/*!
********************************************************************************************
* @file FP_EPSII_BP_1ProtocolTypes.h
* @brief Protocol public type declarations
********************************************************************************************
* @version           interface EPSII_BP_1 v3.0
*
* @copyright         (C) Copyright EnduroSat
*
*                    Contents and presentations are protected world-wide.
*                    Any kind of using, copying etc. is prohibited without prior permission.
*                    All rights - incl. industrial property rights - are reserved.
*
*-------------------------------------------------------------------------------------------
* GENERATOR: org.endurosat.generators.macchiato.binders.Gen_C v2.15
*-------------------------------------------------------------------------------------------
* !!! Please note that this code is fully GENERATED and shall not be manually modified as
* all changes will be overwritten !!!
********************************************************************************************
*/

#ifndef FP_EPSII_BP_1PROTOCOLTYPES_H
#define FP_EPSII_BP_1PROTOCOLTYPES_H

#include <stddef.h>
#include "FP_common/FP_BaseProtocolTypes.h"
#include "FP_common/FP_Helpers.h"

/**********************************************************************
 *
 *  Shared defines
 *
 **********************************************************************/
#define ES_SAT_FUNC_PROTOCOL_ID_EPSII_BP_1 ((uint16_t) (0x00000015))

#define EPSII_BP_1_GETRAWSENSORS_FUNC_ID ((funcIdType_t) 0x00000002)
#define EPSII_BP_1_GETBATTERYINFO_FUNC_ID ((funcIdType_t) 0x00000003)
#define EPSII_BP_1_GETDEVICEHEALTHINFO_FUNC_ID ((funcIdType_t) 0x00000004)
#define EPSII_BP_1_GETRAWSENSORS_FUNCRESP_ID ((funcIdType_t) 0x00000002)
#define EPSII_BP_1_GETBATTERYINFO_FUNCRESP_ID ((funcIdType_t) 0x00000003)
#define EPSII_BP_1_GETDEVICEHEALTHINFO_FUNCRESP_ID ((funcIdType_t) 0x00000004)

/**********************************************************************
 *
 *  Type definitions
 *
 **********************************************************************/
/*
    Telemetry sensors IDs
*/
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_NULL_ID ((uint16_t) 0)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_INA_BAT_OUT_1_I_ID ((uint16_t) 1)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_INA_BAT_OUT_1_U_ID ((uint16_t) 2)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_INA_BAT_OUT_1_P_ID ((uint16_t) 3)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_INA_BAT_OUT_1_T_ID ((uint16_t) 4)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_INA_BAT_OUT_2_I_ID ((uint16_t) 5)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_INA_BAT_OUT_2_U_ID ((uint16_t) 6)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_INA_BAT_OUT_2_P_ID ((uint16_t) 7)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_INA_BAT_OUT_2_T_ID ((uint16_t) 8)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BALANCER1_BAT_U_ID ((uint16_t) 9)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BALANCER1_BAT_I_ID ((uint16_t) 10)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BALANCER1_BAT_P_ID ((uint16_t) 11)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BALANCER1_BAT_CELL_1_U_ID ((uint16_t) 12)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BALANCER1_BAT_CELL_2_U_ID ((uint16_t) 13)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BALANCER1_BAT_CELL_3_U_ID ((uint16_t) 14)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BALANCER1_BAT_CELL_4_U_ID ((uint16_t) 15)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BALANCER1_BAT_CELL_5_U_ID ((uint16_t) 16)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BALANCER1_BAT_CELL_6_U_ID ((uint16_t) 17)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BALANCER1_BAT_CELL_7_U_ID ((uint16_t) 18)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BALANCER1_BAT_CELL_8_U_ID ((uint16_t) 19)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BALANCER1_BAT_SUM_CELL_U_ID ((uint16_t) 20)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BALANCER1_INT_TEMP_ID ((uint16_t) 21)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BALANCER1_STATUS0_ID ((uint16_t) 22)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BALANCER1_STATUS1_ID ((uint16_t) 23)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BALANCER1_STATUS2_ID ((uint16_t) 24)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BALANCER1_STATUS3_ID ((uint16_t) 25)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BALANCER1_CONTROL0_ID ((uint16_t) 26)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BALANCER1_CONTROL1_ID ((uint16_t) 27)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BALANCER1_CONTROL2_ID ((uint16_t) 28)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BALANCER1_CONTROL3_ID ((uint16_t) 29)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_RESERVED_0_ID ((uint16_t) 30)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_RESERVED_1_ID ((uint16_t) 31)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_RESERVED_2_ID ((uint16_t) 32)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_RESERVED_3_ID ((uint16_t) 33)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_RESERVED_4_ID ((uint16_t) 34)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XP_STAT_CHARGER_ID ((uint16_t) 35)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XP_STAT_SYSTEM_ID ((uint16_t) 36)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XP_STAT_SUPPLY_ID ((uint16_t) 37)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XP_STAT_CHRG_FAULTS_ID ((uint16_t) 38)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XP_TELE_TBAT_ID ((uint16_t) 39)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XP_TELE_POUT_ID ((uint16_t) 40)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XP_TELE_PIN_ID ((uint16_t) 41)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XP_TELE_EFF_ID ((uint16_t) 42)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XP_TELE_IOUT_ID ((uint16_t) 43)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XP_TELE_IIN_ID ((uint16_t) 44)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XP_TELE_VBAT_ID ((uint16_t) 45)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XP_TELE_VIN_ID ((uint16_t) 46)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XP_TELE_VINR_ID ((uint16_t) 47)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XR_STAT_CHARGER_ID ((uint16_t) 48)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XR_STAT_SYSTEM_ID ((uint16_t) 49)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XR_STAT_SUPPLY_ID ((uint16_t) 50)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XR_STAT_CHRG_FAULTS_ID ((uint16_t) 51)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XR_TELE_TBAT_ID ((uint16_t) 52)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XR_TELE_POUT_ID ((uint16_t) 53)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XR_TELE_PIN_ID ((uint16_t) 54)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XR_TELE_EFF_ID ((uint16_t) 55)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XR_TELE_IOUT_ID ((uint16_t) 56)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XR_TELE_IIN_ID ((uint16_t) 57)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XR_TELE_VBAT_ID ((uint16_t) 58)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XR_TELE_VIN_ID ((uint16_t) 59)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_XR_TELE_VINR_ID ((uint16_t) 60)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YP_STAT_CHARGER_ID ((uint16_t) 61)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YP_STAT_SYSTEM_ID ((uint16_t) 62)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YP_STAT_SUPPLY_ID ((uint16_t) 63)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YP_STAT_CHRG_FAULTS_ID ((uint16_t) 64)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YP_TELE_TBAT_ID ((uint16_t) 65)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YP_TELE_POUT_ID ((uint16_t) 66)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YP_TELE_PIN_ID ((uint16_t) 67)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YP_TELE_EFF_ID ((uint16_t) 68)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YP_TELE_IOUT_ID ((uint16_t) 69)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YP_TELE_IIN_ID ((uint16_t) 70)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YP_TELE_VBAT_ID ((uint16_t) 71)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YP_TELE_VIN_ID ((uint16_t) 72)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YP_TELE_VINR_ID ((uint16_t) 73)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YR_STAT_CHARGER_ID ((uint16_t) 74)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YR_STAT_SYSTEM_ID ((uint16_t) 75)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YR_STAT_SUPPLY_ID ((uint16_t) 76)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YR_STAT_CHRG_FAULTS_ID ((uint16_t) 77)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YR_TELE_TBAT_ID ((uint16_t) 78)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YR_TELE_POUT_ID ((uint16_t) 79)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YR_TELE_PIN_ID ((uint16_t) 80)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YR_TELE_EFF_ID ((uint16_t) 81)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YR_TELE_IOUT_ID ((uint16_t) 82)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YR_TELE_IIN_ID ((uint16_t) 83)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YR_TELE_VBAT_ID ((uint16_t) 84)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YR_TELE_VIN_ID ((uint16_t) 85)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_YR_TELE_VINR_ID ((uint16_t) 86)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZP_STAT_CHARGER_ID ((uint16_t) 87)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZP_STAT_SYSTEM_ID ((uint16_t) 88)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZP_STAT_SUPPLY_ID ((uint16_t) 89)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZP_STAT_CHRG_FAULTS_ID ((uint16_t) 90)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZP_TELE_TBAT_ID ((uint16_t) 91)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZP_TELE_POUT_ID ((uint16_t) 92)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZP_TELE_PIN_ID ((uint16_t) 93)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZP_TELE_EFF_ID ((uint16_t) 94)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZP_TELE_IOUT_ID ((uint16_t) 95)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZP_TELE_IIN_ID ((uint16_t) 96)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZP_TELE_VBAT_ID ((uint16_t) 97)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZP_TELE_VIN_ID ((uint16_t) 98)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZP_TELE_VINR_ID ((uint16_t) 99)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZR_STAT_CHARGER_ID ((uint16_t) 100)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZR_STAT_SYSTEM_ID ((uint16_t) 101)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZR_STAT_SUPPLY_ID ((uint16_t) 102)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZR_STAT_CHRG_FAULTS_ID ((uint16_t) 103)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZR_TELE_TBAT_ID ((uint16_t) 104)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZR_TELE_POUT_ID ((uint16_t) 105)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZR_TELE_PIN_ID ((uint16_t) 106)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZR_TELE_EFF_ID ((uint16_t) 107)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZR_TELE_IOUT_ID ((uint16_t) 108)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZR_TELE_IIN_ID ((uint16_t) 109)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZR_TELE_VBAT_ID ((uint16_t) 110)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZR_TELE_VIN_ID ((uint16_t) 111)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_CHRG_ZR_TELE_VINR_ID ((uint16_t) 112)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BP_TEMPERATURE_PCB_1_ID ((uint16_t) 113)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BP_TEMPERATURE_PCB_2_ID ((uint16_t) 114)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_ADC_CPU_T_ID ((uint16_t) 115)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_ADC_CPU_AVCC_U_ID ((uint16_t) 116)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_ADC_BAT_TEMP_NTC1_ID ((uint16_t) 117)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_ADC_BAT_TEMP_NTC2_ID ((uint16_t) 118)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_ADC_RAD_FED_ID ((uint16_t) 119)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_HEATER_PWM_PERCENT_ID ((uint16_t) 120)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_HEATER_TARGET_TEMP_ID ((uint16_t) 121)
#define EPSII_BP_1_EPSIIT_SENSORIDS_EPSIIT_BAT_CHARGE_WH_ID ((uint16_t) 122)
#define EPSII_BP_1_EPSIIT_SENSORIDS_MAX_CNT  ((uint16_t) 123)
typedef uint16_t EPSII_BP_1_EPSIIT_SensorIDs_t;

/*
    Status of chips as seen by CPU
*/
#define EPSII_BP_1_EDHI_CHIPSTATUS_EDHICS_EMDCS_UNKNOWN ((uint8_t) 0)
#define EPSII_BP_1_EDHI_CHIPSTATUS_EDHICS_EMDCS_ONLINE ((uint8_t) 1)
#define EPSII_BP_1_EDHI_CHIPSTATUS_EDHICS_EMDCS_COM_ERR ((uint8_t) 2)
#define EPSII_BP_1_EDHI_CHIPSTATUS_EDHICS_EMDCS_COM_TIMEOUT ((uint8_t) 3)
#define EPSII_BP_1_EDHI_CHIPSTATUS_EDHICS_EMDCS_DRV_DISABLED ((uint8_t) 4)
#define EPSII_BP_1_EDHI_CHIPSTATUS_MAX_CNT  ((uint8_t) 5)
typedef uint8_t EPSII_BP_1_EDHI_ChipStatus_t;

/*
    Battery Pack mode type
*/
#define EPSII_BP_1_BP_MODE_TYPE_ROOT ((uint8_t) 0)
#define EPSII_BP_1_BP_MODE_TYPE_IDENTIFYPREVIOUSSTATE ((uint8_t) 1)
#define EPSII_BP_1_BP_MODE_TYPE_BATTERY_AVAILABLE ((uint8_t) 2)
#define EPSII_BP_1_BP_MODE_TYPE_BATTERY ((uint8_t) 3)
#define EPSII_BP_1_BP_MODE_TYPE_TRANSITION_TO_HIB ((uint8_t) 4)
#define EPSII_BP_1_BP_MODE_TYPE_NORMAL ((uint8_t) 5)
#define EPSII_BP_1_BP_MODE_TYPE_HIB ((uint8_t) 6)
#define EPSII_BP_1_BP_MODE_TYPE_NOHIB ((uint8_t) 7)
#define EPSII_BP_1_BP_MODE_TYPE_PANEL ((uint8_t) 8)
#define EPSII_BP_1_BP_MODE_TYPE____HISTORY_BATTERY_AVAILABLE ((uint8_t) 9)
#define EPSII_BP_1_BP_MODE_TYPE_MAX_CNT  ((uint8_t) 10)
typedef uint8_t EPSII_BP_1_BP_Mode_Type_t;


typedef struct {
    uint32_t u32PktIDReq;
    EPSII_BP_1_EPSIIT_SensorIDs_t aeSensorsIDs[50];
} PACKED_STRUCT EPSII_BP_1GetRAWSensorsRequestData_t;


typedef struct {
    uint32_t u32PktID;
    int32_t ai32SensorValues[50];
} PACKED_STRUCT EPSII_BP_1GetRAWSensorsResponseData_t;

typedef struct {
    EPSII_BP_1_BP_Mode_Type_t eBp_mode;
    int64_t i64BattEnergy;
    int64_t i64BattCharge;
    int64_t i64BattChargeCapacity;
    int64_t i64BattPercent;
    int64_t i64BattVoltage;
    int64_t i64BattCurrent;
    int64_t i64BattTemperature;
} PACKED_STRUCT EPSII_BP_1GetBatteryInfoResponseData_t;

typedef struct {
    int32_t i32ActiveCPU_RunningTime;
    int32_t i32ActiveCPU_Voltage;
    int32_t i32ActiveCPU_Temperature;
    int32_t i32PCB_Temperature_1;
    int32_t i32PCB_Temperature_2;
    int32_t i32NVM_AllocatedSize;
    int32_t i32NVM_UsedSize;
    int32_t i32Stack_AllocatedSize;
    int32_t i32Stack_UsedSize;
    EPSII_BP_1_EDHI_ChipStatus_t eBALANCER_CHIP_1;
    EPSII_BP_1_EDHI_ChipStatus_t eBALANCER_CHIP_2;
    EPSII_BP_1_EDHI_ChipStatus_t eLT8491_IC_XP;
    EPSII_BP_1_EDHI_ChipStatus_t eLT8491_IC_XR;
    EPSII_BP_1_EDHI_ChipStatus_t eLT8491_IC_YP;
    EPSII_BP_1_EDHI_ChipStatus_t eLT8491_IC_YR;
    EPSII_BP_1_EDHI_ChipStatus_t eLT8491_IC_ZP;
    EPSII_BP_1_EDHI_ChipStatus_t eLT8491_IC_ZR;
    EPSII_BP_1_EDHI_ChipStatus_t eINA_BAT_OUT_1;
    EPSII_BP_1_EDHI_ChipStatus_t eINA_BAT_OUT_2;
    EPSII_BP_1_EDHI_ChipStatus_t eTMP117_U810;
    EPSII_BP_1_EDHI_ChipStatus_t eTMP117_U811;
    EPSII_BP_1_EDHI_ChipStatus_t eGPIO_PCA9538_U2001;
    EPSII_BP_1_EDHI_ChipStatus_t eGPIO_PCA9538_U2002;
    EPSII_BP_1_EDHI_ChipStatus_t eDPOT_MCP4562_CURRENT_LIMMITER;
} PACKED_STRUCT EPSII_BP_1GetDeviceHealthInfoResponseData_t;


#endif  // #ifndef FP_EPSII_BP_1PROTOCOLTYPES_H

