/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "es_adrv9009.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(es_phya_telemetry_get_req, es_phya_telemetry_get_req, AUTO)


PB_BIND(phya_telemetry_get_res_pl, phya_telemetry_get_res_pl, AUTO)


PB_BIND(es_phya_telemetry_get_res, es_phya_telemetry_get_res, 2)


PB_BIND(phya_telemetry_get_rpc, phya_telemetry_get_rpc, 2)


PB_BIND(es_phyb_telemetry_get_req, es_phyb_telemetry_get_req, AUTO)


PB_BIND(phyb_telemetry_get_res_pl, phyb_telemetry_get_res_pl, AUTO)


PB_BIND(es_phyb_telemetry_get_res, es_phyb_telemetry_get_res, 2)


PB_BIND(phyb_telemetry_get_rpc, phyb_telemetry_get_rpc, 2)


PB_BIND(phya_altvoltage0_set_req_pl, phya_altvoltage0_set_req_pl, AUTO)


PB_BIND(es_phya_altvoltage0_set_req, es_phya_altvoltage0_set_req, AUTO)


PB_BIND(es_phya_altvoltage0_set_res, es_phya_altvoltage0_set_res, 2)


PB_BIND(phya_altvoltage0_set_rpc, phya_altvoltage0_set_rpc, 2)


PB_BIND(phya_altvoltage0_get_res_pl, phya_altvoltage0_get_res_pl, AUTO)


PB_BIND(es_phya_altvoltage0_get_req, es_phya_altvoltage0_get_req, AUTO)


PB_BIND(es_phya_altvoltage0_get_res, es_phya_altvoltage0_get_res, 2)


PB_BIND(phya_altvoltage0_get_rpc, phya_altvoltage0_get_rpc, 2)


PB_BIND(phyb_altvoltage0_set_req_pl, phyb_altvoltage0_set_req_pl, AUTO)


PB_BIND(es_phyb_altvoltage0_set_req, es_phyb_altvoltage0_set_req, AUTO)


PB_BIND(es_phyb_altvoltage0_set_res, es_phyb_altvoltage0_set_res, 2)


PB_BIND(phyb_altvoltage0_set_rpc, phyb_altvoltage0_set_rpc, 2)


PB_BIND(phyb_altvoltage0_get_res_pl, phyb_altvoltage0_get_res_pl, AUTO)


PB_BIND(es_phyb_altvoltage0_get_req, es_phyb_altvoltage0_get_req, AUTO)


PB_BIND(es_phyb_altvoltage0_get_res, es_phyb_altvoltage0_get_res, 2)


PB_BIND(phyb_altvoltage0_get_rpc, phyb_altvoltage0_get_rpc, 2)


PB_BIND(phya_tx1out_voltage0_set_req_pl, phya_tx1out_voltage0_set_req_pl, AUTO)


PB_BIND(es_phya_tx1out_voltage0_set_req, es_phya_tx1out_voltage0_set_req, AUTO)


PB_BIND(es_phya_tx1out_voltage0_set_res, es_phya_tx1out_voltage0_set_res, 2)


PB_BIND(phya_tx1out_voltage0_set_rpc, phya_tx1out_voltage0_set_rpc, 2)


PB_BIND(phya_tx1out_voltage0_get_res_pl, phya_tx1out_voltage0_get_res_pl, AUTO)


PB_BIND(es_phya_tx1out_voltage0_get_req, es_phya_tx1out_voltage0_get_req, AUTO)


PB_BIND(es_phya_tx1out_voltage0_get_res, es_phya_tx1out_voltage0_get_res, 2)


PB_BIND(phya_tx1out_voltage0_get_rpc, phya_tx1out_voltage0_get_rpc, 2)


PB_BIND(phyb_tx1out_voltage0_set_req_pl, phyb_tx1out_voltage0_set_req_pl, AUTO)


PB_BIND(es_phyb_tx1out_voltage0_set_req, es_phyb_tx1out_voltage0_set_req, AUTO)


PB_BIND(es_phyb_tx1out_voltage0_set_res, es_phyb_tx1out_voltage0_set_res, 2)


PB_BIND(phyb_tx1out_voltage0_set_rpc, phyb_tx1out_voltage0_set_rpc, 2)


PB_BIND(phyb_tx1out_voltage0_get_res_pl, phyb_tx1out_voltage0_get_res_pl, AUTO)


PB_BIND(es_phyb_tx1out_voltage0_get_req, es_phyb_tx1out_voltage0_get_req, AUTO)


PB_BIND(es_phyb_tx1out_voltage0_get_res, es_phyb_tx1out_voltage0_get_res, 2)


PB_BIND(phyb_tx1out_voltage0_get_rpc, phyb_tx1out_voltage0_get_rpc, 2)


PB_BIND(phya_tx2out_voltage1_set_req_pl, phya_tx2out_voltage1_set_req_pl, AUTO)


PB_BIND(es_phya_tx2out_voltage1_set_req, es_phya_tx2out_voltage1_set_req, AUTO)


PB_BIND(es_phya_tx2out_voltage1_set_res, es_phya_tx2out_voltage1_set_res, 2)


PB_BIND(phya_tx2out_voltage1_set_rpc, phya_tx2out_voltage1_set_rpc, 2)


PB_BIND(phya_tx2out_voltage1_get_res_pl, phya_tx2out_voltage1_get_res_pl, AUTO)


PB_BIND(es_phya_tx2out_voltage1_get_req, es_phya_tx2out_voltage1_get_req, AUTO)


PB_BIND(es_phya_tx2out_voltage1_get_res, es_phya_tx2out_voltage1_get_res, 2)


PB_BIND(phya_tx2out_voltage1_get_rpc, phya_tx2out_voltage1_get_rpc, 2)


PB_BIND(phyb_tx2out_voltage1_set_req_pl, phyb_tx2out_voltage1_set_req_pl, AUTO)


PB_BIND(es_phyb_tx2out_voltage1_set_req, es_phyb_tx2out_voltage1_set_req, AUTO)


PB_BIND(es_phyb_tx2out_voltage1_set_res, es_phyb_tx2out_voltage1_set_res, 2)


PB_BIND(phyb_tx2out_voltage1_set_rpc, phyb_tx2out_voltage1_set_rpc, 2)


PB_BIND(phyb_tx2out_voltage1_get_res_pl, phyb_tx2out_voltage1_get_res_pl, AUTO)


PB_BIND(es_phyb_tx2out_voltage1_get_req, es_phyb_tx2out_voltage1_get_req, AUTO)


PB_BIND(es_phyb_tx2out_voltage1_get_res, es_phyb_tx2out_voltage1_get_res, 2)


PB_BIND(phyb_tx2out_voltage1_get_rpc, phyb_tx2out_voltage1_get_rpc, 2)


PB_BIND(phya_orx1in_voltage2_set_req_pl, phya_orx1in_voltage2_set_req_pl, AUTO)


PB_BIND(es_phya_orx1in_voltage2_set_req, es_phya_orx1in_voltage2_set_req, AUTO)


PB_BIND(es_phya_orx1in_voltage2_set_res, es_phya_orx1in_voltage2_set_res, 2)


PB_BIND(phya_orx1in_voltage2_set_rpc, phya_orx1in_voltage2_set_rpc, 2)


PB_BIND(phya_orx1in_voltage2_get_res_pl, phya_orx1in_voltage2_get_res_pl, AUTO)


PB_BIND(es_phya_orx1in_voltage2_get_req, es_phya_orx1in_voltage2_get_req, AUTO)


PB_BIND(es_phya_orx1in_voltage2_get_res, es_phya_orx1in_voltage2_get_res, 2)


PB_BIND(phya_orx1in_voltage2_get_rpc, phya_orx1in_voltage2_get_rpc, 2)


PB_BIND(phyb_orx1in_voltage2_set_req_pl, phyb_orx1in_voltage2_set_req_pl, AUTO)


PB_BIND(es_phyb_orx1in_voltage2_set_req, es_phyb_orx1in_voltage2_set_req, AUTO)


PB_BIND(es_phyb_orx1in_voltage2_set_res, es_phyb_orx1in_voltage2_set_res, 2)


PB_BIND(phyb_orx1in_voltage2_set_rpc, phyb_orx1in_voltage2_set_rpc, 2)


PB_BIND(phyb_orx1in_voltage2_get_res_pl, phyb_orx1in_voltage2_get_res_pl, AUTO)


PB_BIND(es_phyb_orx1in_voltage2_get_req, es_phyb_orx1in_voltage2_get_req, AUTO)


PB_BIND(es_phyb_orx1in_voltage2_get_res, es_phyb_orx1in_voltage2_get_res, 2)


PB_BIND(phyb_orx1in_voltage2_get_rpc, phyb_orx1in_voltage2_get_rpc, 2)


PB_BIND(phya_orx2in_voltage3_set_req_pl, phya_orx2in_voltage3_set_req_pl, AUTO)


PB_BIND(es_phya_orx2in_voltage3_set_req, es_phya_orx2in_voltage3_set_req, AUTO)


PB_BIND(es_phya_orx2in_voltage3_set_res, es_phya_orx2in_voltage3_set_res, 2)


PB_BIND(phya_orx2in_voltage3_set_rpc, phya_orx2in_voltage3_set_rpc, 2)


PB_BIND(phya_orx2in_voltage3_get_res_pl, phya_orx2in_voltage3_get_res_pl, AUTO)


PB_BIND(es_phya_orx2in_voltage3_get_req, es_phya_orx2in_voltage3_get_req, AUTO)


PB_BIND(es_phya_orx2in_voltage3_get_res, es_phya_orx2in_voltage3_get_res, 2)


PB_BIND(phya_orx2in_voltage3_get_rpc, phya_orx2in_voltage3_get_rpc, 2)


PB_BIND(phyb_orx2in_voltage3_set_req_pl, phyb_orx2in_voltage3_set_req_pl, AUTO)


PB_BIND(es_phyb_orx2in_voltage3_set_req, es_phyb_orx2in_voltage3_set_req, AUTO)


PB_BIND(es_phyb_orx2in_voltage3_set_res, es_phyb_orx2in_voltage3_set_res, 2)


PB_BIND(phyb_orx2in_voltage3_set_rpc, phyb_orx2in_voltage3_set_rpc, 2)


PB_BIND(phyb_orx2in_voltage3_get_res_pl, phyb_orx2in_voltage3_get_res_pl, AUTO)


PB_BIND(es_phyb_orx2in_voltage3_get_req, es_phyb_orx2in_voltage3_get_req, AUTO)


PB_BIND(es_phyb_orx2in_voltage3_get_res, es_phyb_orx2in_voltage3_get_res, 2)


PB_BIND(phyb_orx2in_voltage3_get_rpc, phyb_orx2in_voltage3_get_rpc, 2)


PB_BIND(phya_rx1in_voltage0_set_req_pl, phya_rx1in_voltage0_set_req_pl, AUTO)


PB_BIND(es_phya_rx1in_voltage0_set_req, es_phya_rx1in_voltage0_set_req, AUTO)


PB_BIND(es_phya_rx1in_voltage0_set_res, es_phya_rx1in_voltage0_set_res, 2)


PB_BIND(phya_rx1in_voltage0_set_rpc, phya_rx1in_voltage0_set_rpc, 2)


PB_BIND(phya_rx1in_voltage0_get_res_pl, phya_rx1in_voltage0_get_res_pl, AUTO)


PB_BIND(es_phya_rx1in_voltage0_get_req, es_phya_rx1in_voltage0_get_req, AUTO)


PB_BIND(es_phya_rx1in_voltage0_get_res, es_phya_rx1in_voltage0_get_res, 2)


PB_BIND(phya_rx1in_voltage0_get_rpc, phya_rx1in_voltage0_get_rpc, 2)


PB_BIND(phyb_rx1in_voltage0_set_req_pl, phyb_rx1in_voltage0_set_req_pl, AUTO)


PB_BIND(es_phyb_rx1in_voltage0_set_req, es_phyb_rx1in_voltage0_set_req, AUTO)


PB_BIND(es_phyb_rx1in_voltage0_set_res, es_phyb_rx1in_voltage0_set_res, 2)


PB_BIND(phyb_rx1in_voltage0_set_rpc, phyb_rx1in_voltage0_set_rpc, 2)


PB_BIND(phyb_rx1in_voltage0_get_res_pl, phyb_rx1in_voltage0_get_res_pl, AUTO)


PB_BIND(es_phyb_rx1in_voltage0_get_req, es_phyb_rx1in_voltage0_get_req, AUTO)


PB_BIND(es_phyb_rx1in_voltage0_get_res, es_phyb_rx1in_voltage0_get_res, 2)


PB_BIND(phyb_rx1in_voltage0_get_rpc, phyb_rx1in_voltage0_get_rpc, 2)


PB_BIND(phya_rx2in_voltage1_set_req_pl, phya_rx2in_voltage1_set_req_pl, AUTO)


PB_BIND(es_phya_rx2in_voltage1_set_req, es_phya_rx2in_voltage1_set_req, AUTO)


PB_BIND(es_phya_rx2in_voltage1_set_res, es_phya_rx2in_voltage1_set_res, 2)


PB_BIND(phya_rx2in_voltage1_set_rpc, phya_rx2in_voltage1_set_rpc, 2)


PB_BIND(phya_rx2in_voltage1_get_res_pl, phya_rx2in_voltage1_get_res_pl, AUTO)


PB_BIND(es_phya_rx2in_voltage1_get_req, es_phya_rx2in_voltage1_get_req, AUTO)


PB_BIND(es_phya_rx2in_voltage1_get_res, es_phya_rx2in_voltage1_get_res, 2)


PB_BIND(phya_rx2in_voltage1_get_rpc, phya_rx2in_voltage1_get_rpc, 2)


PB_BIND(phyb_rx2in_voltage1_set_req_pl, phyb_rx2in_voltage1_set_req_pl, AUTO)


PB_BIND(es_phyb_rx2in_voltage1_set_req, es_phyb_rx2in_voltage1_set_req, AUTO)


PB_BIND(es_phyb_rx2in_voltage1_set_res, es_phyb_rx2in_voltage1_set_res, 2)


PB_BIND(phyb_rx2in_voltage1_set_rpc, phyb_rx2in_voltage1_set_rpc, 2)


PB_BIND(phyb_rx2in_voltage1_get_res_pl, phyb_rx2in_voltage1_get_res_pl, AUTO)


PB_BIND(es_phyb_rx2in_voltage1_get_req, es_phyb_rx2in_voltage1_get_req, AUTO)


PB_BIND(es_phyb_rx2in_voltage1_get_res, es_phyb_rx2in_voltage1_get_res, 2)


PB_BIND(phyb_rx2in_voltage1_get_rpc, phyb_rx2in_voltage1_get_rpc, 2)


PB_BIND(es_adrv9009_rpc, es_adrv9009_rpc, 2)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

