/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "es_board_mgr.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(eth_cfg_get_req_pl, eth_cfg_get_req_pl, AUTO)


PB_BIND(es_eth_cfg_get_req, es_eth_cfg_get_req, AUTO)


PB_BIND(eth_cfg_get_res_pl, eth_cfg_get_res_pl, AUTO)


PB_BIND(es_eth_cfg_get_res, es_eth_cfg_get_res, 2)


PB_BIND(eth_cfg_get_rpc, eth_cfg_get_rpc, 2)


PB_BIND(eth_cfg_set_req_pl, eth_cfg_set_req_pl, AUTO)


PB_BIND(es_eth_cfg_set_req, es_eth_cfg_set_req, AUTO)


PB_BIND(es_eth_cfg_set_res, es_eth_cfg_set_res, 2)


PB_BIND(eth_cfg_set_rpc, eth_cfg_set_rpc, 2)


PB_BIND(csp_cfg_get_req_pl, csp_cfg_get_req_pl, AUTO)


PB_BIND(es_csp_cfg_get_req, es_csp_cfg_get_req, AUTO)


PB_BIND(csp_cfg_get_res_pl, csp_cfg_get_res_pl, AUTO)


PB_BIND(es_csp_cfg_get_res, es_csp_cfg_get_res, 2)


PB_BIND(csp_cfg_get_rpc, csp_cfg_get_rpc, 2)


PB_BIND(csp_cfg_set_req_pl, csp_cfg_set_req_pl, AUTO)


PB_BIND(es_csp_cfg_set_req, es_csp_cfg_set_req, AUTO)


PB_BIND(es_csp_cfg_set_res, es_csp_cfg_set_res, 2)


PB_BIND(csp_cfg_set_rpc, csp_cfg_set_rpc, 2)


PB_BIND(esps_cfg_get_req_pl, esps_cfg_get_req_pl, AUTO)


PB_BIND(es_esps_cfg_get_req, es_esps_cfg_get_req, AUTO)


PB_BIND(esps_cfg_get_res_pl, esps_cfg_get_res_pl, AUTO)


PB_BIND(es_esps_cfg_get_res, es_esps_cfg_get_res, 2)


PB_BIND(esps_cfg_get_rpc, esps_cfg_get_rpc, 2)


PB_BIND(esps_cfg_set_req_pl, esps_cfg_set_req_pl, AUTO)


PB_BIND(es_esps_cfg_set_req, es_esps_cfg_set_req, AUTO)


PB_BIND(es_esps_cfg_set_res, es_esps_cfg_set_res, 2)


PB_BIND(esps_cfg_set_rpc, esps_cfg_set_rpc, 2)


PB_BIND(bundle_info_req_pl, bundle_info_req_pl, AUTO)


PB_BIND(es_bundle_info_req, es_bundle_info_req, AUTO)


PB_BIND(bundle_info_res_pl, bundle_info_res_pl, AUTO)


PB_BIND(es_bundle_info_res, es_bundle_info_res, 2)


PB_BIND(bundle_info_rpc, bundle_info_rpc, 2)


PB_BIND(bundle_install_req_pl, bundle_install_req_pl, AUTO)


PB_BIND(es_bundle_install_req, es_bundle_install_req, AUTO)


PB_BIND(es_bundle_install_res, es_bundle_install_res, 2)


PB_BIND(bundle_install_rpc, bundle_install_rpc, 2)


PB_BIND(es_update_progress_req, es_update_progress_req, AUTO)


PB_BIND(update_progress_res_pl, update_progress_res_pl, AUTO)


PB_BIND(es_update_progress_res, es_update_progress_res, 2)


PB_BIND(update_progress_rpc, update_progress_rpc, 2)


PB_BIND(slot_status_req_pl, slot_status_req_pl, AUTO)


PB_BIND(es_slot_status_req, es_slot_status_req, AUTO)


PB_BIND(slot_status_res_pl, slot_status_res_pl, 2)


PB_BIND(es_slot_status_res, es_slot_status_res, 2)


PB_BIND(slot_status_rpc, slot_status_rpc, 2)


PB_BIND(mark_slot_req_pl, mark_slot_req_pl, AUTO)


PB_BIND(es_mark_slot_req, es_mark_slot_req, AUTO)


PB_BIND(es_mark_slot_res, es_mark_slot_res, 2)


PB_BIND(mark_slot_rpc, mark_slot_rpc, 2)


PB_BIND(es_get_primary_slot_req, es_get_primary_slot_req, AUTO)


PB_BIND(get_primary_slot_res_pl, get_primary_slot_res_pl, AUTO)


PB_BIND(es_get_primary_slot_res, es_get_primary_slot_res, 2)


PB_BIND(get_primary_slot_rpc, get_primary_slot_rpc, 2)


PB_BIND(sys_time_set_rpc, sys_time_set_rpc, 2)


PB_BIND(es_sys_time_set_req, es_sys_time_set_req, AUTO)


PB_BIND(sys_time_set_req_pl, sys_time_set_req_pl, AUTO)


PB_BIND(es_sys_time_set_res, es_sys_time_set_res, 2)


PB_BIND(sys_time_get_rpc, sys_time_get_rpc, 2)


PB_BIND(es_sys_time_get_req, es_sys_time_get_req, AUTO)


PB_BIND(es_sys_time_get_res, es_sys_time_get_res, 2)


PB_BIND(sys_time_get_res_pl, sys_time_get_res_pl, AUTO)


PB_BIND(sys_time_pps_lock_stat_get_rpc, sys_time_pps_lock_stat_get_rpc, 2)


PB_BIND(es_sys_time_pps_lock_stat_get_req, es_sys_time_pps_lock_stat_get_req, AUTO)


PB_BIND(es_sys_time_pps_lock_stat_get_res, es_sys_time_pps_lock_stat_get_res, 2)


PB_BIND(sys_time_pps_lock_stat_get_res_pl, sys_time_pps_lock_stat_get_res_pl, AUTO)


PB_BIND(sys_time_pps_offset_get_rpc, sys_time_pps_offset_get_rpc, 2)


PB_BIND(es_sys_time_pps_offset_get_req, es_sys_time_pps_offset_get_req, AUTO)


PB_BIND(es_sys_time_pps_offset_get_res, es_sys_time_pps_offset_get_res, 2)


PB_BIND(sys_time_pps_offset_get_res_pl, sys_time_pps_offset_get_res_pl, AUTO)


PB_BIND(rtc_time_get_rpc, rtc_time_get_rpc, 2)


PB_BIND(es_rtc_time_get_req, es_rtc_time_get_req, AUTO)


PB_BIND(es_rtc_time_get_res, es_rtc_time_get_res, 2)


PB_BIND(rtc_time_get_res_pl, rtc_time_get_res_pl, AUTO)


PB_BIND(rtc_time_force_sync_rpc, rtc_time_force_sync_rpc, 2)


PB_BIND(es_rtc_time_force_sync_req, es_rtc_time_force_sync_req, AUTO)


PB_BIND(es_rtc_time_force_sync_res, es_rtc_time_force_sync_res, 2)


PB_BIND(rf_board_stat_set_rpc, rf_board_stat_set_rpc, 2)


PB_BIND(es_rf_board_stat_set_req, es_rf_board_stat_set_req, AUTO)


PB_BIND(rf_board_stat_set_req_pl, rf_board_stat_set_req_pl, AUTO)


PB_BIND(es_rf_board_stat_set_res, es_rf_board_stat_set_res, 2)


PB_BIND(rf_board_stat_get_rpc, rf_board_stat_get_rpc, 2)


PB_BIND(es_rf_board_stat_get_req, es_rf_board_stat_get_req, AUTO)


PB_BIND(es_rf_board_stat_get_res, es_rf_board_stat_get_res, 2)


PB_BIND(system_halt_rpc, system_halt_rpc, 2)


PB_BIND(es_system_halt_req, es_system_halt_req, AUTO)


PB_BIND(es_system_halt_res, es_system_halt_res, 2)


PB_BIND(rf_board_stat_get_res_pl, rf_board_stat_get_res_pl, AUTO)


PB_BIND(es_board_mgr_rpc, es_board_mgr_rpc, 2)


