/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "es_board_info.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(software_version_get_req_pl, software_version_get_req_pl, AUTO)


PB_BIND(es_software_version_get_req, es_software_version_get_req, AUTO)


PB_BIND(software_version_get_res_pl, software_version_get_res_pl, AUTO)


PB_BIND(es_software_version_get_res, es_software_version_get_res, 2)


PB_BIND(software_version_get_rpc, software_version_get_rpc, 2)


PB_BIND(es_system_info_get_req, es_system_info_get_req, AUTO)


PB_BIND(system_info_get_res_pl, system_info_get_res_pl, AUTO)


PB_BIND(es_system_info_get_res, es_system_info_get_res, 2)


PB_BIND(system_info_get_rpc, system_info_get_rpc, 2)


PB_BIND(es_adm1177_tel_get_req, es_adm1177_tel_get_req, AUTO)


PB_BIND(adm1177_tel_get_res_pl, adm1177_tel_get_res_pl, AUTO)


PB_BIND(es_adm1177_tel_get_res, es_adm1177_tel_get_res, 2)


PB_BIND(adm1177_tel_get_rpc, adm1177_tel_get_rpc, 2)


PB_BIND(es_ams_tel_get_req, es_ams_tel_get_req, AUTO)


PB_BIND(ams_tel_get_res_pl, ams_tel_get_res_pl, 2)


PB_BIND(es_ams_tel_get_res, es_ams_tel_get_res, 2)


PB_BIND(ams_tel_get_rpc, ams_tel_get_rpc, 2)


PB_BIND(es_serial_get_req, es_serial_get_req, AUTO)


PB_BIND(serial_get_res_pl, serial_get_res_pl, AUTO)


PB_BIND(es_serial_get_res, es_serial_get_res, 2)


PB_BIND(serial_get_rpc, serial_get_rpc, 2)


PB_BIND(es_reset_reason_get_req, es_reset_reason_get_req, AUTO)


PB_BIND(reset_reason_get_res_pl, reset_reason_get_res_pl, AUTO)


PB_BIND(es_reset_reason_get_res, es_reset_reason_get_res, 2)


PB_BIND(reset_reason_get_rpc, reset_reason_get_rpc, 2)


PB_BIND(es_board_info_rpc, es_board_info_rpc, 2)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

