/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "es_file_transfer.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(es_ftp_rrq_wrq_pkt, es_ftp_rrq_wrq_pkt, AUTO)


PB_BIND(es_ftp_data_pkt, es_ftp_data_pkt, 4)


PB_BIND(es_ftp_ack_pkt, es_ftp_ack_pkt, AUTO)


PB_BIND(es_ftp_err_pkt, es_ftp_err_pkt, AUTO)


PB_BIND(es_ftp_pkt, es_ftp_pkt, 4)





