/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "es_iprium_dvb_s2.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(dvb_s2_core0_set_req_pl, dvb_s2_core0_set_req_pl, AUTO)


PB_BIND(es_dvb_s2_core0_set_req, es_dvb_s2_core0_set_req, AUTO)


PB_BIND(es_dvb_s2_core0_set_res, es_dvb_s2_core0_set_res, 2)


PB_BIND(dvb_s2_core0_set_rpc, dvb_s2_core0_set_rpc, 2)


PB_BIND(es_dvb_s2_core0_get_req, es_dvb_s2_core0_get_req, AUTO)


PB_BIND(dvb_s2_core0_get_res_pl, dvb_s2_core0_get_res_pl, AUTO)


PB_BIND(es_dvb_s2_core0_get_res, es_dvb_s2_core0_get_res, 2)


PB_BIND(dvb_s2_core0_get_rpc, dvb_s2_core0_get_rpc, 2)


PB_BIND(tsgen_set_req_pl, tsgen_set_req_pl, AUTO)


PB_BIND(es_tsgen_set_req, es_tsgen_set_req, AUTO)


PB_BIND(es_tsgen_set_res, es_tsgen_set_res, 2)


PB_BIND(tsgen_set_rpc, tsgen_set_rpc, 2)


PB_BIND(es_tsgen_get_req, es_tsgen_get_req, AUTO)


PB_BIND(tsgen_get_res_pl, tsgen_get_res_pl, AUTO)


PB_BIND(es_tsgen_get_res, es_tsgen_get_res, 2)


PB_BIND(tsgen_get_rpc, tsgen_get_rpc, 2)


PB_BIND(clk_wiz_set_req_pl, clk_wiz_set_req_pl, AUTO)


PB_BIND(es_clk_wiz_set_req, es_clk_wiz_set_req, AUTO)


PB_BIND(es_clk_wiz_set_res, es_clk_wiz_set_res, 2)


PB_BIND(clk_wiz_set_rpc, clk_wiz_set_rpc, 2)


PB_BIND(es_clk_wiz_get_req, es_clk_wiz_get_req, AUTO)


PB_BIND(clk_wiz_get_res_pl, clk_wiz_get_res_pl, AUTO)


PB_BIND(es_clk_wiz_get_res, es_clk_wiz_get_res, 2)


PB_BIND(clk_wiz_get_rpc, clk_wiz_get_rpc, 2)


PB_BIND(xbar_set_req_pl, xbar_set_req_pl, AUTO)


PB_BIND(es_xbar_set_req, es_xbar_set_req, AUTO)


PB_BIND(es_xbar_set_res, es_xbar_set_res, 2)


PB_BIND(xbar_set_rpc, xbar_set_rpc, 2)


PB_BIND(es_xbar_get_req, es_xbar_get_req, AUTO)


PB_BIND(xbar_get_res_pl, xbar_get_res_pl, AUTO)


PB_BIND(es_xbar_get_res, es_xbar_get_res, 2)


PB_BIND(xbar_get_rpc, xbar_get_rpc, 2)


PB_BIND(es_iprium_dvb_s2_rpc, es_iprium_dvb_s2_rpc, 2)



