/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "es_rce.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cmd_exec_req_pl, cmd_exec_req_pl, AUTO)


PB_BIND(es_cmd_exec_req, es_cmd_exec_req, AUTO)


PB_BIND(es_cmd_exec_res, es_cmd_exec_res, 2)


PB_BIND(cmd_exec_rpc, cmd_exec_rpc, 2)


PB_BIND(cmd_get_status_req_pl, cmd_get_status_req_pl, AUTO)


PB_BIND(es_cmd_get_status_req, es_cmd_get_status_req, AUTO)


PB_BIND(cmd_get_status_res_pl, cmd_get_status_res_pl, AUTO)


PB_BIND(es_cmd_get_status_res, es_cmd_get_status_res, 2)


PB_BIND(cmd_get_status_rpc, cmd_get_status_rpc, 2)


PB_BIND(es_rce_rpc, es_rce_rpc, 2)




