/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "es_test.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(loopback_req_pl, loopback_req_pl, 2)


PB_BIND(es_loopback_req, es_loopback_req, 2)


PB_BIND(loopback_res_pl, loopback_res_pl, 2)


PB_BIND(es_loopback_res, es_loopback_res, 2)


PB_BIND(loopback_rpc, loopback_rpc, 2)


PB_BIND(test_cfg_set_req_pl, test_cfg_set_req_pl, AUTO)


PB_BIND(es_test_cfg_set_req, es_test_cfg_set_req, AUTO)


PB_BIND(es_test_cfg_set_res, es_test_cfg_set_res, 2)


PB_BIND(test_cfg_set_rpc, test_cfg_set_rpc, 2)


PB_BIND(es_test_cfg_get_req, es_test_cfg_get_req, AUTO)


PB_BIND(test_cfg_get_res_pl, test_cfg_get_res_pl, AUTO)


PB_BIND(es_test_cfg_get_res, es_test_cfg_get_res, 2)


PB_BIND(test_cfg_get_rpc, test_cfg_get_rpc, 2)


PB_BIND(es_hello_test_req, es_hello_test_req, AUTO)


PB_BIND(hello_test_req_pl, hello_test_req_pl, AUTO)


PB_BIND(es_hello_test_res, es_hello_test_res, 2)


PB_BIND(hello_test_rpc, hello_test_rpc, 2)


PB_BIND(es_test_rpc, es_test_rpc, 2)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

