/*
 * Copyright (c) EnduroSat AD. All rights reserved.
 *
 * Contents and presentations are protected world-wide.
 * Any kind of using, copying etc. is prohibited without prior permission.
 * -----------------------------------------------------------------------------
 * This is a generated file. Do not modify manually as the changes may be
 * overwritten.
 * -----------------------------------------------------------------------------
 */

#include <assert.h>
#include "datacache.h"
#include "telemetry_cfg_defs.h"
#include "telemetry_types.h"

// the worst case size calculation for telemetry COBS-encoded frames includes:
// 1) tlm_frame_hdr_t (telemetry frame header)
// 2) the DataCache structure bytes
// 3) tlm_msg_footer_t (telemetry frame footer)
// 4) COBS-overhead for delimiters which is 1 additional length byte for every 254 non-zero bytes
#define WORST_CASE_SZ_FOR_DC_ATTR(struct_name)	(sizeof(tlm_frame_hdr_t) + sizeof(struct_name) + sizeof(tlm_msg_footer_t) + ((sizeof(struct_name) / 254))) 

static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_OBC_0_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_ADCS_0_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_ADCS_1_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_ADCS_2_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_EPS_0_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_SSP_0_Telemetry_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_SSP_1_Telemetry_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_SSP_2_Telemetry_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_SSP_3_Telemetry_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_AOCS_CNTRL_TLM_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_AOCS_CNTRL_SYS_STATE_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_AOCS_CNTRL_REF_PARAMS_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_SENSOR_GYRO_SENSOR_FRAME_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_SENSOR_GYRO_BODY_FRAME_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_SENSOR_MAG_PRIMARY_SENSOR_FRAME_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_SENSOR_MAG_PRIMARY_BODY_FRAME_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_SENSOR_MAG_SECONDARY_SENSOR_FRAME_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_SENSOR_MAG_SECONDARY_BODY_FRAME_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_SENSOR_COARSE_SUN_SENSOR_FRAME_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_SENSOR_COARSE_SUN_BODY_FRAME_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_SENSOR_PANEL_TEMP_SENSOR_FRAME_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_SENSOR_PANEL_TEMP_BODY_FRAME_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_SENSOR_GYRO_TEMP_SENSOR_FRAME_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_SENSOR_GYRO_TEMP_BODY_FRAME_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_ACTUATOR_MTQ_VALUES_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_ACTUATOR_TORQUE_VALUES_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_ADCS_3_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_ADCS_4_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_EPS_9_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_EPS_10_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_EPS_14_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_OP_STATUS_COMMON_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_OP_STATUS_APP_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_166_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_167_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_168_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_169_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_170_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_171_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_172_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_173_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_174_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_175_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_176_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_177_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_178_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_179_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_180_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_203_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_204_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_205_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_206_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_207_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_208_1_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_208_2_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_209_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_210_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_211_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_212_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_213_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_214_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_216_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_217_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_218_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_225_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_226_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_165_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_CUBEADCS_GEN2_TLM_FRAME_221_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_GNSS_TIME_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_GNSS_BESTXYZ_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_SAT_STATE_VECTOR_FROM_PROPAGATOR_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_SAT_MAG_FIELD_VECTOR_FROM_MODEL_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_SAT_MAG_FIELD_VECTOR_FROM_SENSOR_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_FDIR_EPS_I_CMD_EXEC_STATUS_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_FDIR_EPS_II_PDM_CMD_EXEC_STATUS_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_FDIR_CUBEADCS_CMD_EXEC_STATUS_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_FDIR_CUBEADCS_GEN2_CMD_EXEC_STATUS_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_FDIR_CUBEADCS_GEN2_EVENTS_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_FDIR_S_BAND_TMTC_CMD_EXEC_STATUS_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_FDIR_UHF_CMD_EXEC_STATUS_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_FDIR_GNSS_CMD_EXEC_STATUS_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_FDIR_SDR_CMD_EXEC_STATUS_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_FDIR_S_X_BAND_CMD_EXEC_STATUS_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_FDIR_THRUSTER_CMD_EXEC_STATUS_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_XBandFeTelemetry_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_EpsOverallBatteryInfoType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_PPS_Telemetry_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_FDIR_EPS_III_PDM_CMD_EXEC_STATUS_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst0BatteryInfoType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst0DeviceHealthInfoType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst0InaSensors1Type_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst0InaSensors2Type_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst0BalancerInfoType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst0BalancerStatusType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst0BalancerCellsInfoType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst0ChargerXpType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst0ChargerXrType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst0ChargerYpType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst0ChargerYrType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst0ChargerZpType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst0ChargerZrType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst0_FDIR_CMD_EXEC_STATUS_type_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst1BatteryInfoType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst1DeviceHealthInfoType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst1InaSensors1Type_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst1InaSensors2Type_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst1BalancerInfoType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst1BalancerStatusType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst1BalancerCellsInfoType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst1ChargerXpType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst1ChargerXrType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst1ChargerYpType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst1ChargerYrType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst1ChargerZpType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst1ChargerZrType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps2Inst1_FDIR_CMD_EXEC_STATUS_type_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3Inst0_UpTimeInSecondsType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3Inst0CommonMeasurementType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3Inst0HIBModeStatusType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3Inst0MeasurementsType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3Inst0DischargeStateType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3Inst0ChargeOnStatusType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3Inst0BalancersStatusType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3Inst0BatteryCellsStatusType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3Inst0HeatersStatusType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3Inst0_FDIR_CMD_EXEC_STATUS_type_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_VoltAmps_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_VoltAllAmps_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_MpptState_str_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_ReadEnDftStatus_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_OnOffStatus_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_ReadLvlState_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_PDM_A_Inst0_UpTimeInSecondsType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_PDM_A_Inst0_CommonMesurementsType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_PDM_A_Inst0_HibModeType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_PDM_A_Inst0_OutputsStatusType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_PDM_A_Inst0_FaultsStatusType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_PDM_A_Inst0_VoltAmpsMeasurementsType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_PDM_A_Inst0_FDIR_CMD_EXEC_STATUS_type_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_PDM_B_Inst0_FDIR_CMD_EXEC_STATUS_type_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_PDM_B_Inst0_UpTimeInSecondsType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_PDM_B_Inst0_CommonMeasurementType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_PDM_B_Inst0_hib_mode_Type_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_PDM_B_Inst0_OutputsStatus_type_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_PDM_B_Inst0_ChannelFlagState_type_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_PDM_B_Inst0_Temps_type_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_PDM_B_Inst0_VoltAmpsMeasurements_type_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_EXPANDER_Inst0_FDIR_CMD_EXEC_STATUS_type_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_EXPANDER_Inst0_UpTimeInSecondsType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_EXPANDER_Inst0_CommonMeasurementType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_EXPANDER_Inst0_DigitalOutputsType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_EXPANDER_Inst0_GeneralInputType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_EXPANDER_Inst0_FeedbackType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_EXPANDER_Inst0_CurrentLimitersType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_INPUT_STAGE_Inst0_UpTimeInSecondsType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_INPUT_STAGE_Inst0CommonMeasurementType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_INPUT_STAGE_Inst0hib_mode_status_type_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_INPUT_STAGE_Inst0selflock_on_type_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_INPUT_STAGE_Inst0Sp1InputDataType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_INPUT_STAGE_Inst0Sp2InputDataType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_INPUT_STAGE_Inst0Sp3InputDataType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_INPUT_STAGE_Inst0SystemBusType_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_INPUT_STAGE_Inst0Bus7v5Type_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_INPUT_STAGE_Inst0bus_7v5_power_good_type_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_INPUT_STAGE_Inst0undervoltage_7V5_type_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_INPUT_STAGE_Inst0Bbus3v3Type_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_INPUT_STAGE_Inst0undervoltage_3V3_type_t) <= TLM_BUF_SIZE);
static_assert(WORST_CASE_SZ_FOR_DC_ATTR(DATA_CACHE_Eps3_INPUT_STAGE_Inst0_FDIR_CMD_EXEC_STATUS_type_t) <= TLM_BUF_SIZE);
