/*
 * Copyright (c) EnduroSat AD. All rights reserved.
 *
 * Contents and presentations are protected world-wide.
 * Any kind of using, copying etc. is prohibited without prior permission.
 * -----------------------------------------------------------------------------
 * Generated by hsmgen 2.0.1
 * -----------------------------------------------------------------------------
 */

#ifndef TELEMETRY_SM_CONFIG_USER_H
#define TELEMETRY_SM_CONFIG_USER_H

#ifdef __cplusplus
extern "C" {
#endif

#include "libhsm.h"

// USER_CODE_START::@main@
// Any code placed between these two tags will be preserved during code generation!
#include "telemetry_context_types.h"

/** @brief Load the telemetry configuration from the NVM */
void telemetry_load_config(tlm_runtime_context_t *const p_tlm_rt_ctx);

// USER_CODE_END::@main@

// Entry/Exit functions
void telemetry_sm_on_entry_Init(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);
void telemetry_sm_on_entry_Started(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);
void telemetry_sm_on_exit_Started(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);
void telemetry_sm_on_entry_Stopped(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);

// Guard condition functions
bool telemetry_sm_guard_is_hold_time_elapsed(const uint16_t instance_id, const sState_t* const pSMRoot, const sHSM_EventType_t * const pEvent);

// Action handlers
void telemetry_sm_action_reload_config(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);
void telemetry_sm_action_stop_file_telemetry(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);
void telemetry_sm_action_collect_telemetry(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);
void telemetry_sm_action_start_file_telemetry(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);

#ifdef __cplusplus
};
#endif

#endif  // #ifndef TELEMETRY_SM_CONFIG_USER_H