/*
 * Copyright (c) EnduroSat AD. All rights reserved.
 *
 * Contents and presentations are protected world-wide.
 * Any kind of using, copying etc. is prohibited without prior permission.
 * -----------------------------------------------------------------------------
 * Generated by hsmgen 2.0.1
 * -----------------------------------------------------------------------------
 */

#include <stddef.h>
#include "libhsm.h"
#include "telemetry_file_sink_sm_config_user.h"
#include "telemetry_file_sink_sm_user.h"


static const sTransition_t tran_Not_Init_ev_init_Init;
static const sTransition_t tran_Init_ev_start_Wait_Storage;
static const sTransition_t tran_Init_ev_periodic_self;
static const sTransition_t tran_Wait_Storage_ev_periodic_Started;
static const sTransition_t tran_Started_ev_stop_Stopped;
static const sTransition_t tran_Started_ev_periodic_self;
static const sTransition_t tran_Started_ev_periodic_Wait_Storage;
static const sTransition_t tran_Started_ev_restart_Wait_Storage;
static const sTransition_t tran_Started_ev_file_cleanup_triggered_Wait_Cleanup;
static const sTransition_t tran_Stopped_ev_start_Wait_Storage;
static const sTransition_t tran_Stopped_ev_periodic_self;
static const sTransition_t tran_Wait_Cleanup_ev_periodic_Wait_Storage;


static const sTransition_t* trans_Not_Init[2] =
{
    &tran_Not_Init_ev_init_Init,
    NULL
};

static const sTransition_t* trans_Init[3] =
{
    &tran_Init_ev_start_Wait_Storage,
    &tran_Init_ev_periodic_self,
    NULL
};

static const sTransition_t* trans_Wait_Storage[2] =
{
    &tran_Wait_Storage_ev_periodic_Started,
    NULL
};

static const sTransition_t* trans_Started[6] =
{
    &tran_Started_ev_stop_Stopped,
    &tran_Started_ev_periodic_self,
    &tran_Started_ev_periodic_Wait_Storage,
    &tran_Started_ev_restart_Wait_Storage,
    &tran_Started_ev_file_cleanup_triggered_Wait_Cleanup,
    NULL
};

static const sTransition_t* trans_Stopped[3] =
{
    &tran_Stopped_ev_start_Wait_Storage,
    &tran_Stopped_ev_periodic_self,
    NULL
};

static const sTransition_t* trans_Wait_Cleanup[2] =
{
    &tran_Wait_Cleanup_ev_periodic_Wait_Storage,
    NULL
};


// telemetry_file_sink_sm states forward declarations
static const sState_t state_Not_Init;
static const sState_t state_Init;
static const sState_t state_Wait_Storage;
static const sState_t state_Started;
static const sState_t state_Stopped;
static const sState_t state_Wait_Cleanup;

// history/active states instance lists definitions

static sState_t *p_telemetry_file_sink_sm_inst_history[TELEMETRY_FILE_SINK_SM_INSTANCE_CNT] = {
    HSM_UPCAST_STATE(&state_Not_Init),HSM_UPCAST_STATE(&state_Not_Init),
};

static sState_t *p_telemetry_file_sink_sm_inst_active_states[TELEMETRY_FILE_SINK_SM_INSTANCE_CNT] = {
    HSM_UPCAST_STATE(&state_telemetry_file_sink_sm),HSM_UPCAST_STATE(&state_telemetry_file_sink_sm),
};

// telemetry_file_sink_sm root state definition
sCompositeState_t state_telemetry_file_sink_sm =
{
    .state =
    {
        .state_id = TELEMETRY_FILE_SINK_SM_ROOT,
        .pName = "state_telemetry_file_sink_sm",
        .onEntryFunc = NULL,
        .onExitFunc = NULL,
        .pTransitionList = NULL,
        .eType = eHSM_StateType_Composite,
        .pParent = NULL
    },
    .pInitialState = HSM_UPCAST_STATE(&state_Not_Init),
    .instanceCnt = 2,
    .ppHistoryState = p_telemetry_file_sink_sm_inst_history,
    .ppActiveState = p_telemetry_file_sink_sm_inst_active_states
};

static const sState_t state_Not_Init =
{
    .state_id = TELEMETRY_FILE_SINK_SM_STATE_NOT_INIT,
    .pName = "state_Not_Init",
    .onEntryFunc = NULL,
    .onExitFunc = NULL,
    .pTransitionList = trans_Not_Init,
    .eType = eHSM_StateType_Simple,
    .pParent = HSM_UPCAST_STATE(&state_telemetry_file_sink_sm)
};


static const sState_t state_Init =
{
    .state_id = TELEMETRY_FILE_SINK_SM_STATE_INIT,
    .pName = "state_Init",
    .onEntryFunc = &telemetry_file_sink_sm_on_entry_Init,
    .onExitFunc = NULL,
    .pTransitionList = trans_Init,
    .eType = eHSM_StateType_Simple,
    .pParent = HSM_UPCAST_STATE(&state_telemetry_file_sink_sm)
};


static const sState_t state_Wait_Storage =
{
    .state_id = TELEMETRY_FILE_SINK_SM_STATE_WAIT_STORAGE,
    .pName = "state_Wait_Storage",
    .onEntryFunc = NULL,
    .onExitFunc = NULL,
    .pTransitionList = trans_Wait_Storage,
    .eType = eHSM_StateType_Simple,
    .pParent = HSM_UPCAST_STATE(&state_telemetry_file_sink_sm)
};


static const sState_t state_Started =
{
    .state_id = TELEMETRY_FILE_SINK_SM_STATE_STARTED,
    .pName = "state_Started",
    .onEntryFunc = NULL,
    .onExitFunc = NULL,
    .pTransitionList = trans_Started,
    .eType = eHSM_StateType_Simple,
    .pParent = HSM_UPCAST_STATE(&state_telemetry_file_sink_sm)
};


static const sState_t state_Stopped =
{
    .state_id = TELEMETRY_FILE_SINK_SM_STATE_STOPPED,
    .pName = "state_Stopped",
    .onEntryFunc = NULL,
    .onExitFunc = NULL,
    .pTransitionList = trans_Stopped,
    .eType = eHSM_StateType_Simple,
    .pParent = HSM_UPCAST_STATE(&state_telemetry_file_sink_sm)
};


static const sState_t state_Wait_Cleanup =
{
    .state_id = TELEMETRY_FILE_SINK_SM_STATE_WAIT_CLEANUP,
    .pName = "state_Wait_Cleanup",
    .onEntryFunc = &telemetry_file_sink_sm_on_entry_Wait_Cleanup,
    .onExitFunc = &telemetry_file_sink_sm_on_exit_Wait_Cleanup,
    .pTransitionList = trans_Wait_Cleanup,
    .eType = eHSM_StateType_Simple,
    .pParent = HSM_UPCAST_STATE(&state_telemetry_file_sink_sm)
};

static const sTransition_t tran_Not_Init_ev_init_Init =
{
    .eventId = ev_telemetry_file_sink_sm_init,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state_Init),
    .onTransitionActionFunc = NULL
};

static const sTransition_t tran_Init_ev_start_Wait_Storage =
{
    .eventId = ev_telemetry_file_sink_sm_start,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state_Wait_Storage),
    .onTransitionActionFunc = &telemetry_file_sink_sm_action_reload_config,
};

static const sTransition_t tran_Init_ev_periodic_self =
{
    .eventId = eHSM_StdEvent_Periodic,
    .guardFunc = NULL,
    .pTargetState = NULL,
    .onTransitionActionFunc = &telemetry_file_sink_sm_action_reload_config,
};

static const sTransition_t tran_Wait_Storage_ev_periodic_Started =
{
    .eventId = eHSM_StdEvent_Periodic,
    .guardFunc = &telemetry_file_sink_sm_guard_is_storage_available,
    .pTargetState = HSM_UPCAST_STATE(&state_Started),
    .onTransitionActionFunc = &telemetry_file_sink_sm_action_prepare_file_telemetry,
};

static const sTransition_t tran_Started_ev_stop_Stopped =
{
    .eventId = ev_telemetry_file_sink_sm_stop,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state_Stopped),
    .onTransitionActionFunc = NULL
};

static const sTransition_t tran_Started_ev_periodic_self =
{
    .eventId = eHSM_StdEvent_Periodic,
    .guardFunc = &telemetry_file_sink_sm_guard_is_storage_available,
    .pTargetState = NULL,
    .onTransitionActionFunc = &telemetry_file_sink_sm_action_store_telemetry,
};

static const sTransition_t tran_Started_ev_periodic_Wait_Storage =
{
    .eventId = eHSM_StdEvent_Periodic,
    .guardFunc = &telemetry_file_sink_sm_guard_is_storage_blocked,
    .pTargetState = HSM_UPCAST_STATE(&state_Wait_Storage),
    .onTransitionActionFunc = NULL
};

static const sTransition_t tran_Started_ev_restart_Wait_Storage =
{
    .eventId = ev_telemetry_file_sink_sm_restart,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state_Wait_Storage),
    .onTransitionActionFunc = &telemetry_file_sink_sm_action_clean_and_reload_cfg,
};

static const sTransition_t tran_Started_ev_file_cleanup_triggered_Wait_Cleanup =
{
    .eventId = ev_telemetry_file_sink_sm_file_cleanup_triggered,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state_Wait_Cleanup),
    .onTransitionActionFunc = NULL
};

static const sTransition_t tran_Stopped_ev_start_Wait_Storage =
{
    .eventId = ev_telemetry_file_sink_sm_start,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state_Wait_Storage),
    .onTransitionActionFunc = NULL
};

static const sTransition_t tran_Stopped_ev_periodic_self =
{
    .eventId = eHSM_StdEvent_Periodic,
    .guardFunc = NULL,
    .pTargetState = NULL,
    .onTransitionActionFunc = &telemetry_file_sink_sm_action_reload_config,
};

static const sTransition_t tran_Wait_Cleanup_ev_periodic_Wait_Storage =
{
    .eventId = eHSM_StdEvent_Periodic,
    .guardFunc = &telemetry_file_sink_sm_guard_is_cleanup_finished,
    .pTargetState = HSM_UPCAST_STATE(&state_Wait_Storage),
    .onTransitionActionFunc = NULL
};
