/*
 * Copyright (c) EnduroSat AD. All rights reserved.
 *
 * Contents and presentations are protected world-wide.
 * Any kind of using, copying etc. is prohibited without prior permission.
 * -----------------------------------------------------------------------------
 * Generated by hsmgen 2.0.1
 * -----------------------------------------------------------------------------
 */

#include "libhsm.h"
#include "telemetry_file_sink_sm_config_user.h"

// USER_CODE_START::@main@
// Any code placed between these two tags will be preserved during code generation!

/**
 * @addtogroup service_tlm
 * @{
 *
 * @file telemetry_file_sink_sm_config_user.c
 * @brief Telemetry file sink state machine functions implementation
 *
 * @note This file contains generated code by libhsm based on `telemetry_file_sink_sm.yaml`.
 *
 * @}
 */
#include <string.h>
#include <stdio.h>
#include <inttypes.h>

#include "es_cdef.h"
#include "assertions.h"
#include "fm_mng.h"
#include "crc16-ccitt.h"
#include "telemetry_queue.h"
#include "telemetry_types.h"
#include "timer.h"
#include "trace.h"
#include "telemetry_cfg_user.h"
#include "taskmon.h"

#define BYTES_1K                          (1024LU)
#define DEFAULT_FILE_SZ_IF_CFG_INVALID_KB (1U)

static inline void telemetry_upd_file_idx(tlm_file_sink_rt_ctx_t *const p_tlm_filesink_rt_ctx, const uint16_t file_idx);
static uint64_t    telemetry_file_sink_getfreebytes(const tlm_file_sink_rt_ctx_t *const p_tlm_filesink_rt_ctx);
static void        telemetry_file_sink_check_create_tlm_dir(tlm_file_sink_rt_ctx_t *const p_tlm_filesink_rt_ctx);
static bool        telemetry_file_sink_shall_write(const tlm_file_sink_rt_ctx_t *const p_tlm_filesink_rt_ctx, uint32_t next_write_offset, uint16_t msg_size);
static void        telemetry_file_sink_prepare_next_slot(tlm_file_sink_rt_ctx_t *const p_tlm_filesink_rt_ctx);
static bool        telemetry_file_sink_is_fhdr_valid(tlm_file_hdr_t *p_hdr);
static inline bool telemetry_file_sink_is_file_complete(const tlm_file_hdr_t *const p_fhdr, const fm_handle_t f_handle);
static void        telemetry_file_sink_init_header(tlm_file_hdr_t *const p_hdr);
static inline void telemetry_file_sink_update_hdr_crc(tlm_file_hdr_t *const p_hdr);
static inline void telemetry_file_sink_write_hdr(fm_handle_t f_handle, tlm_file_hdr_t *const p_hdr);
static fm_result_t telemetry_cleanup_handler(const fm_fast_file_info_t *const gfi, void *const user_data);

INIT_CMP_LOGGER(true, TRACE_LVL_WARN)

static fm_result_t telemetry_cleanup_handler(const fm_fast_file_info_t *const gfi, void *const user_data)
{
    UNUSED(user_data);
    char fullname[FM_MAX_PATH];
    if ('\0' == gfi->p_path[0])
    {
        fm_delete(gfi->p_name);
    }
    else
    {
        (void)memset(fullname, 0U, sizeof(fullname));
        snprintf(fullname, sizeof(fullname), "%s/%s", gfi->p_path, gfi->p_name);
        fm_delete(fullname);
    }
    return FM_RES_OK;
}

void telemetry_file_sink_clean(tlm_file_sink_rt_ctx_t *const p_tlm_filesink_rt_ctx)
{
    fm_foreach_flat(p_tlm_filesink_rt_ctx->current_folder_name, p_tlm_filesink_rt_ctx->wildcard, &telemetry_cleanup_handler, NULL);
    telemetry_upd_file_idx(p_tlm_filesink_rt_ctx, 0);
}

/** @brief Update the current telemetry file slot index and persist the index to NVM.
 *
 *  @param[out] p_tlm_filesink_rt_ctx telemetry file sink runtime context
 *  @param[in] file_idx new file slot index to set
 */
static inline void telemetry_upd_file_idx(tlm_file_sink_rt_ctx_t *const p_tlm_filesink_rt_ctx, const uint16_t file_idx)
{
    CRIT_ASSERT(NULL != p_tlm_filesink_rt_ctx);

    p_tlm_filesink_rt_ctx->persistent_data.last_file_slot_idx = file_idx;
    telemetry_cfg_set_persistent_data(p_tlm_filesink_rt_ctx->sm_instance_id, &p_tlm_filesink_rt_ctx->persistent_data);
}

/** @brief Updates the header CRC and writes it to the provided file handle
 *  @param[in] f_handle file handle opened for writing
 *  @param[in/out] p_hdr telemetry header structure to write to the file after updating its CRC
 */
static inline void telemetry_file_sink_write_hdr(fm_handle_t f_handle, tlm_file_hdr_t *const p_hdr)
{
    CRIT_ASSERT(NULL != f_handle);
    CRIT_ASSERT(NULL != p_hdr);

    telemetry_file_sink_update_hdr_crc(p_hdr);

    uint32_t prev_pos = 0;
    fm_tell(f_handle, &prev_pos);
    // set file pointer to beginning of file in order to update the header
    fm_result_t fr = fm_seek(f_handle, 0U);

    if (FM_RES_OK != fr)
    {
        ES_TRACE_ERROR("file seek error [%ld]", fr);
        return;
    }

    fr = fm_write(f_handle, (const void *)p_hdr, (uint32_t)sizeof(tlm_file_hdr_t), NULL);

    if (FM_RES_OK != fr)
    {
        ES_TRACE_ERROR("tlm header write error [%ld]", fr);
        return;
    }

    // restore file pointer where it was...
    (void)fm_seek(f_handle, prev_pos);
}

/** @brief Calculates the CRC of a file telemetry header
 *  @param[in/out] p_hdr pointer to a file telemetry header structure which receives the updated CRC
 */
static inline void telemetry_file_sink_update_hdr_crc(tlm_file_hdr_t *const p_hdr)
{
    CRIT_ASSERT(NULL != p_hdr);
    p_hdr->crc = crc16_ccitt_table((const uint8_t *)p_hdr, sizeof(tlm_file_hdr_t) - sizeof(p_hdr->crc));
}

/** @brief Populates a file header structure with default values
 *  @param[in] p_hdr pointer to a telemetry file header structure to fill-in
 */
static void telemetry_file_sink_init_header(tlm_file_hdr_t *const p_hdr)
{
    CRIT_ASSERT(NULL != p_hdr);

    (void)memcpy(&p_hdr->signature, TLM_FILE_SIGN, sizeof(p_hdr->signature));
    // TODO: hardcoded for now but shall be matched to DataCache version (which is currently not generated yet!)
    p_hdr->version           = 0x00000200U;
    p_hdr->next_write_offset = sizeof(tlm_file_hdr_t);
    p_hdr->file_complete     = false;
    p_hdr->reserved          = 0;
}

/** @brief The function abstracts the decision whether file writing is complete or not.
 *
 *  @param[in] p_fhdr a pointer to a valid telemetry file header
 *  @param[in] f_handle opened handle to the file so that its size can be checked
 *
 *  @return true: file is complete according to the configuration; false: writing can continue in the same file at next_write_position
 */
static inline bool telemetry_file_sink_is_file_complete(const tlm_file_hdr_t *const p_fhdr, fm_handle_t f_handle)
{
    // currently unused
    (void)f_handle;

    return p_fhdr->file_complete;
}

/** @brief Returns the free space on the storage
 *
 *  @param[in] p_tlm_filesink_rt_ctx file sink runtime context
 *
 *  @return value in bytes
 */
static uint64_t telemetry_file_sink_getfreebytes(const tlm_file_sink_rt_ctx_t *const p_tlm_filesink_rt_ctx)
{
    uint32_t free_kilobytes = 0U;
    uint64_t free_bytes     = 0U;

    CRIT_ASSERT(NULL != p_tlm_filesink_rt_ctx);

    fm_get_free("/sd", &free_kilobytes);

    free_bytes = (uint64_t)free_kilobytes * (uint64_t)BYTES_1K;
    if (free_bytes < free_kilobytes) // overflow
    {
        free_bytes = UINT64_MAX;
    }

    return free_bytes;
}

/** @brief Checks if the telemetry instance directory exists and if not - creates it.
 *
 *  @param[in] p_tlm_filesink_rt_ctx telemetry file sink runtime context
 */
static void telemetry_file_sink_check_create_tlm_dir(tlm_file_sink_rt_ctx_t *const p_tlm_filesink_rt_ctx)
{
    CRIT_ASSERT(NULL != p_tlm_filesink_rt_ctx);

    if ('\0' == p_tlm_filesink_rt_ctx->current_folder_name[0])
    {
        (void)snprintf(p_tlm_filesink_rt_ctx->current_folder_name, TLM_DIR_MAX_NAME_SIZE, "/sd/tlm_%u", (uint16_t)p_tlm_filesink_rt_ctx->sm_instance_id);
    }

    fm_dir_obj_t dir_obj = { 0 };

    // check if directory exists...
    if (FM_RES_OK == fm_dir_open(&dir_obj, p_tlm_filesink_rt_ctx->current_folder_name, NULL))
    {
        fm_dir_close(&dir_obj);
    }
    else
    {
        // directory doesn't exist, so it must be created
        fm_result_t mkdir_res = fm_mkdir(p_tlm_filesink_rt_ctx->current_folder_name);

        if (FM_RES_OK == mkdir_res)
        {
            ES_TRACE_DEBUG("[%u] new folder '%s' created", p_tlm_filesink_rt_ctx->sm_instance_id, p_tlm_filesink_rt_ctx->current_folder_name);
        }
        else
        {
            ES_TRACE_ERROR("[%u] could not create tlm folder '%s'. failed with error '%s'.",
                           p_tlm_filesink_rt_ctx->sm_instance_id,
                           p_tlm_filesink_rt_ctx->current_folder_name,
                           fm_result_to_str(mkdir_res));
        }
    }
}

/** @brief Derives a telemetry file name based on index and folder.
 *
 *  @param[in] p_tlm_filesink_rt_ctx telemetry file sink runtime context
 *  @param[in] index telemetry file index
 *
 *  @note Relies on an external static memory buffer! The function also creates any required
 *  directories if they don't exist.
 */
void telemetry_file_sink_prepare_file_access(tlm_file_sink_rt_ctx_t *const p_tlm_filesink_rt_ctx)
{
    CRIT_ASSERT(NULL != p_tlm_filesink_rt_ctx);

    telemetry_file_sink_check_create_tlm_dir(p_tlm_filesink_rt_ctx);

    snprintf(p_tlm_filesink_rt_ctx->current_file_name,
             sizeof(p_tlm_filesink_rt_ctx->current_file_name),
             "%s/%u_%05u.%s",
             p_tlm_filesink_rt_ctx->current_folder_name,
             (uint16_t)p_tlm_filesink_rt_ctx->sm_instance_id,
             p_tlm_filesink_rt_ctx->persistent_data.last_file_slot_idx,
             TLM_FILE_SINK_EXT);
}

/** @brief The function makes a decision whether next write in the current file can occur
 *            based on the current configuration and state.
 *
 *  @param[in] p_tlm_filesink_rt_ctx telemetry file sink runtime context
 *  @param[in] next_write_offset byte location where next write will take place in the current file
 *  @param[in] msg_size Size in bytes of the next message to write to the file
 *
 *  @return true: write can be performed; false: skip write and prepare another file to continue
 */
static bool telemetry_file_sink_shall_write(const tlm_file_sink_rt_ctx_t *const p_tlm_filesink_rt_ctx, uint32_t next_write_offset, uint16_t msg_size)
{
    CRIT_ASSERT(NULL != p_tlm_filesink_rt_ctx);

    return (next_write_offset + msg_size) <= p_tlm_filesink_rt_ctx->max_file_size_bytes;
}

/** @brief The function is responsible to prepare the next file slot to write to depending on the current state and
 *         configuration.
 *
 *  @param[in] p_tlm_filesink_rt_ctx telemetry file sink runtime context
 */
static void telemetry_file_sink_prepare_next_slot(tlm_file_sink_rt_ctx_t *const p_tlm_filesink_rt_ctx)
{
    CRIT_ASSERT(NULL != p_tlm_filesink_rt_ctx);

    telemetry_upd_file_idx(p_tlm_filesink_rt_ctx,
            (p_tlm_filesink_rt_ctx->persistent_data.last_file_slot_idx + 1) % p_tlm_filesink_rt_ctx->cfg.params.u16Max_log_files_cnt);

    telemetry_file_sink_prepare_file_access(p_tlm_filesink_rt_ctx);

    // reinitilize the new slot file header
    fm_file_obj_t  tlm_file_handle;
    tlm_file_hdr_t fhdr;
    uint32_t       bytes_read    = 0;
    uint32_t       bytes_written = 0;

    fm_result_t res = fm_open(&tlm_file_handle,
                              p_tlm_filesink_rt_ctx->current_file_name,
                              (uint32_t)(FM_MODE_OPEN_ALWAYS | FM_MODE_READ | FM_MODE_WRITE));

    if (FM_RES_OK == res)
    {
        res = fm_read(&tlm_file_handle, &fhdr, sizeof(fhdr), &bytes_read);

        if ((FM_RES_OK == res) && (sizeof(fhdr) == bytes_read))
        {
            telemetry_file_sink_init_header(&fhdr);
            telemetry_file_sink_update_hdr_crc(&fhdr);

            // set file pointer to beginning of file in order to update the header
            (void)fm_seek(&tlm_file_handle, 0U);
            res = fm_write(&tlm_file_handle, (const void *)&fhdr, sizeof(fhdr), &bytes_written);

            if ((FM_RES_OK == res) && (sizeof(fhdr) == bytes_written))
            {
                ES_TRACE_DEBUG("[%u:%u] next slot header prepared for use", p_tlm_filesink_rt_ctx->sm_instance_id, p_tlm_filesink_rt_ctx->persistent_data.last_file_slot_idx);
            }
            else
            {
                ES_TRACE_WARN("[%u:%u] error when trying to prepare new slot", p_tlm_filesink_rt_ctx->sm_instance_id, p_tlm_filesink_rt_ctx->persistent_data.last_file_slot_idx);
            }
        }

        (void)fm_close(&tlm_file_handle);
    }
    else
    {
        ES_TRACE_WARN("[%u:%u] unexpected result [%d] when opening file", p_tlm_filesink_rt_ctx->sm_instance_id, p_tlm_filesink_rt_ctx->persistent_data.last_file_slot_idx, res);
    }
}

static bool telemetry_file_sink_is_fhdr_valid(tlm_file_hdr_t *p_hdr)
{
    bool is_valid = false;

    CRIT_ASSERT(NULL != p_hdr);

    if (0 == memcmp(p_hdr->signature, TLM_FILE_SIGN, sizeof(p_hdr->signature)))
    {
        uint16_t fhdr_crc = p_hdr->crc;
        telemetry_file_sink_update_hdr_crc(p_hdr);

        is_valid = (fhdr_crc == p_hdr->crc);
    }

    return is_valid;
}

static void verify_tlm_header(fm_file_obj_t *p_tlm_file_handle, tlm_file_hdr_t *p_hdr)
{
    uint32_t bytes_read;

    fm_result_t res = fm_read(p_tlm_file_handle, p_hdr, sizeof(tlm_file_hdr_t), &bytes_read);

    if ((FM_RES_OK == res) && (sizeof(tlm_file_hdr_t) == bytes_read) && (true == telemetry_file_sink_is_fhdr_valid(p_hdr)))
    {
        p_hdr->next_write_offset = (true == telemetry_file_sink_is_file_complete(p_hdr, p_tlm_file_handle)) ? (sizeof(tlm_file_hdr_t)) : (p_hdr->next_write_offset);

        // restore file position pointer based on information from the header...
        fm_seek(p_tlm_file_handle, p_hdr->next_write_offset);
    }
    else
    {
        telemetry_file_sink_init_header(p_hdr);

        telemetry_file_sink_write_hdr(p_tlm_file_handle, p_hdr);

        // skip header and set file pointer position for first message
        (void)fm_seek(p_tlm_file_handle, (uint32_t)sizeof(tlm_file_hdr_t));
    }
}

// USER_CODE_END::@main@

// Entry/Exit functions


// GEN_OBJ_START::telemetry_file_sink_sm_on_entry_Init
void telemetry_file_sink_sm_on_entry_Init(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::onEntry_Init
    tlm_file_sink_rt_ctx_t *const p_tlm_filesink_rt_ctx = &telemetry_cfg_get_ctx_u16(instance_id)->tlm_file_sink_rt;

    p_tlm_filesink_rt_ctx->persistent_data.last_file_slot_idx = 0U;
    (void)memset(p_tlm_filesink_rt_ctx->tlm_msg_buffer, 0U, sizeof(p_tlm_filesink_rt_ctx->tlm_msg_buffer));
    (void)memset(&p_tlm_filesink_rt_ctx->prev_cfg, 0U, sizeof(p_tlm_filesink_rt_ctx->prev_cfg));

    telemetry_file_sink_sm_action_reload_config(instance_id, pSMRoot, pEvent);
    // USER_CODE_END::onEntry_Init
}
// GEN_OBJ_END::telemetry_file_sink_sm_on_entry_Init





// GEN_OBJ_START::telemetry_file_sink_sm_on_entry_Wait_Cleanup
void telemetry_file_sink_sm_on_entry_Wait_Cleanup(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::onEntry_Wait_Cleanup
    ES_TRACE_DEBUG("[%u] cleanup started...", instance_id);
    // USER_CODE_END::onEntry_Wait_Cleanup
}
// GEN_OBJ_END::telemetry_file_sink_sm_on_entry_Wait_Cleanup

// GEN_OBJ_START::telemetry_file_sink_sm_on_exit_Wait_Cleanup
void telemetry_file_sink_sm_on_exit_Wait_Cleanup(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::onExit_Wait_Cleanup
    ES_TRACE_DEBUG("[%u] cleanup finished...", instance_id);
    // USER_CODE_END::onExit_Wait_Cleanup
}
// GEN_OBJ_END::telemetry_file_sink_sm_on_exit_Wait_Cleanup



// Guard condition functions
// GEN_OBJ_START::telemetry_file_sink_sm_guard_is_storage_available
bool telemetry_file_sink_sm_guard_is_storage_available(const uint16_t instance_id, const sState_t* const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::guard_is_storage_available
    fm_storage_status_t status;
    fm_result_t res = fm_storage_status(FM_VOL_SD_PATH, &status);

    return ((FM_RES_OK == res) &&
            ((STORAGE_STATUS_READY == status) ||
             (STORAGE_STATUS_BUSY == status)));
    // USER_CODE_END::guard_is_storage_available
}
// GEN_OBJ_END::telemetry_file_sink_sm_guard_is_storage_available

// GEN_OBJ_START::telemetry_file_sink_sm_guard_is_storage_blocked
bool telemetry_file_sink_sm_guard_is_storage_blocked(const uint16_t instance_id, const sState_t* const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::guard_is_storage_blocked
    return !telemetry_file_sink_sm_guard_is_storage_available(instance_id, pSMRoot, pEvent);
    // USER_CODE_END::guard_is_storage_blocked
}
// GEN_OBJ_END::telemetry_file_sink_sm_guard_is_storage_blocked

// GEN_OBJ_START::telemetry_file_sink_sm_guard_is_cleanup_finished
bool telemetry_file_sink_sm_guard_is_cleanup_finished(const uint16_t instance_id, const sState_t* const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::guard_is_cleanup_finished
    return (false == telemetry_cfg_get_ctx_u16(instance_id)->tlm_file_sink_rt.main_task_sync_op_flags[TLM_FILE_SINK_OP_CLEAN]);
    // USER_CODE_END::guard_is_cleanup_finished
}
// GEN_OBJ_END::telemetry_file_sink_sm_guard_is_cleanup_finished


// Action handlers
// GEN_OBJ_START::telemetry_file_sink_sm_action_reload_config
void telemetry_file_sink_sm_action_reload_config(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::action_reload_config
    tlm_file_sink_rt_ctx_t *const p_tlm_filesink_rt_ctx = &telemetry_cfg_get_ctx_u16(instance_id)->tlm_file_sink_rt;

    telemetry_cfg_get_file_config((TELEMETRY_TelemetryInstance_t)instance_id, &p_tlm_filesink_rt_ctx->cfg);
    bool cfg_changed = (p_tlm_filesink_rt_ctx->prev_cfg.cfg_type != p_tlm_filesink_rt_ctx->cfg.cfg_type) ||
                       (p_tlm_filesink_rt_ctx->prev_cfg.params.u16Max_log_files_cnt != p_tlm_filesink_rt_ctx->cfg.params.u16Max_log_files_cnt) ||
                       (p_tlm_filesink_rt_ctx->prev_cfg.params.u32Size_limit_kb != p_tlm_filesink_rt_ctx->cfg.params.u32Size_limit_kb);

    if (true == cfg_changed)
    {
        p_tlm_filesink_rt_ctx->prev_cfg = p_tlm_filesink_rt_ctx->cfg;

        ES_TRACE_INFO("[%u] telemetry file configuration change detected", instance_id);

        BREAK_ASSERT(TELEMETRY_TLM_FILE_LOGGING_TYPE_SIZE_LIMIT == p_tlm_filesink_rt_ctx->cfg.cfg_type);
        BREAK_ASSERT(0U != p_tlm_filesink_rt_ctx->cfg.params.u16Max_log_files_cnt);
        BREAK_ASSERT(0U != p_tlm_filesink_rt_ctx->cfg.params.u32Size_limit_kb);

        if ((0U != p_tlm_filesink_rt_ctx->cfg.params.u16Max_log_files_cnt) &&
            (0U != p_tlm_filesink_rt_ctx->cfg.params.u32Size_limit_kb))
        {
            p_tlm_filesink_rt_ctx->max_file_size_bytes =
                (p_tlm_filesink_rt_ctx->cfg.params.u32Size_limit_kb * 1024U) / p_tlm_filesink_rt_ctx->cfg.params.u16Max_log_files_cnt;
        }
        else
        {
            p_tlm_filesink_rt_ctx->max_file_size_bytes = DEFAULT_FILE_SZ_IF_CFG_INVALID_KB;
        }
    }

    // restore operational persistent data from NVM
    telemetry_cfg_get_persistent_data(p_tlm_filesink_rt_ctx->sm_instance_id, &p_tlm_filesink_rt_ctx->persistent_data);
    // USER_CODE_END::action_reload_config
}
// GEN_OBJ_END::telemetry_file_sink_sm_action_reload_config

// GEN_OBJ_START::telemetry_file_sink_sm_action_prepare_file_telemetry
void telemetry_file_sink_sm_action_prepare_file_telemetry(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::action_prepare_file_telemetry
    tlm_file_sink_rt_ctx_t *const p_tlm_filesink_rt_ctx = &telemetry_cfg_get_ctx_u16(instance_id)->tlm_file_sink_rt;

    // reload configuration explicitly, just in case we couldn't load it in one of the previous states
    telemetry_file_sink_sm_action_reload_config(instance_id, pSMRoot, pEvent);

    CRIT_ASSERT(NULL != p_tlm_filesink_rt_ctx);
    CRIT_ASSERT(p_tlm_filesink_rt_ctx->max_file_size_bytes >= TLM_MSG_SIZE_BYTES_LEAST);

    // if last stored index is out of bounds, reset it
    if (p_tlm_filesink_rt_ctx->persistent_data.last_file_slot_idx >= p_tlm_filesink_rt_ctx->cfg.params.u16Max_log_files_cnt)
    {
        ES_TRACE_WARN("[%u:%u] pd idx force reset", p_tlm_filesink_rt_ctx->sm_instance_id, p_tlm_filesink_rt_ctx->persistent_data.last_file_slot_idx);

        telemetry_upd_file_idx(p_tlm_filesink_rt_ctx, 0);
    }

    telemetry_file_sink_prepare_file_access(p_tlm_filesink_rt_ctx);
    ES_TRACE_DEBUG("[%u:%u] preparing '%s' for update", p_tlm_filesink_rt_ctx->sm_instance_id, p_tlm_filesink_rt_ctx->persistent_data.last_file_slot_idx, p_tlm_filesink_rt_ctx->current_file_name);
    // USER_CODE_END::action_prepare_file_telemetry
}
// GEN_OBJ_END::telemetry_file_sink_sm_action_prepare_file_telemetry

// GEN_OBJ_START::telemetry_file_sink_sm_action_store_telemetry
void telemetry_file_sink_sm_action_store_telemetry(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::action_store_telemetry
    fm_result_t                   res;
    fm_file_obj_t                 tlm_file_handle;
    tlm_file_hdr_t                fhdr;
    tlm_file_sink_rt_ctx_t *const p_tlm_filesink_rt_ctx = &telemetry_cfg_get_ctx_u16(instance_id)->tlm_file_sink_rt;
    tlm_queue_rt_t *const         p_tlm_queue_rt        = &telemetry_cfg_get_ctx_u16(instance_id)->tlm_queue;

    telemetry_queue_update_stats(p_tlm_queue_rt, TLM_STATS_ID_ACTIVE_SLOT, p_tlm_filesink_rt_ctx->persistent_data.last_file_slot_idx);

    (void)memset(&fhdr, 0U, sizeof(fhdr));
    res = fm_open(&tlm_file_handle,
                  p_tlm_filesink_rt_ctx->current_file_name,
                  (uint32_t)(FM_MODE_OPEN_ALWAYS | FM_MODE_READ | FM_MODE_WRITE));

    if (FM_RES_OK == res)
    {
        verify_tlm_header(&tlm_file_handle, &fhdr);

        uint16_t next_msg_size   = telemetry_queue_peek(p_tlm_queue_rt);
        uint64_t free_bytes      = telemetry_file_sink_getfreebytes(p_tlm_filesink_rt_ctx);
        uint32_t batch_msg_count = 0U;

        if (free_bytes > (uint64_t)next_msg_size)
        {
            bool continue_op = true;

            while ((next_msg_size > 0U) && (true == continue_op))
            {
                uint32_t bytes_written = 0U;

                if (true == telemetry_file_sink_shall_write(p_tlm_filesink_rt_ctx, fhdr.next_write_offset, next_msg_size))
                {
                    uint16_t bytes_read_from_queue = telemetry_queue_pop(p_tlm_queue_rt, p_tlm_filesink_rt_ctx->tlm_msg_buffer,
                                                                         sizeof(p_tlm_filesink_rt_ctx->tlm_msg_buffer));

                    CRIT_ASSERT(bytes_read_from_queue == next_msg_size);

                    res = fm_write(&tlm_file_handle,
                                   p_tlm_filesink_rt_ctx->tlm_msg_buffer,
                                   bytes_read_from_queue,
                                   &bytes_written);

                    uint32_t file_size = 0;
                    (void)fm_tell(&tlm_file_handle, &file_size);
                    fhdr.next_write_offset = file_size;

                    if ((FM_RES_OK != res) || (bytes_written != bytes_read_from_queue))
                    {
                        ES_TRACE_ERROR("[%u:%u] tlm write error [%d]", instance_id, p_tlm_filesink_rt_ctx->persistent_data.last_file_slot_idx, res);

                        // exit the loop (not using break due to SonarQube complaints)
                        continue_op = false;
                    }
                    else
                    {
                        fhdr.file_complete = false;

                        telemetry_file_sink_write_hdr(&tlm_file_handle, &fhdr);

                        next_msg_size = telemetry_queue_peek(p_tlm_queue_rt);

                        batch_msg_count++;

                        ES_TRACE_DEBUG("[%u:%u] tlm wrt @ offs %lu", instance_id, p_tlm_filesink_rt_ctx->persistent_data.last_file_slot_idx, fhdr.next_write_offset);
                    }
                }
                else
                {
                    ES_TRACE_DEBUG("[%u:%u] no space in current file. switching to next slot...", instance_id, p_tlm_filesink_rt_ctx->persistent_data.last_file_slot_idx);

                    fhdr.reserved      = 0U;
                    fhdr.file_complete = true;
                    // next writes in this file will start from
                    fhdr.next_write_offset = sizeof(tlm_file_hdr_t);

                    // Note: Order is important here in case of intermediate reset after this point! The next file slot must be
                    // prepared first before marking the current one as complete, otherwise we may end up with the current file complete and
                    // no partial slot to continue from next time after reset.
                    telemetry_file_sink_prepare_next_slot(p_tlm_filesink_rt_ctx);

                    // call this after telemetry_file_sink_prepare_next_slot() to ensure correct recovery in case of CPU reset between these
                    // two calls
                    telemetry_file_sink_write_hdr(&tlm_file_handle, &fhdr);

                    // exit the loop (not using break due to SonarQube complaints)
                    continue_op = false;
                }
            }

            // report statistics on last run...
            telemetry_queue_update_stats(p_tlm_queue_rt, TLM_STATS_ID_BATCH_COUNT, batch_msg_count);
        }
        else
        {
            ES_TRACE_WARN("no space left on storage. %" PRIu64 " free bytes remaining.", free_bytes);
        }

        (void)fm_close(&tlm_file_handle);
    }
    else
    {
        ES_TRACE_WARN("[%u:%u] unexpected result [%d] when opening file. skipping this slot.", instance_id, p_tlm_filesink_rt_ctx->persistent_data.last_file_slot_idx, res);
        telemetry_file_sink_prepare_next_slot(p_tlm_filesink_rt_ctx);
    }

    // USER_CODE_END::action_store_telemetry
}
// GEN_OBJ_END::telemetry_file_sink_sm_action_store_telemetry

// GEN_OBJ_START::telemetry_file_sink_sm_action_clean_and_reload_cfg
void telemetry_file_sink_sm_action_clean_and_reload_cfg(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::action_clean_and_reload_cfg
    tlm_runtime_context_t *p_tlm_rt_ctx = telemetry_cfg_get_ctx_u16(instance_id);

    telemetry_file_sink_sm_action_reload_config(instance_id, pSMRoot, pEvent);

    telemetry_file_sink_clean(&p_tlm_rt_ctx->tlm_file_sink_rt);
    // USER_CODE_END::action_clean_and_reload_cfg
}
// GEN_OBJ_END::telemetry_file_sink_sm_action_clean_and_reload_cfg
