/*
 * Copyright (c) EnduroSat AD. All rights reserved.
 *
 * Contents and presentations are protected world-wide.
 * Any kind of using, copying etc. is prohibited without prior permission.
 * -----------------------------------------------------------------------------
 * Generated by hsmgen 2.0.1
 * -----------------------------------------------------------------------------
 */

#include <stddef.h>
#include "libhsm.h"
#include "telemetry_sm_config_user.h"
#include "telemetry_sm_user.h"


static const sTransition_t tran_Not_Init_ev_init_Init;
static const sTransition_t tran_Init_ev_start_Started;
static const sTransition_t tran_Init_ev_periodic_self;
static const sTransition_t tran_Started_ev_stop_Stopped;
static const sTransition_t tran_Started_ev_periodic_Stopped;
static const sTransition_t tran_Started_ev_periodic_self;
static const sTransition_t tran_Stopped_ev_start_Started;
static const sTransition_t tran_Stopped_ev_periodic_Started;
static const sTransition_t tran_Stopped_ev_periodic_self;


static const sTransition_t* trans_Not_Init[2] =
{
    &tran_Not_Init_ev_init_Init,
    NULL
};

static const sTransition_t* trans_Init[3] =
{
    &tran_Init_ev_start_Started,
    &tran_Init_ev_periodic_self,
    NULL
};

static const sTransition_t* trans_Started[4] =
{
    &tran_Started_ev_stop_Stopped,
    &tran_Started_ev_periodic_Stopped,
    &tran_Started_ev_periodic_self,
    NULL
};

static const sTransition_t* trans_Stopped[4] =
{
    &tran_Stopped_ev_start_Started,
    &tran_Stopped_ev_periodic_Started,
    &tran_Stopped_ev_periodic_self,
    NULL
};


// telemetry_sm states forward declarations
static const sState_t state_Not_Init;
static const sState_t state_Init;
static const sState_t state_Started;
static const sState_t state_Stopped;

// history/active states instance lists definitions

static sState_t *p_telemetry_sm_inst_history[TELEMETRY_SM_INSTANCE_CNT] = {
    HSM_UPCAST_STATE(&state_Not_Init),HSM_UPCAST_STATE(&state_Not_Init),
};

static sState_t *p_telemetry_sm_inst_active_states[TELEMETRY_SM_INSTANCE_CNT] = {
    HSM_UPCAST_STATE(&state_telemetry_sm),HSM_UPCAST_STATE(&state_telemetry_sm),
};

// telemetry_sm root state definition
sCompositeState_t state_telemetry_sm =
{
    .state =
    {
        .state_id = TELEMETRY_SM_ROOT,
        .pName = "state_telemetry_sm",
        .onEntryFunc = NULL,
        .onExitFunc = NULL,
        .pTransitionList = NULL,
        .eType = eHSM_StateType_Composite,
        .pParent = NULL
    },
    .pInitialState = HSM_UPCAST_STATE(&state_Not_Init),
    .instanceCnt = 2,
    .ppHistoryState = p_telemetry_sm_inst_history,
    .ppActiveState = p_telemetry_sm_inst_active_states
};

static const sState_t state_Not_Init =
{
    .state_id = TELEMETRY_SM_STATE_NOT_INIT,
    .pName = "state_Not_Init",
    .onEntryFunc = NULL,
    .onExitFunc = NULL,
    .pTransitionList = trans_Not_Init,
    .eType = eHSM_StateType_Simple,
    .pParent = HSM_UPCAST_STATE(&state_telemetry_sm)
};


static const sState_t state_Init =
{
    .state_id = TELEMETRY_SM_STATE_INIT,
    .pName = "state_Init",
    .onEntryFunc = &telemetry_sm_on_entry_Init,
    .onExitFunc = NULL,
    .pTransitionList = trans_Init,
    .eType = eHSM_StateType_Simple,
    .pParent = HSM_UPCAST_STATE(&state_telemetry_sm)
};


static const sState_t state_Started =
{
    .state_id = TELEMETRY_SM_STATE_STARTED,
    .pName = "state_Started",
    .onEntryFunc = &telemetry_sm_on_entry_Started,
    .onExitFunc = &telemetry_sm_on_exit_Started,
    .pTransitionList = trans_Started,
    .eType = eHSM_StateType_Simple,
    .pParent = HSM_UPCAST_STATE(&state_telemetry_sm)
};


static const sState_t state_Stopped =
{
    .state_id = TELEMETRY_SM_STATE_STOPPED,
    .pName = "state_Stopped",
    .onEntryFunc = &telemetry_sm_on_entry_Stopped,
    .onExitFunc = NULL,
    .pTransitionList = trans_Stopped,
    .eType = eHSM_StateType_Simple,
    .pParent = HSM_UPCAST_STATE(&state_telemetry_sm)
};

static const sTransition_t tran_Not_Init_ev_init_Init =
{
    .eventId = ev_telemetry_sm_init,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state_Init),
    .onTransitionActionFunc = NULL
};

static const sTransition_t tran_Init_ev_start_Started =
{
    .eventId = ev_telemetry_sm_start,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state_Started),
    .onTransitionActionFunc = NULL
};

static const sTransition_t tran_Init_ev_periodic_self =
{
    .eventId = eHSM_StdEvent_Periodic,
    .guardFunc = NULL,
    .pTargetState = NULL,
    .onTransitionActionFunc = &telemetry_sm_action_reload_config,
};

static const sTransition_t tran_Started_ev_stop_Stopped =
{
    .eventId = ev_telemetry_sm_stop,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state_Stopped),
    .onTransitionActionFunc = &telemetry_sm_action_stop_file_telemetry,
};

static const sTransition_t tran_Started_ev_periodic_Stopped =
{
    .eventId = eHSM_StdEvent_Periodic,
    .guardFunc = &telemetry_sm_guard_is_hold_time_elapsed,
    .pTargetState = HSM_UPCAST_STATE(&state_Stopped),
    .onTransitionActionFunc = &telemetry_sm_action_stop_file_telemetry,
};

static const sTransition_t tran_Started_ev_periodic_self =
{
    .eventId = eHSM_StdEvent_Periodic,
    .guardFunc = NULL,
    .pTargetState = NULL,
    .onTransitionActionFunc = &telemetry_sm_action_collect_telemetry,
};

static const sTransition_t tran_Stopped_ev_start_Started =
{
    .eventId = ev_telemetry_sm_start,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state_Started),
    .onTransitionActionFunc = &telemetry_sm_action_start_file_telemetry,
};

static const sTransition_t tran_Stopped_ev_periodic_Started =
{
    .eventId = eHSM_StdEvent_Periodic,
    .guardFunc = &telemetry_sm_guard_is_hold_time_elapsed,
    .pTargetState = HSM_UPCAST_STATE(&state_Started),
    .onTransitionActionFunc = &telemetry_sm_action_start_file_telemetry,
};

static const sTransition_t tran_Stopped_ev_periodic_self =
{
    .eventId = eHSM_StdEvent_Periodic,
    .guardFunc = NULL,
    .pTargetState = NULL,
    .onTransitionActionFunc = &telemetry_sm_action_reload_config,
};
