/*
 * Copyright (c) EnduroSat AD. All rights reserved.
 *
 * Contents and presentations are protected world-wide.
 * Any kind of using, copying etc. is prohibited without prior permission.
 * -----------------------------------------------------------------------------
 * Generated by hsmgen 2.0.1
 * -----------------------------------------------------------------------------
 */

#ifndef TELEMETRY_SM_USER_H
#define TELEMETRY_SM_USER_H

#ifdef __cplusplus
extern "C" {
#endif

#include "libhsm.h"

// State identifiers
enum telemetry_sm_states
{
    TELEMETRY_SM_ROOT,
    TELEMETRY_SM_STATE_NOT_INIT,
    TELEMETRY_SM_STATE_INIT,
    TELEMETRY_SM_STATE_STARTED,
    TELEMETRY_SM_STATE_STOPPED,
    TELEMETRY_SM_MAX
};

// User state machine events
enum telemetry_sm_events
{
    ev_telemetry_sm_user_start = eHSM_StdEvent_UserEvStart,
    ev_telemetry_sm_init,
    ev_telemetry_sm_start,
    ev_telemetry_sm_stop,
    ev_telemetry_sm_MAX
};

// State machine root object
extern sCompositeState_t state_telemetry_sm;

// Use this macro to access the SM instance instead of a direct reference to
// state_telemetry_sm variable
#define telemetry_sm_instance  HSM_UPCAST_STATE(&state_telemetry_sm)

// Number of SM instances configured in the SM model
#define TELEMETRY_SM_INSTANCE_CNT    (2U)

#ifdef __cplusplus
};
#endif

#endif  // #ifndef TELEMETRY_SM_USER_H