/*
 * Copyright (c) EnduroSat AD. All rights reserved.
 *
 * Contents and presentations are protected world-wide.
 * Any kind of using, copying etc. is prohibited without prior permission.
 * -----------------------------------------------------------------------------
 * Generated by hsmgen 2.0.1
 * -----------------------------------------------------------------------------
 */

#include "libhsm.h"
#include "telemetry_sm_config_user.h"

// USER_CODE_START::@main@

// Keep this documentation here to preserve it during code generation!
/**
 * @addtogroup service_tlm
 * @{
 *
 * @file telemetry_sm_config_user.c
 *
 * @brief This file contains the Telemetry SM hook functions (e.g. on_entry/on_exit/actions and guards).
 *
 * The functions here are directly called by the libhsm engine based on the generated code from `telemetry_sm.yaml`.
 * @warning Pay attention to edit this file only between the `USER_CODE_START` and `USER_CODE_END` comment blocks in order to
 * ensure that the auto-merge function of the libhsm generator will preserve your changes!
 *
 * @}
 */

// Any code placed between these two tags will be preserved during code generation!
#include <string.h>
#include <limits.h>
#include "telemetry_types.h"
#include "assertions.h"
#include "conops.h"
#include "crc16-ccitt.h"
#include "datetime.h"
#include "cobs.h"
#include "telemetry_queue.h"
#include "datetime.h"
#include "trace.h"
#include "telemetry_cfg_user.h"
#include "telemetry_file_sink.h"

INIT_CMP_LOGGER(true, TRACE_LVL_WARN)

/** @brief Prepare a telemetry frame with the specified data cache attribute
 *
 *  @param[out] p_data_buf buffer where to store the telemetry frame data
 *  @param[in] data_buf_size size of the output buffer in bytes
 *
 *  @return actual length (in bytes) of the prepared telemetry frame
 */
static uint32_t prepare_tlm_frame(const uint16_t data_id, uint8_t *const p_data_buf, const uint32_t data_buf_size);

/** @brief Try to push the provided telemetry preset entry to the queue for dispatch
 *
 *  The function reads the corresponding entry data from DataCache, COBS-encodes it and finally tries to
 *  push it to the telemetry queue for dispatch to storage. If something fails, it just traces a warning and exits.
 *
 *  @param[in/out] p_tlm_rt_ctx pointer to the currently active telemetry context
 *  @param[in] p_tlm_entry pointer to the preset telemetry entry read from NVM
 *
 *  @retval true: the entry was pushed to the dispatch queue successfully
 *  @retval false: the entry was not pushed to the dispatch queue
 */
static bool try_push_tlm_entry_to_queue(tlm_runtime_context_t *const p_tlm_rt_ctx, const TELEMETRY_tlm_preset_cfg_t *const p_tlm_entry);

/** @brief The operation prepares the hold timer to wait for the specified user time. The timer interval is part of
 *  the p_tlm_rt_ctx structure.
 *
 *  @param[in/out] p_tlm_rt_ctx pointer to the currently active telemetry context
 */
static void arm_hold_timer(tlm_runtime_context_t *const p_tlm_rt_ctx);

static uint32_t prepare_tlm_frame(const uint16_t data_id, uint8_t *const p_data_buf, const uint32_t data_buf_size)
{
    uint32_t frame_len = 0U;

    CRIT_ASSERT(NULL != p_data_buf);
    CRIT_ASSERT(data_buf_size > 0U);

    if (INVALID_TLM_SLOT_ASSIGNMENT != data_id)
    {
        dc_did_id dc_item_idx = dc_get_index_by_data_id(data_id);

        if (DC_DID_MAX != dc_item_idx)
        {
            uint32_t dc_data_size    = dc_get_data_size(dc_item_idx);
            uint32_t tlm_msg_buff_sz = sizeof(((tlm_runtime_context_t *)NULL)->tlm_msg_buffer);

            CRIT_ASSERT(dc_data_size <= TLM_BUF_SIZE);

            if (dc_data_size <= TLM_BUF_SIZE)
            {
                tlm_frame_hdr_t *p_frame_hdr  = (tlm_frame_hdr_t *)p_data_buf;
                uint8_t         *p_frame_data = &p_data_buf[sizeof(tlm_frame_hdr_t)];

                frame_len = sizeof(tlm_frame_hdr_t) + dc_data_size + sizeof(tlm_msg_footer_t);

                CRIT_ASSERT(tlm_msg_buff_sz >= frame_len);

                unix_time_precise_t data_ts = datetime_to_unix_precise_now();

                p_frame_hdr->timestamp    = data_ts.unix_ts;
                // set the timestamp in units of 0.1 ms
                p_frame_hdr->timestamp_precise = (uint16_t) ((((uint32_t) data_ts.ms * 1000) + data_ts.us) / 100);
                p_frame_hdr->rolling_cntr++;
                conops_get_hsm_active_state(&p_frame_hdr->obc_opmode);

                dc_data_status_t dc_status =
                    dc_get_raw_data(dc_item_idx,
                                    p_frame_data,
                                    tlm_msg_buff_sz,
                                    0U,
                                    dc_data_size);

                p_frame_hdr->msg_hdr.msg_type        = data_id;
                p_frame_hdr->msg_hdr.tlm_data_status = (uint8_t)dc_status;
                CRIT_ASSERT(dc_data_size <= UINT_MAX);
                p_frame_hdr->msg_hdr.data_len = (uint16_t)dc_data_size;

                p_frame_data += dc_data_size;

                ((tlm_msg_footer_t *)p_frame_data)->crc =
                    crc16_ccitt_table((const uint8_t *)p_frame_hdr, frame_len - sizeof(tlm_msg_footer_t));
            }
        }
    }

    return frame_len;
}

static bool try_push_tlm_entry_to_queue(tlm_runtime_context_t *const p_tlm_rt_ctx, const TELEMETRY_tlm_preset_cfg_t *const p_tlm_entry)
{
    CRIT_ASSERT(NULL != p_tlm_rt_ctx);
    CRIT_ASSERT(NULL != p_tlm_entry);

    bool     is_pushed_to_queue = false;
    uint32_t frame_len          = prepare_tlm_frame(p_tlm_entry->u16Data_id, p_tlm_rt_ctx->tlm_msg_buffer, sizeof(p_tlm_rt_ctx->tlm_msg_buffer));

    if (frame_len > 0U)
    {
        uint32_t cobs_frame_len = cobs_encode(p_tlm_rt_ctx->tlm_msg_buffer,
                                              frame_len,
                                              p_tlm_rt_ctx->tlm_msg_encode_buffer);

        // the following check ensures there is room for the frame delimiter byte
        BREAK_ASSERT((cobs_frame_len + 1U) <= sizeof(p_tlm_rt_ctx->tlm_msg_encode_buffer));

        if ((cobs_frame_len + 1U) <= sizeof(p_tlm_rt_ctx->tlm_msg_encode_buffer))
        {
            p_tlm_rt_ctx->tlm_msg_encode_buffer[cobs_frame_len++] = TLM_FRM_DELIMITER;

            is_pushed_to_queue = telemetry_queue_push(&p_tlm_rt_ctx->tlm_queue, p_tlm_rt_ctx->tlm_msg_encode_buffer, (uint16_t)cobs_frame_len);

            if (false == is_pushed_to_queue)
            {
                // Note: Even if res is false, which means there was no space in the queue, we will
                //       still continue with other slots because there may be enough space in the queue for them.
                ES_TRACE_WARN("[%u] skipping DC frame '%u' due to lack of space in queue", (uint8_t)p_tlm_rt_ctx->sm_instance_id, p_tlm_entry->u16Data_id);
            }
        }
        else
        {
            ES_TRACE_WARN("[%u] skipping DC frame '%u' because it is larger than the configured queue size of %lu byte(s)", (uint8_t)p_tlm_rt_ctx->sm_instance_id, p_tlm_entry->u16Data_id, (uint32_t)sizeof(p_tlm_rt_ctx->tlm_msg_encode_buffer));
        }
    }

    return is_pushed_to_queue;
}

static void arm_hold_timer(tlm_runtime_context_t *const p_tlm_rt_ctx)
{
    CRIT_ASSERT(NULL != p_tlm_rt_ctx);

    if (0 != p_tlm_rt_ctx->hold_period_s)
    {
        timer_start(&p_tlm_rt_ctx->hold_timer);
    }
    else
    {
        timer_stop(&p_tlm_rt_ctx->hold_timer);
    }
}
// USER_CODE_END::@main@

// Entry/Exit functions


// GEN_OBJ_START::telemetry_sm_on_entry_Init
void telemetry_sm_on_entry_Init(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::onEntry_Init
    tlm_runtime_context_t *p_tlm_rt_ctx = telemetry_cfg_get_ctx_u16(instance_id);

    p_tlm_rt_ctx->next_start_slot_idx = 0;

    telemetry_queue_init(&(p_tlm_rt_ctx->tlm_queue));

    timer_start(&p_tlm_rt_ctx->reload_config_timer);

    // USER_CODE_END::onEntry_Init
}
// GEN_OBJ_END::telemetry_sm_on_entry_Init


// GEN_OBJ_START::telemetry_sm_on_entry_Started
void telemetry_sm_on_entry_Started(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::onEntry_Started
    tlm_runtime_context_t *p_tlm_rt_ctx = telemetry_cfg_get_ctx_u16(instance_id);

    // reset acquisition counters...
    (void)memset(p_tlm_rt_ctx->tlm_entry_timer, 0U, sizeof(p_tlm_rt_ctx->tlm_entry_timer));

    arm_hold_timer(p_tlm_rt_ctx);
    // USER_CODE_END::onEntry_Started
}
// GEN_OBJ_END::telemetry_sm_on_entry_Started

// GEN_OBJ_START::telemetry_sm_on_exit_Started
void telemetry_sm_on_exit_Started(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::onExit_Started
    timer_start(&telemetry_cfg_get_ctx_u16(instance_id)->reload_config_timer);
    // USER_CODE_END::onExit_Started
}
// GEN_OBJ_END::telemetry_sm_on_exit_Started


// GEN_OBJ_START::telemetry_sm_on_entry_Stopped
void telemetry_sm_on_entry_Stopped(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::onEntry_Stopped
    arm_hold_timer(telemetry_cfg_get_ctx_u16(instance_id));
    // USER_CODE_END::onEntry_Stopped
}
// GEN_OBJ_END::telemetry_sm_on_entry_Stopped



// Guard condition functions
// GEN_OBJ_START::telemetry_sm_guard_is_hold_time_elapsed
bool telemetry_sm_guard_is_hold_time_elapsed(const uint16_t instance_id, const sState_t* const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::guard_is_hold_time_elapsed
    tlm_runtime_context_t *p_tlm_rt_ctx          = telemetry_cfg_get_ctx_u16(instance_id);
    bool                   is_hold_timer_elapsed = ((IS_TRUE(p_tlm_rt_ctx->hold_timer.is_running)) &&
                                  (true == timer_is_elapsed(&p_tlm_rt_ctx->hold_timer, p_tlm_rt_ctx->hold_period_s * 1000U)));

    if (true == is_hold_timer_elapsed)
    {
        timer_stop(&p_tlm_rt_ctx->hold_timer);
        p_tlm_rt_ctx->hold_period_s = 0U;
    }

    return is_hold_timer_elapsed;
    // USER_CODE_END::guard_is_hold_time_elapsed
}
// GEN_OBJ_END::telemetry_sm_guard_is_hold_time_elapsed


// Action handlers
// GEN_OBJ_START::telemetry_sm_action_reload_config
void telemetry_sm_action_reload_config(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::action_reload_config
    tlm_runtime_context_t *p_tlm_rt_ctx = telemetry_cfg_get_ctx_u16(instance_id);

    if ((IS_TRUE(p_tlm_rt_ctx->reload_config_timer.is_running)) &&
        (true == timer_is_elapsed(&p_tlm_rt_ctx->reload_config_timer, TLM_RELOAD_CFG_TIME_MS)))
    {
        telemetry_load_config(p_tlm_rt_ctx);

        timer_start(&p_tlm_rt_ctx->reload_config_timer);
    }

    // USER_CODE_END::action_reload_config
}
// GEN_OBJ_END::telemetry_sm_action_reload_config

// GEN_OBJ_START::telemetry_sm_action_stop_file_telemetry
void telemetry_sm_action_stop_file_telemetry(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::action_stop_file_telemetry
    tlm_runtime_context_t *p_tlm_rt_ctx = telemetry_cfg_get_ctx_u16(instance_id);

    telemetry_file_sink_if.cmd(&p_tlm_rt_ctx->tlm_file_sink_rt, TELEMETRY_SINK_ADAPTER_CMD_STOP);
    // USER_CODE_END::action_stop_file_telemetry
}
// GEN_OBJ_END::telemetry_sm_action_stop_file_telemetry

// GEN_OBJ_START::telemetry_sm_action_collect_telemetry
void telemetry_sm_action_collect_telemetry(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::action_collect_telemetry
    tlm_runtime_context_t *p_tlm_rt_ctx = telemetry_cfg_get_ctx_u16(instance_id);

    uint16_t current_slot_idx = (p_tlm_rt_ctx->next_start_slot_idx < TELEMETRY_MAX_CONFIGURABLE_ENTRIES) ? p_tlm_rt_ctx->next_start_slot_idx : 0;
    uint16_t end_slot_idx     = (current_slot_idx + TELEMETRY_MAX_CONFIGURABLE_ENTRIES) % TELEMETRY_MAX_CONFIGURABLE_ENTRIES;
    bool     is_pushed_ok     = false;

    ES_TRACE_DEBUG("[%u] scan range is ['%u'..'%u']", (uint8_t)p_tlm_rt_ctx->sm_instance_id, current_slot_idx, end_slot_idx);

    telemetry_load_config(p_tlm_rt_ctx);

    // invalidate last skipped slot before next use
    p_tlm_rt_ctx->next_start_slot_idx = TELEMETRY_MAX_CONFIGURABLE_ENTRIES;

    do
    {
        TELEMETRY_tlm_preset_cfg_t tlm_entry = p_tlm_rt_ctx->preset_cfg.tlm_slots_setting[p_tlm_rt_ctx->active_preset_id][current_slot_idx];

        // has acquisition period elapsed?
        if ((true == tlm_entry.bActive) &&
            (tlm_entry.u16Acq_period_ms > 0U) &&
            (true == timer_is_elapsed(&p_tlm_rt_ctx->tlm_entry_timer[current_slot_idx], tlm_entry.u16Acq_period_ms)))
        {
            is_pushed_ok = try_push_tlm_entry_to_queue(p_tlm_rt_ctx, &tlm_entry);

            if ((TELEMETRY_MAX_CONFIGURABLE_ENTRIES == p_tlm_rt_ctx->next_start_slot_idx) &&
                (false == is_pushed_ok))
            {
                // preserve the first slot which was not successfully pushed to the dispatch queue as the starting slot for
                // the next collection round
                p_tlm_rt_ctx->next_start_slot_idx = current_slot_idx;

                ES_TRACE_DEBUG("[%u] will start from slot '%u' next round", (uint8_t)p_tlm_rt_ctx->sm_instance_id, p_tlm_rt_ctx->next_start_slot_idx);

                // there may be other failures during the preset scan because the loop will continue in a cyclic fashion
                // but next time we start from the slot which failed first
            }

            // reset acquisition time
            timer_start(&p_tlm_rt_ctx->tlm_entry_timer[current_slot_idx]);
        }

        current_slot_idx = (current_slot_idx + 1) % TELEMETRY_MAX_CONFIGURABLE_ENTRIES;
    } while (current_slot_idx != end_slot_idx);
    // USER_CODE_END::action_collect_telemetry
}
// GEN_OBJ_END::telemetry_sm_action_collect_telemetry

// GEN_OBJ_START::telemetry_sm_action_start_file_telemetry
void telemetry_sm_action_start_file_telemetry(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::action_start_file_telemetry
    tlm_runtime_context_t *p_tlm_rt_ctx = telemetry_cfg_get_ctx_u16(instance_id);

    telemetry_file_sink_if.cmd(&p_tlm_rt_ctx->tlm_file_sink_rt, TELEMETRY_SINK_ADAPTER_CMD_START);
    // USER_CODE_END::action_start_file_telemetry
}
// GEN_OBJ_END::telemetry_sm_action_start_file_telemetry