/*
 * Copyright (c) EnduroSat AD. All rights reserved.
 *
 * Contents and presentations are protected world-wide.
 * Any kind of using, copying etc. is prohibited without prior permission.
 * -----------------------------------------------------------------------------
 * Generated by hsmgen 2.0.1
 * -----------------------------------------------------------------------------
 */

#ifndef TELEMETRY_FILE_SINK_SM_CONFIG_USER_H
#define TELEMETRY_FILE_SINK_SM_CONFIG_USER_H

#ifdef __cplusplus
extern "C" {
#endif

#include "libhsm.h"

// USER_CODE_START::@main@
// Any code placed between these two tags will be preserved during code generation!
#include "telemetry_context_types.h"

/** @brief Responsible to clean-up all existing telemetry files on the storage.
 *
 *  @param[in] p_tlm_filesink_rt_ctx telemetry file sink context pointer
 *
 */
void telemetry_file_sink_clean(tlm_file_sink_rt_ctx_t *const p_tlm_filesink_rt_ctx);

// USER_CODE_END::@main@

// Entry/Exit functions
void telemetry_file_sink_sm_on_entry_Init(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);
void telemetry_file_sink_sm_on_entry_Wait_Cleanup(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);
void telemetry_file_sink_sm_on_exit_Wait_Cleanup(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);

// Guard condition functions
bool telemetry_file_sink_sm_guard_is_storage_available(const uint16_t instance_id, const sState_t* const pSMRoot, const sHSM_EventType_t * const pEvent);
bool telemetry_file_sink_sm_guard_is_storage_blocked(const uint16_t instance_id, const sState_t* const pSMRoot, const sHSM_EventType_t * const pEvent);
bool telemetry_file_sink_sm_guard_is_cleanup_finished(const uint16_t instance_id, const sState_t* const pSMRoot, const sHSM_EventType_t * const pEvent);

// Action handlers
void telemetry_file_sink_sm_action_reload_config(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);
void telemetry_file_sink_sm_action_prepare_file_telemetry(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);
void telemetry_file_sink_sm_action_store_telemetry(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);
void telemetry_file_sink_sm_action_clean_and_reload_cfg(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);

#ifdef __cplusplus
};
#endif

#endif  // #ifndef TELEMETRY_FILE_SINK_SM_CONFIG_USER_H
