// Header list generated by CMake:
#include "fp/conops/v2.0/conops_server/FP_conopsServerApp.h"
#include "fp/gnss/v1.2/gnss_server/FP_gnssServerApp.h"
#include "fp/OBC_CUBEADCS/v2.1/OBC_CUBEADCS_server/FP_OBC_CUBEADCSServerApp.h"
#include "fp/EPS1/v0.1/EPS1_client/FP_EPS1ClientApp.h"
#include "fp/EPSII_BP_1/v3.0/EPSII_BP_1_client/FP_EPSII_BP_1ClientApp.h"
#include "fp/EPSII_PDM_1/v1.0/EPSII_PDM_1_client/FP_EPSII_PDM_1ClientApp.h"
#include "fp/eps_iii_batt_pack/v2.0/eps_iii_batt_pack_client/FP_eps_iii_batt_packClientApp.h"
#include "fp/eps_iii_pdm_a/v2.0/eps_iii_pdm_a_client/FP_eps_iii_pdm_aClientApp.h"
#include "fp/eps_iii_pdm_b/v2.0/eps_iii_pdm_b_client/FP_eps_iii_pdm_bClientApp.h"
#include "fp/eps_iii_expander/v2.0/eps_iii_expander_client/FP_eps_iii_expanderClientApp.h"
#include "fp/eps_iii_input_stage/v2.0/eps_iii_input_stage_client/FP_eps_iii_input_stageClientApp.h"
#include "fp/SBAND_TMTC/v1.12/SBAND_TMTC_client/FP_SBAND_TMTCClientApp.h"
#include "fp/adis16265_gyro/v1.0/adis16265_gyro_server/FP_adis16265_gyroServerApp.h"
#include "fp/nvm_eps/v0.1/nvm_eps_server/FP_nvm_epsServerApp.h"
#include "fp/nvm/v1.0/nvm_server/FP_nvmServerApp.h"
#include "fp/eps_ctrl/v0.1/eps_ctrl_server/FP_eps_ctrlServerApp.h"
#include "fp/data_cache/v0.1/data_cache_server/FP_data_cacheServerApp.h"
#include "fp/payload_ctrl/v2.0/payload_ctrl_server/FP_payload_ctrlServerApp.h"
#include "fp/time/v0.1/time_server/FP_timeServerApp.h"
#include "fp/fault_ops/v0.1/fault_ops_server/FP_fault_opsServerApp.h"
#include "trace_level_config/v0.1/trace_level_config_server/FP_trace_level_configServerApp.h"
#include "fp/fdir_srv/v0.2/fdir_srv_server/FP_fdir_srvServerApp.h"
#include "fp/onboard_sched/v0.1/onboard_sched_server/FP_onboard_schedServerApp.h"
#include "fp/sp_uhf_ant/v2.1/sp_uhf_ant_client/FP_sp_uhf_antClientApp.h"
#include "fp/comm_loss_wd/v0.3/comm_loss_wd_server/FP_comm_loss_wdServerApp.h"
#include "fp/csp_service/v0.1/csp_service_server/FP_csp_serviceServerApp.h"
#include "fp/OBC_AOCS_CNTRL/v1.0/OBC_AOCS_CNTRL_server/FP_OBC_AOCS_CNTRLServerApp.h"
#include "fp/OBC_CUBEADCS_GEN2/v5.0/OBC_CUBEADCS_GEN2_server/FP_OBC_CUBEADCS_GEN2ServerApp.h"
#include "fp/telemetry/v2.0/telemetry_server/FP_telemetryServerApp.h"
#include "fp/Beacons/v1.0/Beacons_server/FP_BeaconsServerApp.h"
#include "fp/crypto/v0.1/crypto_server/FP_cryptoServerApp.h"
#include "fp/SDS/v1.0/SDS_server/FP_SDSServerApp.h"
#include "fp/coordsys/v2.0/coordsys_server/FP_coordsysServerApp.h"
#include "fp/acs/v1.2/acs_server/FP_acsServerApp.h"
#include "fp/MacServices/v0.1/MacServices_server/FP_MacServicesServerApp.h"
#include "fp/ModuleId/v0.1/ModuleId_server/FP_ModuleIdServerApp.h"
#include "fp/FileManager/v1.2/FileManager_server/FP_FileManagerServerApp.h"
#include "fp/obc/v4.1/obc_server/FP_obcServerApp.h"
#include "fp/UHF/v0.5/UHF_client/FP_UHFClientApp.h"
#include "fp/task_stat/v0.1/task_stat_server/FP_task_statServerApp.h"
#include "fp/obc_micropython/v1.1/obc_micropython_server/FP_obc_micropythonServerApp.h"

// A wrapper function, which calls the init functions of all the enabled services
void ESSA_Stack_Services_Init()
{
    // Functions generated by CMake:
    conopsServerAppInit();
    gnssServerAppInit();
    OBC_CUBEADCSServerAppInit();
    EPS1ClientAppInit();
    EPSII_BP_1ClientAppInit();
    EPSII_PDM_1ClientAppInit();
    eps_iii_batt_packClientAppInit();
    eps_iii_pdm_aClientAppInit();
    eps_iii_pdm_bClientAppInit();
    eps_iii_expanderClientAppInit();
    eps_iii_input_stageClientAppInit();
    SBAND_TMTCClientAppInit();
    adis16265_gyroServerAppInit();
    nvm_epsServerAppInit();
    nvmServerAppInit();
    eps_ctrlServerAppInit();
    data_cacheServerAppInit();
    payload_ctrlServerAppInit();
    timeServerAppInit();
    fault_opsServerAppInit();
    trace_level_configServerAppInit();
    fdir_srvServerAppInit();
    onboard_schedServerAppInit();
    sp_uhf_antClientAppInit();
    comm_loss_wdServerAppInit();
    csp_serviceServerAppInit();
    OBC_AOCS_CNTRLServerAppInit();
    OBC_CUBEADCS_GEN2ServerAppInit();
    telemetryServerAppInit();
    BeaconsServerAppInit();
    cryptoServerAppInit();
    SDSServerAppInit();
    coordsysServerAppInit();
    acsServerAppInit();
    MacServicesServerAppInit();
    ModuleIdServerAppInit();
    FileManagerServerAppInit();
    obcServerAppInit();
    UHFClientAppInit();
    task_statServerAppInit();
    obc_micropythonServerAppInit();
}
