/*
 * Copyright (c) EnduroSat AD. All rights reserved.
 *
 * Contents and presentations are protected world-wide.
 * Any kind of using, copying etc. is prohibited without prior permission.
 * -----------------------------------------------------------------------------
 * Generated by hsmgen 2.0.1
 * -----------------------------------------------------------------------------
 */

#ifndef TEST_SM_USER_H
#define TEST_SM_USER_H

#ifdef __cplusplus
extern "C" {
#endif

#include "libhsm.h"

// State identifiers
enum Test_SM_states
{
    TEST_SM_ROOT,
    TEST_SM_STATE_INITIAL_COMPOSITE,
    INITIAL_COMPOSITE_STATE_INITIAL,
    INITIAL_COMPOSITE_STATE_IDLE,
    TEST_SM_STATE_COMPOSITE,
    COMPOSITE_STATE_COMPOSITE_SUB1,
    COMPOSITE_STATE_COMPOSITE_SUB2,
    COMPOSITE_SUB3_STATE_DEEP_SUB3,
    COMPOSITE_SUB3_STATE_DEEP_SUB4,
    COMPOSITE_STATE_COMPOSITE_SUB3,
    STATE___HISTORY_COMPOSITE,
    TEST_SM_MAX
};

// User state machine events
enum Test_SM_events
{
    ev_Test_SM_user_start = eHSM_StdEvent_UserEvStart,
    ev_Test_SM_start,
    ev_Test_SM_go_composite_history,
    ev_Test_SM_switch_to_idle,
    ev_Test_SM_go_sub2,
    ev_Test_SM_go_sub3,
    ev_Test_SM_trigger_regular_self_trans,
    ev_Test_SM_trigger_self_trans,
    ev_Test_SM_switch_to_initial,
    ev_Test_SM_exec_top_level_action,
    ev_Test_SM_exec_top_level_action1,
    ev_Test_SM_go_to_initial,
    ev_Test_SM_go_to_sub2_direct,
    ev_Test_SM_go_to_sub1_direct,
    ev_Test_SM_MAX
};

// State machine root object
extern sCompositeState_t state_Test_SM;

// Use this macro to access the SM instance instead of a direct reference to
// state_Test_SM variable
#define Test_SM_instance  HSM_UPCAST_STATE(&state_Test_SM)

// Number of SM instances configured in the SM model
#define TEST_SM_INSTANCE_CNT    (2U)

#ifdef __cplusplus
};
#endif

#endif  // #ifndef TEST_SM_USER_H