/*
 * Copyright (c) EnduroSat AD. All rights reserved.
 *
 * Contents and presentations are protected world-wide.
 * Any kind of using, copying etc. is prohibited without prior permission.
 * -----------------------------------------------------------------------------
 * Generated by hsmgen 2.0.1
 * -----------------------------------------------------------------------------
 */

#include <stddef.h>
#include "libhsm.h"
#include "test_sm_config_user.h"
#include "test_sm_user.h"


static const sTransition_t tran_Initial_ev_start_Composite;
static const sTransition_t tran_Initial_ev_go_composite_history___history_Composite;
static const sTransition_t tran_Initial_ev_switch_to_idle_Idle;
static const sTransition_t tran_Initial_ev_go_sub2_Composite_Sub2;
static const sTransition_t tran_Initial_ev_go_sub3_Composite_Sub3;
static const sTransition_t tran_Initial_ev_trigger_regular_self_trans_Initial;
static const sTransition_t tran_Initial_ev_trigger_self_trans_self;
static const sTransition_t tran_Idle_ev_switch_to_initial_Initial;
static const sTransition_t tran_Composite_ev_exec_top_level_action___history_Composite;
static const sTransition_t tran_Composite_ev_exec_top_level_action1___history_Composite;
static const sTransition_t tran_Composite_Sub1_ev_periodic_Composite_Sub2;
static const sTransition_t tran_Composite_Sub1_ev_go_to_initial_Initial;
static const sTransition_t tran_Composite_Sub2_ev_go_to_initial_Initial;
static const sTransition_t tran_Deep_Sub3_ev_go_to_initial_Initial;
static const sTransition_t tran_Deep_Sub3_ev_go_to_sub2_direct_Composite_Sub2;
static const sTransition_t tran_Deep_Sub4_ev_go_to_sub1_direct_Composite_Sub1;
static const sTransition_t tran_Composite_Sub3_ev_go_to_sub2_direct_Composite_Sub2;
static const sTransition_t tran_Composite_Sub3_ev_go_to_initial_Initial;


static const sTransition_t* trans_Initial[8] =
{
    &tran_Initial_ev_start_Composite,
    &tran_Initial_ev_go_composite_history___history_Composite,
    &tran_Initial_ev_switch_to_idle_Idle,
    &tran_Initial_ev_go_sub2_Composite_Sub2,
    &tran_Initial_ev_go_sub3_Composite_Sub3,
    &tran_Initial_ev_trigger_regular_self_trans_Initial,
    &tran_Initial_ev_trigger_self_trans_self,
    NULL
};

static const sTransition_t* trans_Idle[2] =
{
    &tran_Idle_ev_switch_to_initial_Initial,
    NULL
};

static const sTransition_t* trans_Composite[3] =
{
    &tran_Composite_ev_exec_top_level_action___history_Composite,
    &tran_Composite_ev_exec_top_level_action1___history_Composite,
    NULL
};

static const sTransition_t* trans_Composite_Sub1[3] =
{
    &tran_Composite_Sub1_ev_periodic_Composite_Sub2,
    &tran_Composite_Sub1_ev_go_to_initial_Initial,
    NULL
};

static const sTransition_t* trans_Composite_Sub2[2] =
{
    &tran_Composite_Sub2_ev_go_to_initial_Initial,
    NULL
};

static const sTransition_t* trans_Deep_Sub3[3] =
{
    &tran_Deep_Sub3_ev_go_to_initial_Initial,
    &tran_Deep_Sub3_ev_go_to_sub2_direct_Composite_Sub2,
    NULL
};

static const sTransition_t* trans_Deep_Sub4[2] =
{
    &tran_Deep_Sub4_ev_go_to_sub1_direct_Composite_Sub1,
    NULL
};

static const sTransition_t* trans_Composite_Sub3[3] =
{
    &tran_Composite_Sub3_ev_go_to_sub2_direct_Composite_Sub2,
    &tran_Composite_Sub3_ev_go_to_initial_Initial,
    NULL
};


// Test_SM states forward declarations
static sCompositeState_t state_Initial_Composite;
static const sState_t state_Initial;
static const sState_t state_Idle;
static sCompositeState_t state_Composite;
static const sState_t state_Composite_Sub1;
static const sState_t state_Composite_Sub2;
static const sState_t state_Deep_Sub3;
static const sState_t state_Deep_Sub4;
static sCompositeState_t state_Composite_Sub3;

// history/active states instance lists definitions
static sState_t *p_Initial_Composite_inst_history[TEST_SM_INSTANCE_CNT] = {
    HSM_UPCAST_STATE(&state_Initial),HSM_UPCAST_STATE(&state_Initial),
};

static sState_t *p_Initial_Composite_inst_active_states[TEST_SM_INSTANCE_CNT] = {
    HSM_UPCAST_STATE(&state_Initial_Composite),HSM_UPCAST_STATE(&state_Initial_Composite),
};
static sState_t *p_Composite_inst_history[TEST_SM_INSTANCE_CNT] = {
    HSM_UPCAST_STATE(&state_Composite_Sub1),HSM_UPCAST_STATE(&state_Composite_Sub1),
};

static sState_t *p_Composite_inst_active_states[TEST_SM_INSTANCE_CNT] = {
    HSM_UPCAST_STATE(&state_Composite),HSM_UPCAST_STATE(&state_Composite),
};
static sState_t *p_Composite_Sub3_inst_history[TEST_SM_INSTANCE_CNT] = {
    HSM_UPCAST_STATE(&state_Deep_Sub3),HSM_UPCAST_STATE(&state_Deep_Sub3),
};

static sState_t *p_Composite_Sub3_inst_active_states[TEST_SM_INSTANCE_CNT] = {
    HSM_UPCAST_STATE(&state_Composite_Sub3),HSM_UPCAST_STATE(&state_Composite_Sub3),
};

static sState_t *p_Test_SM_inst_history[TEST_SM_INSTANCE_CNT] = {
    HSM_UPCAST_STATE(&state_Initial_Composite),HSM_UPCAST_STATE(&state_Initial_Composite),
};

static sState_t *p_Test_SM_inst_active_states[TEST_SM_INSTANCE_CNT] = {
    HSM_UPCAST_STATE(&state_Test_SM),HSM_UPCAST_STATE(&state_Test_SM),
};

// Test_SM root state definition
sCompositeState_t state_Test_SM =
{
    .state =
    {
        .state_id = TEST_SM_ROOT,
        .pName = "state_Test_SM",
        .onEntryFunc = NULL,
        .onExitFunc = NULL,
        .pTransitionList = NULL,
        .eType = eHSM_StateType_Composite,
        .pParent = NULL
    },
    .pInitialState = HSM_UPCAST_STATE(&state_Initial_Composite),
    .instanceCnt = 2,
    .ppHistoryState = p_Test_SM_inst_history,
    .ppActiveState = p_Test_SM_inst_active_states
};
static sCompositeState_t state_Initial_Composite =
{
    .state =
    {
        .state_id = TEST_SM_STATE_INITIAL_COMPOSITE,
        .pName = "state_Initial_Composite",
        .onEntryFunc = &Test_SM_on_entry_Initial_Composite,
        .onExitFunc = &Test_SM_on_exit_Initial_Composite,
        .pTransitionList = NULL,
        .eType = eHSM_StateType_Composite,
        .pParent = HSM_UPCAST_STATE(&state_Test_SM)
    },
    .pInitialState = HSM_UPCAST_STATE(&state_Initial),
    .instanceCnt = 2,
    .ppHistoryState = p_Initial_Composite_inst_history,
    .ppActiveState = p_Initial_Composite_inst_active_states
};

static const sState_t state_Initial =
{
    .state_id = INITIAL_COMPOSITE_STATE_INITIAL,
    .pName = "state_Initial",
    .onEntryFunc = &Test_SM_on_entry_Initial,
    .onExitFunc = &Test_SM_on_exit_Initial,
    .pTransitionList = trans_Initial,
    .eType = eHSM_StateType_Simple,
    .pParent = HSM_UPCAST_STATE(&state_Initial_Composite)
};

static const sState_t state_Idle =
{
    .state_id = INITIAL_COMPOSITE_STATE_IDLE,
    .pName = "state_Idle",
    .onEntryFunc = &Test_SM_on_entry_Idle,
    .onExitFunc = &Test_SM_on_exit_Idle,
    .pTransitionList = trans_Idle,
    .eType = eHSM_StateType_Simple,
    .pParent = HSM_UPCAST_STATE(&state_Initial_Composite)
};

static sCompositeState_t state_Composite =
{
    .state =
    {
        .state_id = TEST_SM_STATE_COMPOSITE,
        .pName = "state_Composite",
        .onEntryFunc = &Test_SM_on_entry_Composite,
        .onExitFunc = &Test_SM_on_exit_Composite,
        .pTransitionList = trans_Composite,
        .eType = eHSM_StateType_Composite,
        .pParent = HSM_UPCAST_STATE(&state_Test_SM)
    },
    .pInitialState = HSM_UPCAST_STATE(&state_Composite_Sub1),
    .instanceCnt = 2,
    .ppHistoryState = p_Composite_inst_history,
    .ppActiveState = p_Composite_inst_active_states
};

static const sState_t state_Composite_Sub1 =
{
    .state_id = COMPOSITE_STATE_COMPOSITE_SUB1,
    .pName = "state_Composite_Sub1",
    .onEntryFunc = &Test_SM_on_entry_Composite_Sub1,
    .onExitFunc = &Test_SM_on_exit_Composite_Sub1,
    .pTransitionList = trans_Composite_Sub1,
    .eType = eHSM_StateType_Simple,
    .pParent = HSM_UPCAST_STATE(&state_Composite)
};

static const sState_t state_Composite_Sub2 =
{
    .state_id = COMPOSITE_STATE_COMPOSITE_SUB2,
    .pName = "state_Composite_Sub2",
    .onEntryFunc = &Test_SM_on_entry_Composite_Sub2,
    .onExitFunc = &Test_SM_on_exit_Composite_Sub2,
    .pTransitionList = trans_Composite_Sub2,
    .eType = eHSM_StateType_Simple,
    .pParent = HSM_UPCAST_STATE(&state_Composite)
};

static const sState_t state_Deep_Sub3 =
{
    .state_id = COMPOSITE_SUB3_STATE_DEEP_SUB3,
    .pName = "state_Deep_Sub3",
    .onEntryFunc = &Test_SM_on_entry_Deep_Sub3,
    .onExitFunc = &Test_SM_on_exit_Deep_Sub3,
    .pTransitionList = trans_Deep_Sub3,
    .eType = eHSM_StateType_Simple,
    .pParent = HSM_UPCAST_STATE(&state_Composite_Sub3)
};

static const sState_t state_Deep_Sub4 =
{
    .state_id = COMPOSITE_SUB3_STATE_DEEP_SUB4,
    .pName = "state_Deep_Sub4",
    .onEntryFunc = &Test_SM_on_entry_Deep_Sub4,
    .onExitFunc = &Test_SM_on_exit_Deep_Sub4,
    .pTransitionList = trans_Deep_Sub4,
    .eType = eHSM_StateType_Simple,
    .pParent = HSM_UPCAST_STATE(&state_Composite_Sub3)
};

static sCompositeState_t state_Composite_Sub3 =
{
    .state =
    {
        .state_id = COMPOSITE_STATE_COMPOSITE_SUB3,
        .pName = "state_Composite_Sub3",
        .onEntryFunc = &Test_SM_on_entry_Composite_Sub3,
        .onExitFunc = &Test_SM_on_exit_Composite_Sub3,
        .pTransitionList = trans_Composite_Sub3,
        .eType = eHSM_StateType_Composite,
        .pParent = HSM_UPCAST_STATE(&state_Composite)
    },
    .pInitialState = HSM_UPCAST_STATE(&state_Deep_Sub3),
    .instanceCnt = 2,
    .ppHistoryState = p_Composite_Sub3_inst_history,
    .ppActiveState = p_Composite_Sub3_inst_active_states
};

static const sState_t state___history_Composite =
{
    .state_id = STATE___HISTORY_COMPOSITE,
    .pName = "state___history_Composite",
    .onEntryFunc = NULL,
    .onExitFunc = NULL,
    .pTransitionList = NULL,
    .eType = eHSM_StateType_History,
    .pParent = HSM_UPCAST_STATE(&state_Composite)
};

static const sTransition_t tran_Initial_ev_start_Composite =
{
    .eventId = ev_Test_SM_start,
    .guardFunc = &Test_SM_guard_start_conditions_met,
    .pTargetState = HSM_UPCAST_STATE(&state_Composite),
    .onTransitionActionFunc = &Test_SM_action_on_start_action,
};

static const sTransition_t tran_Initial_ev_go_composite_history___history_Composite =
{
    .eventId = ev_Test_SM_go_composite_history,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state___history_Composite),
    .onTransitionActionFunc = NULL
};

static const sTransition_t tran_Initial_ev_switch_to_idle_Idle =
{
    .eventId = ev_Test_SM_switch_to_idle,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state_Idle),
    .onTransitionActionFunc = NULL
};

static const sTransition_t tran_Initial_ev_go_sub2_Composite_Sub2 =
{
    .eventId = ev_Test_SM_go_sub2,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state_Composite_Sub2),
    .onTransitionActionFunc = NULL
};

static const sTransition_t tran_Initial_ev_go_sub3_Composite_Sub3 =
{
    .eventId = ev_Test_SM_go_sub3,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state_Composite_Sub3),
    .onTransitionActionFunc = NULL
};

static const sTransition_t tran_Initial_ev_trigger_regular_self_trans_Initial =
{
    .eventId = ev_Test_SM_trigger_regular_self_trans,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state_Initial),
    .onTransitionActionFunc = &Test_SM_action_on_regular_self_action,
};

static const sTransition_t tran_Initial_ev_trigger_self_trans_self =
{
    .eventId = ev_Test_SM_trigger_self_trans,
    .guardFunc = NULL,
    .pTargetState = NULL,
    .onTransitionActionFunc = &Test_SM_action_on_self_action,
};

static const sTransition_t tran_Idle_ev_switch_to_initial_Initial =
{
    .eventId = ev_Test_SM_switch_to_initial,
    .guardFunc = &Test_SM_guard_initial_cond_met,
    .pTargetState = HSM_UPCAST_STATE(&state_Initial),
    .onTransitionActionFunc = &Test_SM_action_on_initial_switch_action,
};

static const sTransition_t tran_Composite_ev_exec_top_level_action___history_Composite =
{
    .eventId = ev_Test_SM_exec_top_level_action,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state___history_Composite),
    .onTransitionActionFunc = &Test_SM_action_on_top_level_action,
};

static const sTransition_t tran_Composite_ev_exec_top_level_action1___history_Composite =
{
    .eventId = ev_Test_SM_exec_top_level_action1,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state___history_Composite),
    .onTransitionActionFunc = &Test_SM_action_on_top_level_action1,
};

static const sTransition_t tran_Composite_Sub1_ev_periodic_Composite_Sub2 =
{
    .eventId = eHSM_StdEvent_Periodic,
    .guardFunc = &Test_SM_guard_entry_to_sub2_allowed,
    .pTargetState = HSM_UPCAST_STATE(&state_Composite_Sub2),
    .onTransitionActionFunc = &Test_SM_action_composite_sub2_action,
};

static const sTransition_t tran_Composite_Sub1_ev_go_to_initial_Initial =
{
    .eventId = ev_Test_SM_go_to_initial,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state_Initial),
    .onTransitionActionFunc = NULL
};

static const sTransition_t tran_Composite_Sub2_ev_go_to_initial_Initial =
{
    .eventId = ev_Test_SM_go_to_initial,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state_Initial),
    .onTransitionActionFunc = NULL
};

static const sTransition_t tran_Deep_Sub3_ev_go_to_initial_Initial =
{
    .eventId = ev_Test_SM_go_to_initial,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state_Initial),
    .onTransitionActionFunc = NULL
};

static const sTransition_t tran_Deep_Sub3_ev_go_to_sub2_direct_Composite_Sub2 =
{
    .eventId = ev_Test_SM_go_to_sub2_direct,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state_Composite_Sub2),
    .onTransitionActionFunc = NULL
};

static const sTransition_t tran_Deep_Sub4_ev_go_to_sub1_direct_Composite_Sub1 =
{
    .eventId = ev_Test_SM_go_to_sub1_direct,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state_Composite_Sub1),
    .onTransitionActionFunc = NULL
};

static const sTransition_t tran_Composite_Sub3_ev_go_to_sub2_direct_Composite_Sub2 =
{
    .eventId = ev_Test_SM_go_to_sub2_direct,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state_Composite_Sub2),
    .onTransitionActionFunc = NULL
};

static const sTransition_t tran_Composite_Sub3_ev_go_to_initial_Initial =
{
    .eventId = ev_Test_SM_go_to_initial,
    .guardFunc = NULL,
    .pTargetState = HSM_UPCAST_STATE(&state_Initial),
    .onTransitionActionFunc = NULL
};
