/*
 * Copyright (c) EnduroSat AD. All rights reserved.
 *
 * Contents and presentations are protected world-wide.
 * Any kind of using, copying etc. is prohibited without prior permission.
 * -----------------------------------------------------------------------------
 * Generated by hsmgen 2.0.1
 * -----------------------------------------------------------------------------
 */

#ifndef SDR_SM_CONFIG_USER_H
#define SDR_SM_CONFIG_USER_H

#ifdef __cplusplus
extern "C" {
#endif

#include "libhsm.h"

// USER_CODE_START::@main@

#include "sdr.h"
#include "sdr_op.h"
#include "es_tftp_pkt_codes.h"
#include "es_cdef.h"
#include "timer.h"
#include "datetime.h"

/** @typedef runtime_context_t
 *  @brief Runtime context information for the sdr service
 *
 */
typedef struct
{
    osThreadId_t os_task_hnd;           /** OS task handle */
    es_tftp_err_code_t sdr_ft_status;   /** sdr last file transfer operation status */
    timer_handle_t boot_timer;          /** sdr boot timer handle */
    timer_handle_t sync_timer;          /** sdr sync timer handle */
    bool is_boot_complete;              /** sdr boot complete flag */
    datetime_stamp_t sdr_sync_dt;       /** sdr sync date time stamp */
    bool is_ready_to_sync;              /** sdr ready to sync flag */
    bool sync_data_rdy;                 /** sdr sync data ready flag */
    bool is_op_pending;                 /** sdr operation pending flag */
    sdr_op_req_t sdr_op_req;            /** sdr operation request structure */
    sdr_file_op_t sdr_ft_req;           /** sdr file transfer operation request structure */
} sdr_runtime_context_t;

extern sdr_runtime_context_t sdr_rt_context;

// USER_CODE_END::@main@

// Entry/Exit functions
void sdr_sm_on_entry_inactive(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);
void sdr_sm_on_entry_booting(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);
void sdr_sm_on_exit_booting(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);
void sdr_sm_on_entry_syncing(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);
void sdr_sm_on_exit_syncing(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);
void sdr_sm_on_entry_ready(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);
void sdr_sm_on_entry_busy(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);

// Guard condition functions
bool sdr_sm_guard_is_device_init(const uint16_t instance_id, const sState_t* const pSMRoot, const sHSM_EventType_t * const pEvent);
bool sdr_sm_guard_is_valid_response(const uint16_t instance_id, const sState_t* const pSMRoot, const sHSM_EventType_t * const pEvent);
bool sdr_sm_guard_is_poll_time_elapsed(const uint16_t instance_id, const sState_t* const pSMRoot, const sHSM_EventType_t * const pEvent);
bool sdr_sm_guard_is_data_ready_to_sync(const uint16_t instance_id, const sState_t* const pSMRoot, const sHSM_EventType_t * const pEvent);
bool sdr_sm_guard_is_sync_timeout_elapsed(const uint16_t instance_id, const sState_t* const pSMRoot, const sHSM_EventType_t * const pEvent);
bool sdr_sm_guard_is_operation_pending(const uint16_t instance_id, const sState_t* const pSMRoot, const sHSM_EventType_t * const pEvent);
bool sdr_sm_guard_is_operation_executed(const uint16_t instance_id, const sState_t* const pSMRoot, const sHSM_EventType_t * const pEvent);

// Action handlers
void sdr_sm_action_poll_device(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);
void sdr_sm_action_sync_time(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent);

#ifdef __cplusplus
};
#endif

#endif  // #ifndef SDR_SM_CONFIG_USER_H