/*
 * Copyright (c) EnduroSat AD. All rights reserved.
 *
 * Contents and presentations are protected world-wide.
 * Any kind of using, copying etc. is prohibited without prior permission.
 * -----------------------------------------------------------------------------
 * Generated by hsmgen 2.0.1
 * -----------------------------------------------------------------------------
 */

#include <stddef.h>
#include "libhsm.h"
#include "sdr_sm_config_user.h"
#include "sdr_sm_user.h"


static const sTransition_t tran_inactive_ev_boot_booting;
static const sTransition_t tran_booting_ev_periodic_syncing;
static const sTransition_t tran_booting_ev_periodic_self;
static const sTransition_t tran_syncing_ev_periodic_ready;
static const sTransition_t tran_syncing_ev_periodic_ready_1;
static const sTransition_t tran_ready_ev_periodic_busy;
static const sTransition_t tran_busy_ev_periodic_ready;


static const sTransition_t* trans_inactive[2] =
{
    &tran_inactive_ev_boot_booting,
    NULL
};

static const sTransition_t* trans_booting[3] =
{
    &tran_booting_ev_periodic_syncing,
    &tran_booting_ev_periodic_self,
    NULL
};

static const sTransition_t* trans_syncing[3] =
{
    &tran_syncing_ev_periodic_ready,
    &tran_syncing_ev_periodic_ready_1,
    NULL
};

static const sTransition_t* trans_ready[2] =
{
    &tran_ready_ev_periodic_busy,
    NULL
};

static const sTransition_t* trans_busy[2] =
{
    &tran_busy_ev_periodic_ready,
    NULL
};


// sdr_sm states forward declarations
static const sState_t state_inactive;
static const sState_t state_booting;
static const sState_t state_syncing;
static const sState_t state_ready;
static const sState_t state_busy;

// history/active states instance lists definitions

static sState_t *p_sdr_sm_inst_history[SDR_SM_INSTANCE_CNT] = {
    HSM_UPCAST_STATE(&state_inactive),
};

static sState_t *p_sdr_sm_inst_active_states[SDR_SM_INSTANCE_CNT] = {
    HSM_UPCAST_STATE(&state_sdr_sm),
};

// sdr_sm root state definition
sCompositeState_t state_sdr_sm =
{
    .state =
    {
        .state_id = SDR_SM_ROOT,
        .pName = "state_sdr_sm",
        .onEntryFunc = NULL,
        .onExitFunc = NULL,
        .pTransitionList = NULL,
        .eType = eHSM_StateType_Composite,
        .pParent = NULL
    },
    .pInitialState = HSM_UPCAST_STATE(&state_inactive),
    .instanceCnt = 1,
    .ppHistoryState = p_sdr_sm_inst_history,
    .ppActiveState = p_sdr_sm_inst_active_states
};

static const sState_t state_inactive =
{
    .state_id = SDR_SM_STATE_INACTIVE,
    .pName = "state_inactive",
    .onEntryFunc = &sdr_sm_on_entry_inactive,
    .onExitFunc = NULL,
    .pTransitionList = trans_inactive,
    .eType = eHSM_StateType_Simple,
    .pParent = HSM_UPCAST_STATE(&state_sdr_sm)
};


static const sState_t state_booting =
{
    .state_id = SDR_SM_STATE_BOOTING,
    .pName = "state_booting",
    .onEntryFunc = &sdr_sm_on_entry_booting,
    .onExitFunc = &sdr_sm_on_exit_booting,
    .pTransitionList = trans_booting,
    .eType = eHSM_StateType_Simple,
    .pParent = HSM_UPCAST_STATE(&state_sdr_sm)
};


static const sState_t state_syncing =
{
    .state_id = SDR_SM_STATE_SYNCING,
    .pName = "state_syncing",
    .onEntryFunc = &sdr_sm_on_entry_syncing,
    .onExitFunc = &sdr_sm_on_exit_syncing,
    .pTransitionList = trans_syncing,
    .eType = eHSM_StateType_Simple,
    .pParent = HSM_UPCAST_STATE(&state_sdr_sm)
};


static const sState_t state_ready =
{
    .state_id = SDR_SM_STATE_READY,
    .pName = "state_ready",
    .onEntryFunc = &sdr_sm_on_entry_ready,
    .onExitFunc = NULL,
    .pTransitionList = trans_ready,
    .eType = eHSM_StateType_Simple,
    .pParent = HSM_UPCAST_STATE(&state_sdr_sm)
};


static const sState_t state_busy =
{
    .state_id = SDR_SM_STATE_BUSY,
    .pName = "state_busy",
    .onEntryFunc = &sdr_sm_on_entry_busy,
    .onExitFunc = NULL,
    .pTransitionList = trans_busy,
    .eType = eHSM_StateType_Simple,
    .pParent = HSM_UPCAST_STATE(&state_sdr_sm)
};

static const sTransition_t tran_inactive_ev_boot_booting =
{
    .eventId = ev_sdr_sm_boot,
    .guardFunc = &sdr_sm_guard_is_device_init,
    .pTargetState = HSM_UPCAST_STATE(&state_booting),
    .onTransitionActionFunc = NULL
};

static const sTransition_t tran_booting_ev_periodic_syncing =
{
    .eventId = eHSM_StdEvent_Periodic,
    .guardFunc = &sdr_sm_guard_is_valid_response,
    .pTargetState = HSM_UPCAST_STATE(&state_syncing),
    .onTransitionActionFunc = NULL
};

static const sTransition_t tran_booting_ev_periodic_self =
{
    .eventId = eHSM_StdEvent_Periodic,
    .guardFunc = &sdr_sm_guard_is_poll_time_elapsed,
    .pTargetState = NULL,
    .onTransitionActionFunc = &sdr_sm_action_poll_device,
};

static const sTransition_t tran_syncing_ev_periodic_ready =
{
    .eventId = eHSM_StdEvent_Periodic,
    .guardFunc = &sdr_sm_guard_is_data_ready_to_sync,
    .pTargetState = HSM_UPCAST_STATE(&state_ready),
    .onTransitionActionFunc = &sdr_sm_action_sync_time,
};

static const sTransition_t tran_syncing_ev_periodic_ready_1 =
{
    .eventId = eHSM_StdEvent_Periodic,
    .guardFunc = &sdr_sm_guard_is_sync_timeout_elapsed,
    .pTargetState = HSM_UPCAST_STATE(&state_ready),
    .onTransitionActionFunc = NULL
};

static const sTransition_t tran_ready_ev_periodic_busy =
{
    .eventId = eHSM_StdEvent_Periodic,
    .guardFunc = &sdr_sm_guard_is_operation_pending,
    .pTargetState = HSM_UPCAST_STATE(&state_busy),
    .onTransitionActionFunc = NULL
};

static const sTransition_t tran_busy_ev_periodic_ready =
{
    .eventId = eHSM_StdEvent_Periodic,
    .guardFunc = &sdr_sm_guard_is_operation_executed,
    .pTargetState = HSM_UPCAST_STATE(&state_ready),
    .onTransitionActionFunc = NULL
};
