/*
 * Copyright (c) EnduroSat AD. All rights reserved.
 *
 * Contents and presentations are protected world-wide.
 * Any kind of using, copying etc. is prohibited without prior permission.
 * -----------------------------------------------------------------------------
 * Generated by hsmgen 2.0.1
 * -----------------------------------------------------------------------------
 */

#ifndef SDR_SM_USER_H
#define SDR_SM_USER_H

#ifdef __cplusplus
extern "C" {
#endif

#include "libhsm.h"

// State identifiers
enum sdr_sm_states
{
    SDR_SM_ROOT,
    SDR_SM_STATE_INACTIVE,
    SDR_SM_STATE_BOOTING,
    SDR_SM_STATE_SYNCING,
    SDR_SM_STATE_READY,
    SDR_SM_STATE_BUSY,
    SDR_SM_MAX
};

// User state machine events
enum sdr_sm_events
{
    ev_sdr_sm_user_start = eHSM_StdEvent_UserEvStart,
    ev_sdr_sm_boot,
    ev_sdr_sm_MAX
};

// State machine root object
extern sCompositeState_t state_sdr_sm;

// Use this macro to access the SM instance instead of a direct reference to
// state_sdr_sm variable
#define sdr_sm_instance  HSM_UPCAST_STATE(&state_sdr_sm)

// Number of SM instances configured in the SM model
#define SDR_SM_INSTANCE_CNT    (1U)

#ifdef __cplusplus
};
#endif

#endif  // #ifndef SDR_SM_USER_H