/*
 * Copyright (c) EnduroSat AD. All rights reserved.
 *
 * Contents and presentations are protected world-wide.
 * Any kind of using, copying etc. is prohibited without prior permission.
 * -----------------------------------------------------------------------------
 * Generated by hsmgen 2.0.1
 * -----------------------------------------------------------------------------
 */

#include "libhsm.h"
#include "sdr_sm_config_user.h"

// USER_CODE_START::@main@

/**
 * @addtogroup sdr
 * @{
 * @file sdr_sm_config_user.c
 * @brief The file implements the sdr service SM functions (e.g. @a guard, @a action and @a on_entry/on_exit handlers)
 * @}
 *
 */

#include "sdr_sm_user.h"
#include "sdr_cfg.h"
#include "assertions.h"
#include "trace.h"
#include "sdr_critical.h"

INIT_CMP_LOGGER(true, TRACE_LVL_WARN)

// USER_CODE_END::@main@

// Entry/Exit functions

// GEN_OBJ_START::sdr_sm_on_entry_inactive
void sdr_sm_on_entry_inactive(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::onEntry_inactive
    sdr_rt_context.is_op_pending = false;
    timer_stop(&sdr_rt_context.boot_timer);
    timer_stop(&sdr_rt_context.sync_timer);
    // USER_CODE_END::onEntry_inactive
}
// GEN_OBJ_END::sdr_sm_on_entry_inactive


// GEN_OBJ_START::sdr_sm_on_entry_booting
void sdr_sm_on_entry_booting(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::onEntry_booting
    sdr_rt_context.is_boot_complete = false;
    timer_start(&sdr_rt_context.boot_timer);
    // USER_CODE_END::onEntry_booting
}
// GEN_OBJ_END::sdr_sm_on_entry_booting

// GEN_OBJ_START::sdr_sm_on_exit_booting
void sdr_sm_on_exit_booting(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::onExit_booting
    timer_stop(&sdr_rt_context.boot_timer);
    // USER_CODE_END::onExit_booting
}
// GEN_OBJ_END::sdr_sm_on_exit_booting


// GEN_OBJ_START::sdr_sm_on_entry_syncing
void sdr_sm_on_entry_syncing(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::onEntry_syncing
    sdr_rt_context.is_ready_to_sync = true;
    sdr_rt_context.sync_data_rdy = false;
    timer_start(&sdr_rt_context.sync_timer);
    // USER_CODE_END::onEntry_syncing
}
// GEN_OBJ_END::sdr_sm_on_entry_syncing

// GEN_OBJ_START::sdr_sm_on_exit_syncing
void sdr_sm_on_exit_syncing(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::onExit_syncing
    timer_stop(&sdr_rt_context.sync_timer);
    // USER_CODE_END::onExit_syncing
}
// GEN_OBJ_END::sdr_sm_on_exit_syncing


// GEN_OBJ_START::sdr_sm_on_entry_ready
void sdr_sm_on_entry_ready(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::onEntry_ready
    sdr_rt_context.is_op_pending = false;
    // USER_CODE_END::onEntry_ready
}
// GEN_OBJ_END::sdr_sm_on_entry_ready


// GEN_OBJ_START::sdr_sm_on_entry_busy
void sdr_sm_on_entry_busy(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::onEntry_busy
    // service operation request, based on operation type
    es_tftp_err_code_t res = ES_TFTP_ERR_NOT_DEFINED;
    switch (sdr_rt_context.sdr_op_req.op)
    {
        case OP_FILE_TRANSFER:
            {
                if (UPLOAD == sdr_rt_context.sdr_ft_req.ft_op)
                {
                    res = sdr_upload(&sdr_rt_context.sdr_ft_req);
                    ES_TRACE_DEBUG("sdr op> [upload] file from SDR -> [%d]", res);
                }
                else if (DOWNLOAD == sdr_rt_context.sdr_ft_req.ft_op)
                {
                    res = sdr_download(&sdr_rt_context.sdr_ft_req);
                    ES_TRACE_DEBUG("sdr op> [download] file from SDR -> [%d]", res);
                }
                else
                {
                    ES_TRACE_ERROR("sdr op> [file transfer] invalid operation");
                    sdr_rt_context.sdr_ft_status = ES_TFTP_ERR_ILLEGAL_TFTP_OPERATION;
                }
            }
            break;
        case OP_COMMAND:
            {
                ES_TRACE_DEBUG("sdr op> [command] operation");
            }
            break;
        default:
            {
                ES_TRACE_DEBUG("sdr op> unknown operation");
                sdr_rt_context.sdr_ft_status = ES_TFTP_ERR_NOT_DEFINED;
            }
            break;
    }

    sdr_rt_context.sdr_ft_status = res;
    sdr_rt_context.is_op_pending = false;
    // USER_CODE_END::onEntry_busy
}
// GEN_OBJ_END::sdr_sm_on_entry_busy



// Guard condition functions
// GEN_OBJ_START::sdr_sm_guard_is_device_init
bool sdr_sm_guard_is_device_init(const uint16_t instance_id, const sState_t* const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::guard_is_device_init
    return ((sdr_rt_context.os_task_hnd != NULL) &&
            (true == sdr_critical_is_init()) &&
            (true == es_client_transport_init_done()));
    // USER_CODE_END::guard_is_device_init
}
// GEN_OBJ_END::sdr_sm_guard_is_device_init

// GEN_OBJ_START::sdr_sm_guard_is_valid_response
bool sdr_sm_guard_is_valid_response(const uint16_t instance_id, const sState_t* const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::guard_is_valid_response
    return (true == sdr_rt_context.is_boot_complete);
    // USER_CODE_END::guard_is_valid_response
}
// GEN_OBJ_END::sdr_sm_guard_is_valid_response

// GEN_OBJ_START::sdr_sm_guard_is_poll_time_elapsed
bool sdr_sm_guard_is_poll_time_elapsed(const uint16_t instance_id, const sState_t* const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::guard_is_poll_time_elapsed
    return ((IS_TRUE(sdr_rt_context.boot_timer.is_running)) &&
            (true == timer_is_elapsed(&sdr_rt_context.boot_timer, (const uint32_t)SDR_BOOT_POLL_PERIOD_MS)));
    // USER_CODE_END::guard_is_poll_time_elapsed
}
// GEN_OBJ_END::sdr_sm_guard_is_poll_time_elapsed

// GEN_OBJ_START::sdr_sm_guard_is_data_ready_to_sync
bool sdr_sm_guard_is_data_ready_to_sync(const uint16_t instance_id, const sState_t* const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::guard_is_data_ready_to_sync
    return (true == sdr_rt_context.sync_data_rdy);
    // USER_CODE_END::guard_is_data_ready_to_sync
}
// GEN_OBJ_END::sdr_sm_guard_is_data_ready_to_sync

// GEN_OBJ_START::sdr_sm_guard_is_sync_timeout_elapsed
bool sdr_sm_guard_is_sync_timeout_elapsed(const uint16_t instance_id, const sState_t* const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::guard_is_sync_timeout_elapsed
    return ((IS_TRUE(sdr_rt_context.sync_timer.is_running)) &&
            (true == timer_is_elapsed(&sdr_rt_context.sync_timer, (const uint32_t)SDR_SYNC_TIMEOUT_MS)));
    // USER_CODE_END::guard_is_sync_timeout_elapsed
}
// GEN_OBJ_END::sdr_sm_guard_is_sync_timeout_elapsed

// GEN_OBJ_START::sdr_sm_guard_is_operation_pending
bool sdr_sm_guard_is_operation_pending(const uint16_t instance_id, const sState_t* const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::guard_is_operation_pending
    return (true == sdr_rt_context.is_op_pending);
    // USER_CODE_END::guard_is_operation_pending
}
// GEN_OBJ_END::sdr_sm_guard_is_operation_pending

// GEN_OBJ_START::sdr_sm_guard_is_operation_executed
bool sdr_sm_guard_is_operation_executed(const uint16_t instance_id, const sState_t* const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::guard_is_operation_executed
    return !sdr_sm_guard_is_operation_pending(instance_id, pSMRoot, pEvent);
    // USER_CODE_END::guard_is_operation_executed
}
// GEN_OBJ_END::sdr_sm_guard_is_operation_executed


// Action handlers
// GEN_OBJ_START::sdr_sm_action_poll_device
void sdr_sm_action_poll_device(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::action_poll_device
    es_sys_time_get_req poll_req = es_sys_time_get_req_init_zero;
    es_sys_time_get_res poll_res = es_sys_time_get_res_init_zero;

    poll_res.hdr.stat = ES_STATUS_ERR;

    (void)es_sdr_client_rpc(ES_BOARD_MGR_SERDES_ID, es_board_mgr_rpc_sys_time_get_tag, &poll_req, &poll_res);

    if (ES_STATUS_OK == poll_res.hdr.stat)
    {
        sdr_rt_context.is_boot_complete = true;
    }
    // USER_CODE_END::action_poll_device
}
// GEN_OBJ_END::sdr_sm_action_poll_device

// GEN_OBJ_START::sdr_sm_action_sync_time
void sdr_sm_action_sync_time(const uint16_t instance_id, const sState_t * const pSMRoot, const sHSM_EventType_t * const pEvent)
{
    (void) instance_id;
    (void) pSMRoot;
    (void) pEvent;

    // USER_CODE_START::action_sync_time

    /* Note:    The date and time are formatted as per the requireme
                < UTC Date and/or time formatted with a maxiumum length 25 characters. 
                Simplistic ISO 8601 ASCII/UTF-8 encoded: yyyy-mm-dd hh:mm:ss dd-mm-yyyy hh:mm:ss in any order, .
                A '\' can be used as a delimiter for the date as well. */
    char date_str[11]; // "yyyy-mm-dd"
    char time_str[9];  // "hh:mm:ss"

    // initialize the set time RPC
    sys_time_set_rpc set_time = sys_time_set_rpc_init_zero;
    set_time.payload.req.pl.has_sys_time = true;

    // Note:    Format the date and time using snprintf calls.
    //          The pragma directive is needed to suppress the warning for format truncation.
    //          The warning is suppressed because the format is known and the buffer size is fixed.
    #pragma GCC diagnostic push // push warning state
    #pragma GCC diagnostic ignored "-Wformat-truncation" // ignore format truncation warning
    snprintf(date_str, sizeof(date_str), DATE_FORMAT, sdr_rt_context.sdr_sync_dt.date.year, sdr_rt_context.sdr_sync_dt.date.mon, sdr_rt_context.sdr_sync_dt.date.day);
    snprintf(time_str, sizeof(time_str), TIME_FORMAT, sdr_rt_context.sdr_sync_dt.time.hour, sdr_rt_context.sdr_sync_dt.time.min, sdr_rt_context.sdr_sync_dt.time.sec);

    // format date and time into ISO 8601 ASCII/UTF-8 encoded format as per requirement
    snprintf((char *)set_time.payload.req.pl.sys_time, sizeof(set_time.payload.req.pl.sys_time), "%s %s", date_str, time_str);
    #pragma GCC diagnostic pop // pop warning state

    // dispatch the set_time command
    (void)es_sdr_client_rpc(ES_BOARD_MGR_SERDES_ID, es_board_mgr_rpc_sys_time_set_tag,
                            &set_time.payload.req, &set_time.payload.res);
    sdr_rt_context.is_ready_to_sync = false;

    // .. something to be done with the response status (possibly several retries on failure)

    // USER_CODE_END::action_sync_time
}
// GEN_OBJ_END::sdr_sm_action_sync_time
