/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_ES_BOARD_MGR_PB_H_INCLUDED
#define PB_ES_BOARD_MGR_PB_H_INCLUDED
#include <pb.h>
#include "es_common_types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/**Update bundle info request payload*/
typedef struct _bundle_info_req_pl { 
    char bundle_path[128]; /**< Path to the update bundle*/
} bundle_info_req_pl;

/**Update bundle info response payload*/
typedef struct _bundle_info_res_pl { 
    bool has_compatible;
    char compatible[60]; /**< Compatible of bundle*/
    bool has_ver;
    char ver[60]; /**< Versh string of bundle*/
} bundle_info_res_pl;

/**Update bundle install request payload*/
typedef struct _bundle_install_req_pl { 
    char bundle_path[128]; /**< Path to the update bundle*/
} bundle_install_req_pl;

/**CSP interface to retrieve the configuration for*/
typedef struct _csp_cfg_get_req_pl { 
    char iface[16]; /**< Name of the network interface*/
} csp_cfg_get_req_pl;

/**Configuration of CSP network interface*/
typedef struct _csp_cfg_get_res_pl { 
    bool has_iface;
    char iface[16]; /**< Name of the CSP phy layer to retrieve the configuration for*/
    bool has_address;
    uint32_t address; /**< CSP address of the interface*/
} csp_cfg_get_res_pl;

/**Configuration of eth network interface*/
typedef struct _csp_cfg_set_req_pl { 
    char iface[16]; /**< Name of the network interface*/
    bool has_address;
    uint32_t address; /**< CSP address of the interface*/
} csp_cfg_set_req_pl;

/**Bundle install response*/
typedef struct _es_bundle_install_res { 
    response_hdr hdr; /**< Response header*/
} es_bundle_install_res;

/**CSP Configuration Response*/
typedef struct _es_csp_cfg_set_res { 
    response_hdr hdr; /**< Response header*/
} es_csp_cfg_set_res;

/**ESPS Configuration Set Response*/
typedef struct _es_esps_cfg_set_res { 
    response_hdr hdr; /**< Response header*/
} es_esps_cfg_set_res;

/**Eth Configuration Response*/
typedef struct _es_eth_cfg_set_res { 
    response_hdr hdr; /**< Response header*/
} es_eth_cfg_set_res;

/**Mark slot request*/
typedef struct _es_get_primary_slot_req { 
    request_hdr hdr; /**< Request header*/
} es_get_primary_slot_req;

/**Mark a slot response*/
typedef struct _es_mark_slot_res { 
    response_hdr hdr; /**< Response header*/
} es_mark_slot_res;

/**RF board state get request*/
typedef struct _es_rf_board_stat_get_req { 
    request_hdr hdr; /*Request header*/
} es_rf_board_stat_get_req;

/**Set RF board state response*/
typedef struct _es_rf_board_stat_set_res { 
    response_hdr hdr; /*Response header*/
} es_rf_board_stat_set_res;

/**RTC time force sync request*/
typedef struct _es_rtc_time_force_sync_req { 
    request_hdr hdr; /*Request header*/
} es_rtc_time_force_sync_req;

/**RTC time force sync response*/
typedef struct _es_rtc_time_force_sync_res { 
    response_hdr hdr; /*Request header*/
} es_rtc_time_force_sync_res;

/**Get RTC time request*/
typedef struct _es_rtc_time_get_req { 
    request_hdr hdr; /*Request header*/
} es_rtc_time_get_req;

/**Get system time request*/
typedef struct _es_sys_time_get_req { 
    request_hdr hdr; /*Request header*/
} es_sys_time_get_req;

/**System time PPS lock status request*/
typedef struct _es_sys_time_pps_lock_stat_get_req { 
    request_hdr hdr; /*Request header*/
} es_sys_time_pps_lock_stat_get_req;

/**System time offset to PPS request*/
typedef struct _es_sys_time_pps_offset_get_req { 
    request_hdr hdr; /*Request header*/
} es_sys_time_pps_offset_get_req;

/**Set system time response*/
typedef struct _es_sys_time_set_res { 
    response_hdr hdr; /*Response header*/
} es_sys_time_set_res;

/**System halt request*/
typedef struct _es_system_halt_req { 
    request_hdr hdr; /*Request header*/
} es_system_halt_req;

/**System halt response*/
typedef struct _es_system_halt_res { 
    response_hdr hdr; /*Request header*/
} es_system_halt_res;

/**Update progress request*/
typedef struct _es_update_progress_req { 
    request_hdr hdr; /**< Request header*/
} es_update_progress_req;

/**ESPS interface to retrieve the configuration for*/
typedef struct _esps_cfg_get_req_pl { 
    char iface[16]; /**< Name of the ES MAC interface*/
} esps_cfg_get_req_pl;

/**Configuration of ESPS network interface*/
typedef struct _esps_cfg_get_res_pl { 
    bool has_iface;
    char iface[16]; /**< Name of the ES MAC interface apply the configuration for*/
    bool has_address;
    uint32_t address; /**< ESPS address of the interface*/
} esps_cfg_get_res_pl;

/**Configuration of the ESPS interface*/
typedef struct _esps_cfg_set_req_pl { 
    char iface[16]; /**< Name of the ESPS interface*/
    bool has_address;
    uint32_t address; /**< ESPS address of the interface*/
} esps_cfg_set_req_pl;

/**Eth network interface to retrieve the configuration for*/
typedef struct _eth_cfg_get_req_pl { 
    char iface[16]; /**< Name of the network interface*/
} eth_cfg_get_req_pl;

/**Configuration of eth network interface response payload*/
typedef struct _eth_cfg_get_res_pl { 
    bool has_iface;
    char iface[16]; /**< Name of the network interface*/
    bool has_ipv4;
    char ipv4[18]; /**< IPv4 address of the interface*/
    bool has_mtu;
    uint32_t mtu; /**< MTU of the interface*/
} eth_cfg_get_res_pl;

/**Configuration of eth network interface*/
typedef struct _eth_cfg_set_req_pl { 
    char iface[16]; /**< Name of the network interface*/
    bool has_ipv4;
    char ipv4[18]; /**< IPv4 address of the interface*/
    bool has_mtu;
    uint32_t mtu; /**< MTU of the interface*/
} eth_cfg_set_req_pl;

/**Update get primary slot response payload*/
typedef struct _get_primary_slot_res_pl { 
    char slot[20]; /**< Slot ID*/
} get_primary_slot_res_pl;

/**Update mark slot request payload*/
typedef struct _mark_slot_req_pl { 
    char slot[20]; /**< Slot ID*/
    char slot_state[10]; /**< New state of the slot*/
} mark_slot_req_pl;

/**Get RF board state response payload*/
typedef struct _rf_board_stat_get_res_pl { 
    bool has_enabled;
    bool enabled; /**< RF board enabled*/
    bool has_jesd204_fsm_state;
    char jesd204_fsm_state[80]; /**< JESD204 FSM current state*/
    bool has_jesd204_fsm_error;
    int32_t jesd204_fsm_error; /**< JESD204 FSM errno of previous state transition*/
    bool has_jesd204_fsm_paused;
    bool jesd204_fsm_paused; /**< True indicates that the FSM is currently paused/stopped*/
} rf_board_stat_get_res_pl;

/**Set RF board state request payload*/
typedef struct _rf_board_stat_set_req_pl { 
    bool has_enabled;
    bool enabled; /**< RF board enabled*/
} rf_board_stat_set_req_pl;

/**Get RTC time response payload*/
typedef struct _rtc_time_get_res_pl { 
    bool has_rtc_time;
    char rtc_time[25]; /**< UTC Date and/or time formatted with a maxiumum length 25 characters. ASCII/UTF-8 encoded: yyyy-mm-dd hh:mm:ss*/
} rtc_time_get_res_pl;

/**Update slot status request payload*/
typedef struct _slot_status_req_pl { 
    char slot[20]; /**< Slot ID*/
} slot_status_req_pl;

/**Update slot status response payload*/
typedef struct _slot_status_res_pl { 
    bool has_activated_count;
    uint64_t activated_count; /**< Number of activations*/
    bool has_activated_timestamp;
    char activated_timestamp[24]; /**< Point in time when a bootable slot is activated*/
    bool has_boot_status;
    char boot_status[8]; /**< Boot status*/
    bool has_bootname;
    char bootname[5]; /**< Name of the running slot*/
    bool has_bundle_build;
    char bundle_build[18]; /**< Build ID*/
    bool has_bundle_compatible;
    char bundle_compatible[11]; /**< Compatible string*/
    bool has_bundle_description;
    char bundle_description[18]; /**< Free-form description field that can be used to provide human-readable bundle information*/
    bool has_bundle_ver;
    char bundle_ver[13]; /**< Free-form version string*/
    bool has_slot_cl;
    char slot_cl[10]; /**< Slot class (type)*/
    bool has_device;
    char device[18]; /**< The device path of the slot*/
    bool has_installed_count;
    uint64_t installed_count; /**< The number of updates so far*/
    bool has_installed_timestamp;
    char installed_timestamp[24]; /**< Point in time of installing the image to the slot*/
    bool has_sha256;
    char sha256[8]; /**< sha256 of image file*/
    bool has_size;
    uint64_t size; /**< Size of hte image file*/
    bool has_slot_state;
    char slot_state[12]; /**< The state of the currently installed slot*/
    bool has_status;
    char status[6]; /**< Slot's status*/
    bool has_type;
    char type[8]; /**< Slot's type*/
} slot_status_res_pl;

/**Get system time response payload*/
typedef struct _sys_time_get_res_pl { 
    bool has_sys_time;
    char sys_time[25]; /**< UTC Date and/or time formatted with a maxiumum length 25 characters. ASCII/UTF-8 encoded: yyyy-mm-dd hh:mm:ss*/
} sys_time_get_res_pl;

/**Get system time response payload*/
typedef struct _sys_time_pps_lock_stat_get_res_pl { 
    bool has_locked;
    bool locked; /**< 1PPS system time lock status*/
} sys_time_pps_lock_stat_get_res_pl;

/**System time offsed to PPS response payload*/
typedef struct _sys_time_pps_offset_get_res_pl { 
    bool has_pps_offset;
    int32_t pps_offset; /**< 1PPS system time lock status*/
} sys_time_pps_offset_get_res_pl;

/**Set system time request payload*/
typedef struct _sys_time_set_req_pl { 
    bool has_sys_time;
    char sys_time[25]; /**< UTC Date and/or time formatted with a maxiumum length 25 characters. Simplistic ISO 8601 ASCII/UTF-8 encoded: yyyy-mm-dd hh:mm:ss dd-mm-yyyy hh:mm:ss in any order, .A '\' can be used as a delimiter for the date as well.*/
} sys_time_set_req_pl;

/**Update progress response payload*/
typedef struct _update_progress_res_pl { 
    bool has_percentage;
    uint32_t percentage; /**< Progress in %*/
    bool has_description;
    char description[80]; /**< Stage description*/
    bool has_update_result;
    int32_t update_result; /**< Result of the update*/
    bool has_last_error;
    char last_error[80]; /**< Last error message*/
} update_progress_res_pl;

/**Bundle info request*/
typedef struct _es_bundle_info_req { 
    request_hdr hdr; /**< Request header*/
    bundle_info_req_pl pl; /**< Request payload*/
} es_bundle_info_req;

/**Bundle info response*/
typedef struct _es_bundle_info_res { 
    response_hdr hdr; /**< Response header*/
    bool has_pl;
    bundle_info_res_pl pl; /**< Response payload*/
} es_bundle_info_res;

/**Bundle install request*/
typedef struct _es_bundle_install_req { 
    request_hdr hdr; /**< Request header*/
    bundle_install_req_pl pl; /**< Request payload*/
} es_bundle_install_req;

/**CSP Get Configuration request*/
typedef struct _es_csp_cfg_get_req { 
    request_hdr hdr; /**< Request header*/
    csp_cfg_get_req_pl pl; /**< Request payload*/
} es_csp_cfg_get_req;

/**CSP Get Configuration Response*/
typedef struct _es_csp_cfg_get_res { 
    response_hdr hdr; /**< Response header*/
    bool has_pl;
    csp_cfg_get_res_pl pl; /**< Response payload*/
} es_csp_cfg_get_res;

/**CSP Configuration Request*/
typedef struct _es_csp_cfg_set_req { 
    request_hdr hdr; /**< Request header*/
    csp_cfg_set_req_pl pl; /**< Request payload*/
} es_csp_cfg_set_req;

/**ESPS Get Configuration request*/
typedef struct _es_esps_cfg_get_req { 
    request_hdr hdr; /**< Request header*/
    esps_cfg_get_req_pl pl; /**< Request payload*/
} es_esps_cfg_get_req;

/**ESPS Get Configuration Response*/
typedef struct _es_esps_cfg_get_res { 
    response_hdr hdr; /**< Response header*/
    bool has_pl;
    esps_cfg_get_res_pl pl; /**< Response payload*/
} es_esps_cfg_get_res;

/**ESPS Configuration Set Request*/
typedef struct _es_esps_cfg_set_req { 
    request_hdr hdr; /**< Request header*/
    esps_cfg_set_req_pl pl; /**< Request payload*/
} es_esps_cfg_set_req;

/**Eth network configuration get request*/
typedef struct _es_eth_cfg_get_req { 
    request_hdr hdr; /**< Request header*/
    eth_cfg_get_req_pl pl; /**< Request payload*/
} es_eth_cfg_get_req;

/**Eth Get Configuration Response*/
typedef struct _es_eth_cfg_get_res { 
    response_hdr hdr; /**< Response header*/
    bool has_pl;
    eth_cfg_get_res_pl pl; /**< Response payload*/
} es_eth_cfg_get_res;

/**Eth Configuration Request*/
typedef struct _es_eth_cfg_set_req { 
    request_hdr hdr; /**< Request header*/
    eth_cfg_set_req_pl pl; /**< Request payload*/
} es_eth_cfg_set_req;

/**Mark a slot response*/
typedef struct _es_get_primary_slot_res { 
    response_hdr hdr; /**< Response header*/
    bool has_pl;
    get_primary_slot_res_pl pl; /**< Response payload*/
} es_get_primary_slot_res;

/**Mark slot request*/
typedef struct _es_mark_slot_req { 
    request_hdr hdr; /**< Request header*/
    mark_slot_req_pl pl; /**< Request payload*/
} es_mark_slot_req;

/**RF board state get response*/
typedef struct _es_rf_board_stat_get_res { 
    response_hdr hdr; /*Response header*/
    rf_board_stat_get_res_pl pl; /*Payload*/
} es_rf_board_stat_get_res;

/**Set RF board state*/
typedef struct _es_rf_board_stat_set_req { 
    request_hdr hdr; /*Request header*/
    rf_board_stat_set_req_pl pl; /*Payload*/
} es_rf_board_stat_set_req;

/**Get RTC time response*/
typedef struct _es_rtc_time_get_res { 
    response_hdr hdr; /*Request header*/
    rtc_time_get_res_pl pl; /*Payload*/
} es_rtc_time_get_res;

/**Slot status request*/
typedef struct _es_slot_status_req { 
    request_hdr hdr; /**< Request header*/
    slot_status_req_pl pl; /**< Request payload*/
} es_slot_status_req;

/**Get slot status response*/
typedef struct _es_slot_status_res { 
    response_hdr hdr; /**< Response header*/
    bool has_pl;
    slot_status_res_pl pl; /**< Response payload*/
} es_slot_status_res;

/**Get system time response*/
typedef struct _es_sys_time_get_res { 
    response_hdr hdr; /*Request header*/
    sys_time_get_res_pl pl; /*Payload*/
} es_sys_time_get_res;

/**System time PPS lock status response*/
typedef struct _es_sys_time_pps_lock_stat_get_res { 
    response_hdr hdr; /*Response header*/
    sys_time_pps_lock_stat_get_res_pl pl; /*Payload*/
} es_sys_time_pps_lock_stat_get_res;

/**System time offset to PPS response*/
typedef struct _es_sys_time_pps_offset_get_res { 
    response_hdr hdr; /*Request header*/
    sys_time_pps_offset_get_res_pl pl; /*Payload*/
} es_sys_time_pps_offset_get_res;

/**Set system time request*/
typedef struct _es_sys_time_set_req { 
    request_hdr hdr; /*Request header*/
    sys_time_set_req_pl pl; /*Payload*/
} es_sys_time_set_req;

/**Update progress response*/
typedef struct _es_update_progress_res { 
    response_hdr hdr; /**< Response header*/
    bool has_pl;
    update_progress_res_pl pl; /**< Response payload*/
} es_update_progress_res;

/**RTC time force sync RPC*/
typedef struct _rtc_time_force_sync_rpc { 
    pb_size_t which_payload;
    union {
        es_rtc_time_force_sync_req req;
        es_rtc_time_force_sync_res res;
    } payload; 
} rtc_time_force_sync_rpc;

/**System halt RPC*/
typedef struct _system_halt_rpc { 
    pb_size_t which_payload;
    union {
        es_system_halt_req req;
        es_system_halt_res res;
    } payload; 
} system_halt_rpc;

/**Provides bundle info*/
typedef struct _bundle_info_rpc { 
    pb_size_t which_payload;
    union {
        es_bundle_info_req req;
        es_bundle_info_res res;
    } payload; 
} bundle_info_rpc;

/**Triggers the installation of a bundle*/
typedef struct _bundle_install_rpc { 
    pb_size_t which_payload;
    union {
        es_bundle_install_req req;
        es_bundle_install_res res;
    } payload; 
} bundle_install_rpc;

/**CSP Configuration get RPC*/
typedef struct _csp_cfg_get_rpc { 
    pb_size_t which_payload;
    union {
        es_csp_cfg_get_req req;
        es_csp_cfg_get_res res;
    } payload; 
} csp_cfg_get_rpc;

/**CSP Configuration set RPC*/
typedef struct _csp_cfg_set_rpc { 
    pb_size_t which_payload;
    union {
        es_csp_cfg_set_req req;
        es_csp_cfg_set_res res;
    } payload; 
} csp_cfg_set_rpc;

/**ESPS Configuration get RPC*/
typedef struct _esps_cfg_get_rpc { 
    pb_size_t which_payload;
    union {
        es_esps_cfg_get_req req;
        es_esps_cfg_get_res res;
    } payload; 
} esps_cfg_get_rpc;

/**ESPS Configuration set RPC*/
typedef struct _esps_cfg_set_rpc { 
    pb_size_t which_payload;
    union {
        es_esps_cfg_set_req req;
        es_esps_cfg_set_res res;
    } payload; 
} esps_cfg_set_rpc;

/**Eth Configuration get RPC*/
typedef struct _eth_cfg_get_rpc { 
    pb_size_t which_payload;
    union {
        es_eth_cfg_get_req req;
        es_eth_cfg_get_res res;
    } payload; 
} eth_cfg_get_rpc;

/**Eth Configuration set RPC*/
typedef struct _eth_cfg_set_rpc { 
    pb_size_t which_payload;
    union {
        es_eth_cfg_set_req req;
        es_eth_cfg_set_res res;
    } payload; 
} eth_cfg_set_rpc;

/**Get current primary slot*/
typedef struct _get_primary_slot_rpc { 
    pb_size_t which_payload;
    union {
        es_get_primary_slot_req req;
        es_get_primary_slot_res res;
    } payload; 
} get_primary_slot_rpc;

/**Mark a slot with a state*/
typedef struct _mark_slot_rpc { 
    pb_size_t which_payload;
    union {
        es_mark_slot_req req;
        es_mark_slot_res res;
    } payload; 
} mark_slot_rpc;

/**RF Board status get RPC*/
typedef struct _rf_board_stat_get_rpc { 
    pb_size_t which_payload;
    union {
        es_rf_board_stat_get_req req;
        es_rf_board_stat_get_res res;
    } payload; 
} rf_board_stat_get_rpc;

/**Set RF board state*/
typedef struct _rf_board_stat_set_rpc { 
    pb_size_t which_payload;
    union {
        es_rf_board_stat_set_req req;
        es_rf_board_stat_set_res res;
    } payload; 
} rf_board_stat_set_rpc;

/**Get RTC time RPC*/
typedef struct _rtc_time_get_rpc { 
    pb_size_t which_payload;
    union {
        es_rtc_time_get_req req;
        es_rtc_time_get_res res;
    } payload; 
} rtc_time_get_rpc;

/**Get slots’s status*/
typedef struct _slot_status_rpc { 
    pb_size_t which_payload;
    union {
        es_slot_status_req req;
        es_slot_status_res res;
    } payload; 
} slot_status_rpc;

/**Get system time RPC*/
typedef struct _sys_time_get_rpc { 
    pb_size_t which_payload;
    union {
        es_sys_time_get_req req;
        es_sys_time_get_res res;
    } payload; 
} sys_time_get_rpc;

/**System time PPS lock status RPC*/
typedef struct _sys_time_pps_lock_stat_get_rpc { 
    pb_size_t which_payload;
    union {
        es_sys_time_pps_lock_stat_get_req req;
        es_sys_time_pps_lock_stat_get_res res;
    } payload; 
} sys_time_pps_lock_stat_get_rpc;

/**System time offset to PPS RPC*/
typedef struct _sys_time_pps_offset_get_rpc { 
    pb_size_t which_payload;
    union {
        es_sys_time_pps_offset_get_req req;
        es_sys_time_pps_offset_get_res res;
    } payload; 
} sys_time_pps_offset_get_rpc;

/**Set system time RPC*/
typedef struct _sys_time_set_rpc { 
    pb_size_t which_payload;
    union {
        es_sys_time_set_req req;
        es_sys_time_set_res res;
    } payload; 
} sys_time_set_rpc;

/**Provides installation progress information*/
typedef struct _update_progress_rpc { 
    pb_size_t which_payload;
    union {
        es_update_progress_req req;
        es_update_progress_res res;
    } payload; 
} update_progress_rpc;

/**ES BoardMgr RPCs*/
typedef struct _es_board_mgr_rpc { 
    pb_size_t which_rpc;
    union {
        eth_cfg_set_rpc eth_cfg_set;
        eth_cfg_get_rpc eth_cfg_get;
        csp_cfg_set_rpc csp_cfg_set;
        csp_cfg_get_rpc csp_cfg_get;
        esps_cfg_set_rpc esps_cfg_set;
        esps_cfg_get_rpc esps_cfg_get;
        bundle_info_rpc bundle_info;
        bundle_install_rpc bundle_install;
        update_progress_rpc update_progress;
        slot_status_rpc slot_status;
        mark_slot_rpc mark_slot;
        get_primary_slot_rpc get_primary_slot;
        sys_time_set_rpc sys_time_set;
        sys_time_get_rpc sys_time_get;
        sys_time_pps_lock_stat_get_rpc sys_time_pps_lock_stat_get;
        sys_time_pps_offset_get_rpc sys_time_pps_offset_get;
        rtc_time_get_rpc rtc_time_get;
        rtc_time_force_sync_rpc rtc_time_force_sync;
        rf_board_stat_set_rpc rf_board_stat_set;
        rf_board_stat_get_rpc rf_board_stat_get;
        system_halt_rpc system_halt;
    } rpc; 
} es_board_mgr_rpc;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define eth_cfg_get_req_pl_init_default          {"eth0"}
#define es_eth_cfg_get_req_init_default          {request_hdr_init_default, eth_cfg_get_req_pl_init_default}
#define eth_cfg_get_res_pl_init_default          {false, "eth0", false, "", false, 0}
#define es_eth_cfg_get_res_init_default          {response_hdr_init_default, false, eth_cfg_get_res_pl_init_default}
#define eth_cfg_get_rpc_init_default             {0, {es_eth_cfg_get_req_init_default}}
#define eth_cfg_set_req_pl_init_default          {"eth0", false, "10.42.0.100", false, 9000u}
#define es_eth_cfg_set_req_init_default          {request_hdr_init_default, eth_cfg_set_req_pl_init_default}
#define es_eth_cfg_set_res_init_default          {response_hdr_init_default}
#define eth_cfg_set_rpc_init_default             {0, {es_eth_cfg_set_req_init_default}}
#define csp_cfg_get_req_pl_init_default          {"uart"}
#define es_csp_cfg_get_req_init_default          {request_hdr_init_default, csp_cfg_get_req_pl_init_default}
#define csp_cfg_get_res_pl_init_default          {false, "", false, 0}
#define es_csp_cfg_get_res_init_default          {response_hdr_init_default, false, csp_cfg_get_res_pl_init_default}
#define csp_cfg_get_rpc_init_default             {0, {es_csp_cfg_get_req_init_default}}
#define csp_cfg_set_req_pl_init_default          {"uart", false, 10u}
#define es_csp_cfg_set_req_init_default          {request_hdr_init_default, csp_cfg_set_req_pl_init_default}
#define es_csp_cfg_set_res_init_default          {response_hdr_init_default}
#define csp_cfg_set_rpc_init_default             {0, {es_csp_cfg_set_req_init_default}}
#define esps_cfg_get_req_pl_init_default         {"esmac_sys1"}
#define es_esps_cfg_get_req_init_default         {request_hdr_init_default, esps_cfg_get_req_pl_init_default}
#define esps_cfg_get_res_pl_init_default         {false, "esmac_sys1", false, 0}
#define es_esps_cfg_get_res_init_default         {response_hdr_init_default, false, esps_cfg_get_res_pl_init_default}
#define esps_cfg_get_rpc_init_default            {0, {es_esps_cfg_get_req_init_default}}
#define esps_cfg_set_req_pl_init_default         {"esmac_sys1", false, 10u}
#define es_esps_cfg_set_req_init_default         {request_hdr_init_default, esps_cfg_set_req_pl_init_default}
#define es_esps_cfg_set_res_init_default         {response_hdr_init_default}
#define esps_cfg_set_rpc_init_default            {0, {es_esps_cfg_set_req_init_default}}
#define bundle_info_req_pl_init_default          {"/data/update.raucb"}
#define es_bundle_info_req_init_default          {request_hdr_init_default, bundle_info_req_pl_init_default}
#define bundle_info_res_pl_init_default          {false, "", false, ""}
#define es_bundle_info_res_init_default          {response_hdr_init_default, false, bundle_info_res_pl_init_default}
#define bundle_info_rpc_init_default             {0, {es_bundle_info_req_init_default}}
#define bundle_install_req_pl_init_default       {"/data/update.raucb"}
#define es_bundle_install_req_init_default       {request_hdr_init_default, bundle_install_req_pl_init_default}
#define es_bundle_install_res_init_default       {response_hdr_init_default}
#define bundle_install_rpc_init_default          {0, {es_bundle_install_req_init_default}}
#define es_update_progress_req_init_default      {request_hdr_init_default}
#define update_progress_res_pl_init_default      {false, 0, false, "", false, 0, false, ""}
#define es_update_progress_res_init_default      {response_hdr_init_default, false, update_progress_res_pl_init_default}
#define update_progress_rpc_init_default         {0, {es_update_progress_req_init_default}}
#define slot_status_req_pl_init_default          {"rootfs.0"}
#define es_slot_status_req_init_default          {request_hdr_init_default, slot_status_req_pl_init_default}
#define slot_status_res_pl_init_default          {false, 0, false, "", false, "", false, "", false, "", false, "", false, "", false, "", false, "", false, "", false, 0, false, "", false, "", false, 0, false, "", false, "", false, ""}
#define es_slot_status_res_init_default          {response_hdr_init_default, false, slot_status_res_pl_init_default}
#define slot_status_rpc_init_default             {0, {es_slot_status_req_init_default}}
#define mark_slot_req_pl_init_default            {"rootfs.0", "good"}
#define es_mark_slot_req_init_default            {request_hdr_init_default, mark_slot_req_pl_init_default}
#define es_mark_slot_res_init_default            {response_hdr_init_default}
#define mark_slot_rpc_init_default               {0, {es_mark_slot_req_init_default}}
#define es_get_primary_slot_req_init_default     {request_hdr_init_default}
#define get_primary_slot_res_pl_init_default     {""}
#define es_get_primary_slot_res_init_default     {response_hdr_init_default, false, get_primary_slot_res_pl_init_default}
#define get_primary_slot_rpc_init_default        {0, {es_get_primary_slot_req_init_default}}
#define sys_time_set_rpc_init_default            {0, {es_sys_time_set_req_init_default}}
#define es_sys_time_set_req_init_default         {request_hdr_init_default, sys_time_set_req_pl_init_default}
#define sys_time_set_req_pl_init_default         {false, "N/A"}
#define es_sys_time_set_res_init_default         {response_hdr_init_default}
#define sys_time_get_rpc_init_default            {0, {es_sys_time_get_req_init_default}}
#define es_sys_time_get_req_init_default         {request_hdr_init_default}
#define es_sys_time_get_res_init_default         {response_hdr_init_default, sys_time_get_res_pl_init_default}
#define sys_time_get_res_pl_init_default         {false, ""}
#define sys_time_pps_lock_stat_get_rpc_init_default {0, {es_sys_time_pps_lock_stat_get_req_init_default}}
#define es_sys_time_pps_lock_stat_get_req_init_default {request_hdr_init_default}
#define es_sys_time_pps_lock_stat_get_res_init_default {response_hdr_init_default, sys_time_pps_lock_stat_get_res_pl_init_default}
#define sys_time_pps_lock_stat_get_res_pl_init_default {false, 0}
#define sys_time_pps_offset_get_rpc_init_default {0, {es_sys_time_pps_offset_get_req_init_default}}
#define es_sys_time_pps_offset_get_req_init_default {request_hdr_init_default}
#define es_sys_time_pps_offset_get_res_init_default {response_hdr_init_default, sys_time_pps_offset_get_res_pl_init_default}
#define sys_time_pps_offset_get_res_pl_init_default {false, 0}
#define rtc_time_get_rpc_init_default            {0, {es_rtc_time_get_req_init_default}}
#define es_rtc_time_get_req_init_default         {request_hdr_init_default}
#define es_rtc_time_get_res_init_default         {response_hdr_init_default, rtc_time_get_res_pl_init_default}
#define rtc_time_get_res_pl_init_default         {false, ""}
#define rtc_time_force_sync_rpc_init_default     {0, {es_rtc_time_force_sync_req_init_default}}
#define es_rtc_time_force_sync_req_init_default  {request_hdr_init_default}
#define es_rtc_time_force_sync_res_init_default  {response_hdr_init_default}
#define rf_board_stat_set_rpc_init_default       {0, {es_rf_board_stat_set_req_init_default}}
#define es_rf_board_stat_set_req_init_default    {request_hdr_init_default, rf_board_stat_set_req_pl_init_default}
#define rf_board_stat_set_req_pl_init_default    {false, false}
#define es_rf_board_stat_set_res_init_default    {response_hdr_init_default}
#define rf_board_stat_get_rpc_init_default       {0, {es_rf_board_stat_get_req_init_default}}
#define es_rf_board_stat_get_req_init_default    {request_hdr_init_default}
#define es_rf_board_stat_get_res_init_default    {response_hdr_init_default, rf_board_stat_get_res_pl_init_default}
#define system_halt_rpc_init_default             {0, {es_system_halt_req_init_default}}
#define es_system_halt_req_init_default          {request_hdr_init_default}
#define es_system_halt_res_init_default          {response_hdr_init_default}
#define rf_board_stat_get_res_pl_init_default    {false, 0, false, "", false, 0, false, 0}
#define es_board_mgr_rpc_init_default            {0, {eth_cfg_set_rpc_init_default}}
#define eth_cfg_get_req_pl_init_zero             {""}
#define es_eth_cfg_get_req_init_zero             {request_hdr_init_zero, eth_cfg_get_req_pl_init_zero}
#define eth_cfg_get_res_pl_init_zero             {false, "", false, "", false, 0}
#define es_eth_cfg_get_res_init_zero             {response_hdr_init_zero, false, eth_cfg_get_res_pl_init_zero}
#define eth_cfg_get_rpc_init_zero                {0, {es_eth_cfg_get_req_init_zero}}
#define eth_cfg_set_req_pl_init_zero             {"", false, "", false, 0}
#define es_eth_cfg_set_req_init_zero             {request_hdr_init_zero, eth_cfg_set_req_pl_init_zero}
#define es_eth_cfg_set_res_init_zero             {response_hdr_init_zero}
#define eth_cfg_set_rpc_init_zero                {0, {es_eth_cfg_set_req_init_zero}}
#define csp_cfg_get_req_pl_init_zero             {""}
#define es_csp_cfg_get_req_init_zero             {request_hdr_init_zero, csp_cfg_get_req_pl_init_zero}
#define csp_cfg_get_res_pl_init_zero             {false, "", false, 0}
#define es_csp_cfg_get_res_init_zero             {response_hdr_init_zero, false, csp_cfg_get_res_pl_init_zero}
#define csp_cfg_get_rpc_init_zero                {0, {es_csp_cfg_get_req_init_zero}}
#define csp_cfg_set_req_pl_init_zero             {"", false, 0}
#define es_csp_cfg_set_req_init_zero             {request_hdr_init_zero, csp_cfg_set_req_pl_init_zero}
#define es_csp_cfg_set_res_init_zero             {response_hdr_init_zero}
#define csp_cfg_set_rpc_init_zero                {0, {es_csp_cfg_set_req_init_zero}}
#define esps_cfg_get_req_pl_init_zero            {""}
#define es_esps_cfg_get_req_init_zero            {request_hdr_init_zero, esps_cfg_get_req_pl_init_zero}
#define esps_cfg_get_res_pl_init_zero            {false, "", false, 0}
#define es_esps_cfg_get_res_init_zero            {response_hdr_init_zero, false, esps_cfg_get_res_pl_init_zero}
#define esps_cfg_get_rpc_init_zero               {0, {es_esps_cfg_get_req_init_zero}}
#define esps_cfg_set_req_pl_init_zero            {"", false, 0}
#define es_esps_cfg_set_req_init_zero            {request_hdr_init_zero, esps_cfg_set_req_pl_init_zero}
#define es_esps_cfg_set_res_init_zero            {response_hdr_init_zero}
#define esps_cfg_set_rpc_init_zero               {0, {es_esps_cfg_set_req_init_zero}}
#define bundle_info_req_pl_init_zero             {""}
#define es_bundle_info_req_init_zero             {request_hdr_init_zero, bundle_info_req_pl_init_zero}
#define bundle_info_res_pl_init_zero             {false, "", false, ""}
#define es_bundle_info_res_init_zero             {response_hdr_init_zero, false, bundle_info_res_pl_init_zero}
#define bundle_info_rpc_init_zero                {0, {es_bundle_info_req_init_zero}}
#define bundle_install_req_pl_init_zero          {""}
#define es_bundle_install_req_init_zero          {request_hdr_init_zero, bundle_install_req_pl_init_zero}
#define es_bundle_install_res_init_zero          {response_hdr_init_zero}
#define bundle_install_rpc_init_zero             {0, {es_bundle_install_req_init_zero}}
#define es_update_progress_req_init_zero         {request_hdr_init_zero}
#define update_progress_res_pl_init_zero         {false, 0, false, "", false, 0, false, ""}
#define es_update_progress_res_init_zero         {response_hdr_init_zero, false, update_progress_res_pl_init_zero}
#define update_progress_rpc_init_zero            {0, {es_update_progress_req_init_zero}}
#define slot_status_req_pl_init_zero             {""}
#define es_slot_status_req_init_zero             {request_hdr_init_zero, slot_status_req_pl_init_zero}
#define slot_status_res_pl_init_zero             {false, 0, false, "", false, "", false, "", false, "", false, "", false, "", false, "", false, "", false, "", false, 0, false, "", false, "", false, 0, false, "", false, "", false, ""}
#define es_slot_status_res_init_zero             {response_hdr_init_zero, false, slot_status_res_pl_init_zero}
#define slot_status_rpc_init_zero                {0, {es_slot_status_req_init_zero}}
#define mark_slot_req_pl_init_zero               {"", ""}
#define es_mark_slot_req_init_zero               {request_hdr_init_zero, mark_slot_req_pl_init_zero}
#define es_mark_slot_res_init_zero               {response_hdr_init_zero}
#define mark_slot_rpc_init_zero                  {0, {es_mark_slot_req_init_zero}}
#define es_get_primary_slot_req_init_zero        {request_hdr_init_zero}
#define get_primary_slot_res_pl_init_zero        {""}
#define es_get_primary_slot_res_init_zero        {response_hdr_init_zero, false, get_primary_slot_res_pl_init_zero}
#define get_primary_slot_rpc_init_zero           {0, {es_get_primary_slot_req_init_zero}}
#define sys_time_set_rpc_init_zero               {0, {es_sys_time_set_req_init_zero}}
#define es_sys_time_set_req_init_zero            {request_hdr_init_zero, sys_time_set_req_pl_init_zero}
#define sys_time_set_req_pl_init_zero            {false, ""}
#define es_sys_time_set_res_init_zero            {response_hdr_init_zero}
#define sys_time_get_rpc_init_zero               {0, {es_sys_time_get_req_init_zero}}
#define es_sys_time_get_req_init_zero            {request_hdr_init_zero}
#define es_sys_time_get_res_init_zero            {response_hdr_init_zero, sys_time_get_res_pl_init_zero}
#define sys_time_get_res_pl_init_zero            {false, ""}
#define sys_time_pps_lock_stat_get_rpc_init_zero {0, {es_sys_time_pps_lock_stat_get_req_init_zero}}
#define es_sys_time_pps_lock_stat_get_req_init_zero {request_hdr_init_zero}
#define es_sys_time_pps_lock_stat_get_res_init_zero {response_hdr_init_zero, sys_time_pps_lock_stat_get_res_pl_init_zero}
#define sys_time_pps_lock_stat_get_res_pl_init_zero {false, 0}
#define sys_time_pps_offset_get_rpc_init_zero    {0, {es_sys_time_pps_offset_get_req_init_zero}}
#define es_sys_time_pps_offset_get_req_init_zero {request_hdr_init_zero}
#define es_sys_time_pps_offset_get_res_init_zero {response_hdr_init_zero, sys_time_pps_offset_get_res_pl_init_zero}
#define sys_time_pps_offset_get_res_pl_init_zero {false, 0}
#define rtc_time_get_rpc_init_zero               {0, {es_rtc_time_get_req_init_zero}}
#define es_rtc_time_get_req_init_zero            {request_hdr_init_zero}
#define es_rtc_time_get_res_init_zero            {response_hdr_init_zero, rtc_time_get_res_pl_init_zero}
#define rtc_time_get_res_pl_init_zero            {false, ""}
#define rtc_time_force_sync_rpc_init_zero        {0, {es_rtc_time_force_sync_req_init_zero}}
#define es_rtc_time_force_sync_req_init_zero     {request_hdr_init_zero}
#define es_rtc_time_force_sync_res_init_zero     {response_hdr_init_zero}
#define rf_board_stat_set_rpc_init_zero          {0, {es_rf_board_stat_set_req_init_zero}}
#define es_rf_board_stat_set_req_init_zero       {request_hdr_init_zero, rf_board_stat_set_req_pl_init_zero}
#define rf_board_stat_set_req_pl_init_zero       {false, 0}
#define es_rf_board_stat_set_res_init_zero       {response_hdr_init_zero}
#define rf_board_stat_get_rpc_init_zero          {0, {es_rf_board_stat_get_req_init_zero}}
#define es_rf_board_stat_get_req_init_zero       {request_hdr_init_zero}
#define es_rf_board_stat_get_res_init_zero       {response_hdr_init_zero, rf_board_stat_get_res_pl_init_zero}
#define system_halt_rpc_init_zero                {0, {es_system_halt_req_init_zero}}
#define es_system_halt_req_init_zero             {request_hdr_init_zero}
#define es_system_halt_res_init_zero             {response_hdr_init_zero}
#define rf_board_stat_get_res_pl_init_zero       {false, 0, false, "", false, 0, false, 0}
#define es_board_mgr_rpc_init_zero               {0, {eth_cfg_set_rpc_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define bundle_info_req_pl_bundle_path_tag       1
#define bundle_info_res_pl_compatible_tag        1
#define bundle_info_res_pl_ver_tag               2
#define bundle_install_req_pl_bundle_path_tag    1
#define csp_cfg_get_req_pl_iface_tag             1
#define csp_cfg_get_res_pl_iface_tag             1
#define csp_cfg_get_res_pl_address_tag           2
#define csp_cfg_set_req_pl_iface_tag             1
#define csp_cfg_set_req_pl_address_tag           2
#define es_bundle_install_res_hdr_tag            1
#define es_csp_cfg_set_res_hdr_tag               1
#define es_esps_cfg_set_res_hdr_tag              1
#define es_eth_cfg_set_res_hdr_tag               1
#define es_get_primary_slot_req_hdr_tag          1
#define es_mark_slot_res_hdr_tag                 1
#define es_rf_board_stat_get_req_hdr_tag         1
#define es_rf_board_stat_set_res_hdr_tag         1
#define es_rtc_time_force_sync_req_hdr_tag       1
#define es_rtc_time_force_sync_res_hdr_tag       1
#define es_rtc_time_get_req_hdr_tag              1
#define es_sys_time_get_req_hdr_tag              1
#define es_sys_time_pps_lock_stat_get_req_hdr_tag 1
#define es_sys_time_pps_offset_get_req_hdr_tag   1
#define es_sys_time_set_res_hdr_tag              1
#define es_system_halt_req_hdr_tag               1
#define es_system_halt_res_hdr_tag               1
#define es_update_progress_req_hdr_tag           1
#define esps_cfg_get_req_pl_iface_tag            1
#define esps_cfg_get_res_pl_iface_tag            1
#define esps_cfg_get_res_pl_address_tag          2
#define esps_cfg_set_req_pl_iface_tag            1
#define esps_cfg_set_req_pl_address_tag          2
#define eth_cfg_get_req_pl_iface_tag             1
#define eth_cfg_get_res_pl_iface_tag             1
#define eth_cfg_get_res_pl_ipv4_tag              2
#define eth_cfg_get_res_pl_mtu_tag               3
#define eth_cfg_set_req_pl_iface_tag             1
#define eth_cfg_set_req_pl_ipv4_tag              2
#define eth_cfg_set_req_pl_mtu_tag               3
#define get_primary_slot_res_pl_slot_tag         1
#define mark_slot_req_pl_slot_tag                1
#define mark_slot_req_pl_slot_state_tag          2
#define rf_board_stat_get_res_pl_enabled_tag     1
#define rf_board_stat_get_res_pl_jesd204_fsm_state_tag 2
#define rf_board_stat_get_res_pl_jesd204_fsm_error_tag 3
#define rf_board_stat_get_res_pl_jesd204_fsm_paused_tag 4
#define rf_board_stat_set_req_pl_enabled_tag     1
#define rtc_time_get_res_pl_rtc_time_tag         1
#define slot_status_req_pl_slot_tag              1
#define slot_status_res_pl_activated_count_tag   1
#define slot_status_res_pl_activated_timestamp_tag 2
#define slot_status_res_pl_boot_status_tag       3
#define slot_status_res_pl_bootname_tag          4
#define slot_status_res_pl_bundle_build_tag      5
#define slot_status_res_pl_bundle_compatible_tag 6
#define slot_status_res_pl_bundle_description_tag 7
#define slot_status_res_pl_bundle_ver_tag        8
#define slot_status_res_pl_slot_cl_tag           9
#define slot_status_res_pl_device_tag            10
#define slot_status_res_pl_installed_count_tag   11
#define slot_status_res_pl_installed_timestamp_tag 12
#define slot_status_res_pl_sha256_tag            13
#define slot_status_res_pl_size_tag              14
#define slot_status_res_pl_slot_state_tag        15
#define slot_status_res_pl_status_tag            16
#define slot_status_res_pl_type_tag              17
#define sys_time_get_res_pl_sys_time_tag         1
#define sys_time_pps_lock_stat_get_res_pl_locked_tag 1
#define sys_time_pps_offset_get_res_pl_pps_offset_tag 1
#define sys_time_set_req_pl_sys_time_tag         1
#define update_progress_res_pl_percentage_tag    1
#define update_progress_res_pl_description_tag   2
#define update_progress_res_pl_update_result_tag 3
#define update_progress_res_pl_last_error_tag    4
#define es_bundle_info_req_hdr_tag               1
#define es_bundle_info_req_pl_tag                2
#define es_bundle_info_res_hdr_tag               1
#define es_bundle_info_res_pl_tag                2
#define es_bundle_install_req_hdr_tag            1
#define es_bundle_install_req_pl_tag             2
#define es_csp_cfg_get_req_hdr_tag               1
#define es_csp_cfg_get_req_pl_tag                2
#define es_csp_cfg_get_res_hdr_tag               1
#define es_csp_cfg_get_res_pl_tag                2
#define es_csp_cfg_set_req_hdr_tag               1
#define es_csp_cfg_set_req_pl_tag                2
#define es_esps_cfg_get_req_hdr_tag              1
#define es_esps_cfg_get_req_pl_tag               2
#define es_esps_cfg_get_res_hdr_tag              1
#define es_esps_cfg_get_res_pl_tag               2
#define es_esps_cfg_set_req_hdr_tag              1
#define es_esps_cfg_set_req_pl_tag               2
#define es_eth_cfg_get_req_hdr_tag               1
#define es_eth_cfg_get_req_pl_tag                2
#define es_eth_cfg_get_res_hdr_tag               1
#define es_eth_cfg_get_res_pl_tag                2
#define es_eth_cfg_set_req_hdr_tag               1
#define es_eth_cfg_set_req_pl_tag                2
#define es_get_primary_slot_res_hdr_tag          1
#define es_get_primary_slot_res_pl_tag           2
#define es_mark_slot_req_hdr_tag                 1
#define es_mark_slot_req_pl_tag                  2
#define es_rf_board_stat_get_res_hdr_tag         1
#define es_rf_board_stat_get_res_pl_tag          2
#define es_rf_board_stat_set_req_hdr_tag         1
#define es_rf_board_stat_set_req_pl_tag          2
#define es_rtc_time_get_res_hdr_tag              1
#define es_rtc_time_get_res_pl_tag               2
#define es_slot_status_req_hdr_tag               1
#define es_slot_status_req_pl_tag                2
#define es_slot_status_res_hdr_tag               1
#define es_slot_status_res_pl_tag                2
#define es_sys_time_get_res_hdr_tag              1
#define es_sys_time_get_res_pl_tag               2
#define es_sys_time_pps_lock_stat_get_res_hdr_tag 1
#define es_sys_time_pps_lock_stat_get_res_pl_tag 2
#define es_sys_time_pps_offset_get_res_hdr_tag   1
#define es_sys_time_pps_offset_get_res_pl_tag    2
#define es_sys_time_set_req_hdr_tag              1
#define es_sys_time_set_req_pl_tag               2
#define es_update_progress_res_hdr_tag           1
#define es_update_progress_res_pl_tag            2
#define rtc_time_force_sync_rpc_req_tag          1
#define rtc_time_force_sync_rpc_res_tag          2
#define system_halt_rpc_req_tag                  1
#define system_halt_rpc_res_tag                  2
#define bundle_info_rpc_req_tag                  1
#define bundle_info_rpc_res_tag                  2
#define bundle_install_rpc_req_tag               1
#define bundle_install_rpc_res_tag               2
#define csp_cfg_get_rpc_req_tag                  1
#define csp_cfg_get_rpc_res_tag                  2
#define csp_cfg_set_rpc_req_tag                  1
#define csp_cfg_set_rpc_res_tag                  2
#define esps_cfg_get_rpc_req_tag                 1
#define esps_cfg_get_rpc_res_tag                 2
#define esps_cfg_set_rpc_req_tag                 1
#define esps_cfg_set_rpc_res_tag                 2
#define eth_cfg_get_rpc_req_tag                  1
#define eth_cfg_get_rpc_res_tag                  2
#define eth_cfg_set_rpc_req_tag                  1
#define eth_cfg_set_rpc_res_tag                  2
#define get_primary_slot_rpc_req_tag             1
#define get_primary_slot_rpc_res_tag             2
#define mark_slot_rpc_req_tag                    1
#define mark_slot_rpc_res_tag                    2
#define rf_board_stat_get_rpc_req_tag            1
#define rf_board_stat_get_rpc_res_tag            2
#define rf_board_stat_set_rpc_req_tag            1
#define rf_board_stat_set_rpc_res_tag            2
#define rtc_time_get_rpc_req_tag                 1
#define rtc_time_get_rpc_res_tag                 2
#define slot_status_rpc_req_tag                  1
#define slot_status_rpc_res_tag                  2
#define sys_time_get_rpc_req_tag                 1
#define sys_time_get_rpc_res_tag                 2
#define sys_time_pps_lock_stat_get_rpc_req_tag   1
#define sys_time_pps_lock_stat_get_rpc_res_tag   2
#define sys_time_pps_offset_get_rpc_req_tag      1
#define sys_time_pps_offset_get_rpc_res_tag      2
#define sys_time_set_rpc_req_tag                 1
#define sys_time_set_rpc_res_tag                 2
#define update_progress_rpc_req_tag              1
#define update_progress_rpc_res_tag              2
#define es_board_mgr_rpc_eth_cfg_set_tag         1
#define es_board_mgr_rpc_eth_cfg_get_tag         2
#define es_board_mgr_rpc_csp_cfg_set_tag         3
#define es_board_mgr_rpc_csp_cfg_get_tag         4
#define es_board_mgr_rpc_esps_cfg_set_tag        5
#define es_board_mgr_rpc_esps_cfg_get_tag        6
#define es_board_mgr_rpc_bundle_info_tag         7
#define es_board_mgr_rpc_bundle_install_tag      8
#define es_board_mgr_rpc_update_progress_tag     9
#define es_board_mgr_rpc_slot_status_tag         10
#define es_board_mgr_rpc_mark_slot_tag           11
#define es_board_mgr_rpc_get_primary_slot_tag    12
#define es_board_mgr_rpc_sys_time_set_tag        13
#define es_board_mgr_rpc_sys_time_get_tag        14
#define es_board_mgr_rpc_sys_time_pps_lock_stat_get_tag 15
#define es_board_mgr_rpc_sys_time_pps_offset_get_tag 16
#define es_board_mgr_rpc_rtc_time_get_tag        17
#define es_board_mgr_rpc_rtc_time_force_sync_tag 18
#define es_board_mgr_rpc_rf_board_stat_set_tag   19
#define es_board_mgr_rpc_rf_board_stat_get_tag   20
#define es_board_mgr_rpc_system_halt_tag         21

/* Struct field encoding specification for nanopb */
#define eth_cfg_get_req_pl_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   iface,             1)
#define eth_cfg_get_req_pl_CALLBACK NULL
#define eth_cfg_get_req_pl_DEFAULT (const pb_byte_t*)"\x0a\x04\x65\x74\x68\x30\x00"

#define es_eth_cfg_get_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_eth_cfg_get_req_CALLBACK NULL
#define es_eth_cfg_get_req_DEFAULT NULL
#define es_eth_cfg_get_req_hdr_MSGTYPE request_hdr
#define es_eth_cfg_get_req_pl_MSGTYPE eth_cfg_get_req_pl

#define eth_cfg_get_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   iface,             1) \
X(a, STATIC,   OPTIONAL, STRING,   ipv4,              2) \
X(a, STATIC,   OPTIONAL, UINT32,   mtu,               3)
#define eth_cfg_get_res_pl_CALLBACK NULL
#define eth_cfg_get_res_pl_DEFAULT (const pb_byte_t*)"\x0a\x04\x65\x74\x68\x30\x00"

#define es_eth_cfg_get_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pl,                2)
#define es_eth_cfg_get_res_CALLBACK NULL
#define es_eth_cfg_get_res_DEFAULT NULL
#define es_eth_cfg_get_res_hdr_MSGTYPE response_hdr
#define es_eth_cfg_get_res_pl_MSGTYPE eth_cfg_get_res_pl

#define eth_cfg_get_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define eth_cfg_get_rpc_CALLBACK NULL
#define eth_cfg_get_rpc_DEFAULT NULL
#define eth_cfg_get_rpc_payload_req_MSGTYPE es_eth_cfg_get_req
#define eth_cfg_get_rpc_payload_res_MSGTYPE es_eth_cfg_get_res

#define eth_cfg_set_req_pl_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   iface,             1) \
X(a, STATIC,   OPTIONAL, STRING,   ipv4,              2) \
X(a, STATIC,   OPTIONAL, UINT32,   mtu,               3)
#define eth_cfg_set_req_pl_CALLBACK NULL
#define eth_cfg_set_req_pl_DEFAULT (const pb_byte_t*)"\x0a\x04\x65\x74\x68\x30\x12\x0b\x31\x30\x2e\x34\x32\x2e\x30\x2e\x31\x30\x30\x18\xa8\x46\x00"

#define es_eth_cfg_set_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_eth_cfg_set_req_CALLBACK NULL
#define es_eth_cfg_set_req_DEFAULT NULL
#define es_eth_cfg_set_req_hdr_MSGTYPE request_hdr
#define es_eth_cfg_set_req_pl_MSGTYPE eth_cfg_set_req_pl

#define es_eth_cfg_set_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_eth_cfg_set_res_CALLBACK NULL
#define es_eth_cfg_set_res_DEFAULT NULL
#define es_eth_cfg_set_res_hdr_MSGTYPE response_hdr

#define eth_cfg_set_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define eth_cfg_set_rpc_CALLBACK NULL
#define eth_cfg_set_rpc_DEFAULT NULL
#define eth_cfg_set_rpc_payload_req_MSGTYPE es_eth_cfg_set_req
#define eth_cfg_set_rpc_payload_res_MSGTYPE es_eth_cfg_set_res

#define csp_cfg_get_req_pl_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   iface,             1)
#define csp_cfg_get_req_pl_CALLBACK NULL
#define csp_cfg_get_req_pl_DEFAULT (const pb_byte_t*)"\x0a\x04\x75\x61\x72\x74\x00"

#define es_csp_cfg_get_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_csp_cfg_get_req_CALLBACK NULL
#define es_csp_cfg_get_req_DEFAULT NULL
#define es_csp_cfg_get_req_hdr_MSGTYPE request_hdr
#define es_csp_cfg_get_req_pl_MSGTYPE csp_cfg_get_req_pl

#define csp_cfg_get_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   iface,             1) \
X(a, STATIC,   OPTIONAL, UINT32,   address,           2)
#define csp_cfg_get_res_pl_CALLBACK NULL
#define csp_cfg_get_res_pl_DEFAULT NULL

#define es_csp_cfg_get_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pl,                2)
#define es_csp_cfg_get_res_CALLBACK NULL
#define es_csp_cfg_get_res_DEFAULT NULL
#define es_csp_cfg_get_res_hdr_MSGTYPE response_hdr
#define es_csp_cfg_get_res_pl_MSGTYPE csp_cfg_get_res_pl

#define csp_cfg_get_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define csp_cfg_get_rpc_CALLBACK NULL
#define csp_cfg_get_rpc_DEFAULT NULL
#define csp_cfg_get_rpc_payload_req_MSGTYPE es_csp_cfg_get_req
#define csp_cfg_get_rpc_payload_res_MSGTYPE es_csp_cfg_get_res

#define csp_cfg_set_req_pl_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   iface,             1) \
X(a, STATIC,   OPTIONAL, UINT32,   address,           2)
#define csp_cfg_set_req_pl_CALLBACK NULL
#define csp_cfg_set_req_pl_DEFAULT (const pb_byte_t*)"\x0a\x04\x75\x61\x72\x74\x10\x0a\x00"

#define es_csp_cfg_set_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_csp_cfg_set_req_CALLBACK NULL
#define es_csp_cfg_set_req_DEFAULT NULL
#define es_csp_cfg_set_req_hdr_MSGTYPE request_hdr
#define es_csp_cfg_set_req_pl_MSGTYPE csp_cfg_set_req_pl

#define es_csp_cfg_set_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_csp_cfg_set_res_CALLBACK NULL
#define es_csp_cfg_set_res_DEFAULT NULL
#define es_csp_cfg_set_res_hdr_MSGTYPE response_hdr

#define csp_cfg_set_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define csp_cfg_set_rpc_CALLBACK NULL
#define csp_cfg_set_rpc_DEFAULT NULL
#define csp_cfg_set_rpc_payload_req_MSGTYPE es_csp_cfg_set_req
#define csp_cfg_set_rpc_payload_res_MSGTYPE es_csp_cfg_set_res

#define esps_cfg_get_req_pl_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   iface,             1)
#define esps_cfg_get_req_pl_CALLBACK NULL
#define esps_cfg_get_req_pl_DEFAULT (const pb_byte_t*)"\x0a\x0a\x65\x73\x6d\x61\x63\x5f\x73\x79\x73\x31\x00"

#define es_esps_cfg_get_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_esps_cfg_get_req_CALLBACK NULL
#define es_esps_cfg_get_req_DEFAULT NULL
#define es_esps_cfg_get_req_hdr_MSGTYPE request_hdr
#define es_esps_cfg_get_req_pl_MSGTYPE esps_cfg_get_req_pl

#define esps_cfg_get_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   iface,             1) \
X(a, STATIC,   OPTIONAL, UINT32,   address,           2)
#define esps_cfg_get_res_pl_CALLBACK NULL
#define esps_cfg_get_res_pl_DEFAULT (const pb_byte_t*)"\x0a\x0a\x65\x73\x6d\x61\x63\x5f\x73\x79\x73\x31\x00"

#define es_esps_cfg_get_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pl,                2)
#define es_esps_cfg_get_res_CALLBACK NULL
#define es_esps_cfg_get_res_DEFAULT NULL
#define es_esps_cfg_get_res_hdr_MSGTYPE response_hdr
#define es_esps_cfg_get_res_pl_MSGTYPE esps_cfg_get_res_pl

#define esps_cfg_get_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define esps_cfg_get_rpc_CALLBACK NULL
#define esps_cfg_get_rpc_DEFAULT NULL
#define esps_cfg_get_rpc_payload_req_MSGTYPE es_esps_cfg_get_req
#define esps_cfg_get_rpc_payload_res_MSGTYPE es_esps_cfg_get_res

#define esps_cfg_set_req_pl_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   iface,             1) \
X(a, STATIC,   OPTIONAL, UINT32,   address,           2)
#define esps_cfg_set_req_pl_CALLBACK NULL
#define esps_cfg_set_req_pl_DEFAULT (const pb_byte_t*)"\x0a\x0a\x65\x73\x6d\x61\x63\x5f\x73\x79\x73\x31\x10\x0a\x00"

#define es_esps_cfg_set_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_esps_cfg_set_req_CALLBACK NULL
#define es_esps_cfg_set_req_DEFAULT NULL
#define es_esps_cfg_set_req_hdr_MSGTYPE request_hdr
#define es_esps_cfg_set_req_pl_MSGTYPE esps_cfg_set_req_pl

#define es_esps_cfg_set_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_esps_cfg_set_res_CALLBACK NULL
#define es_esps_cfg_set_res_DEFAULT NULL
#define es_esps_cfg_set_res_hdr_MSGTYPE response_hdr

#define esps_cfg_set_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define esps_cfg_set_rpc_CALLBACK NULL
#define esps_cfg_set_rpc_DEFAULT NULL
#define esps_cfg_set_rpc_payload_req_MSGTYPE es_esps_cfg_set_req
#define esps_cfg_set_rpc_payload_res_MSGTYPE es_esps_cfg_set_res

#define bundle_info_req_pl_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   bundle_path,       1)
#define bundle_info_req_pl_CALLBACK NULL
#define bundle_info_req_pl_DEFAULT (const pb_byte_t*)"\x0a\x12\x2f\x64\x61\x74\x61\x2f\x75\x70\x64\x61\x74\x65\x2e\x72\x61\x75\x63\x62\x00"

#define es_bundle_info_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_bundle_info_req_CALLBACK NULL
#define es_bundle_info_req_DEFAULT NULL
#define es_bundle_info_req_hdr_MSGTYPE request_hdr
#define es_bundle_info_req_pl_MSGTYPE bundle_info_req_pl

#define bundle_info_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   compatible,        1) \
X(a, STATIC,   OPTIONAL, STRING,   ver,               2)
#define bundle_info_res_pl_CALLBACK NULL
#define bundle_info_res_pl_DEFAULT (const pb_byte_t*)"\x0a\x00\x12\x00\x00"

#define es_bundle_info_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pl,                2)
#define es_bundle_info_res_CALLBACK NULL
#define es_bundle_info_res_DEFAULT NULL
#define es_bundle_info_res_hdr_MSGTYPE response_hdr
#define es_bundle_info_res_pl_MSGTYPE bundle_info_res_pl

#define bundle_info_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define bundle_info_rpc_CALLBACK NULL
#define bundle_info_rpc_DEFAULT NULL
#define bundle_info_rpc_payload_req_MSGTYPE es_bundle_info_req
#define bundle_info_rpc_payload_res_MSGTYPE es_bundle_info_res

#define bundle_install_req_pl_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   bundle_path,       1)
#define bundle_install_req_pl_CALLBACK NULL
#define bundle_install_req_pl_DEFAULT (const pb_byte_t*)"\x0a\x12\x2f\x64\x61\x74\x61\x2f\x75\x70\x64\x61\x74\x65\x2e\x72\x61\x75\x63\x62\x00"

#define es_bundle_install_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_bundle_install_req_CALLBACK NULL
#define es_bundle_install_req_DEFAULT NULL
#define es_bundle_install_req_hdr_MSGTYPE request_hdr
#define es_bundle_install_req_pl_MSGTYPE bundle_install_req_pl

#define es_bundle_install_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_bundle_install_res_CALLBACK NULL
#define es_bundle_install_res_DEFAULT NULL
#define es_bundle_install_res_hdr_MSGTYPE response_hdr

#define bundle_install_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define bundle_install_rpc_CALLBACK NULL
#define bundle_install_rpc_DEFAULT NULL
#define bundle_install_rpc_payload_req_MSGTYPE es_bundle_install_req
#define bundle_install_rpc_payload_res_MSGTYPE es_bundle_install_res

#define es_update_progress_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_update_progress_req_CALLBACK NULL
#define es_update_progress_req_DEFAULT NULL
#define es_update_progress_req_hdr_MSGTYPE request_hdr

#define update_progress_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   percentage,        1) \
X(a, STATIC,   OPTIONAL, STRING,   description,       2) \
X(a, STATIC,   OPTIONAL, INT32,    update_result,     3) \
X(a, STATIC,   OPTIONAL, STRING,   last_error,        4)
#define update_progress_res_pl_CALLBACK NULL
#define update_progress_res_pl_DEFAULT NULL

#define es_update_progress_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pl,                2)
#define es_update_progress_res_CALLBACK NULL
#define es_update_progress_res_DEFAULT NULL
#define es_update_progress_res_hdr_MSGTYPE response_hdr
#define es_update_progress_res_pl_MSGTYPE update_progress_res_pl

#define update_progress_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define update_progress_rpc_CALLBACK NULL
#define update_progress_rpc_DEFAULT NULL
#define update_progress_rpc_payload_req_MSGTYPE es_update_progress_req
#define update_progress_rpc_payload_res_MSGTYPE es_update_progress_res

#define slot_status_req_pl_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   slot,              1)
#define slot_status_req_pl_CALLBACK NULL
#define slot_status_req_pl_DEFAULT (const pb_byte_t*)"\x0a\x08\x72\x6f\x6f\x74\x66\x73\x2e\x30\x00"

#define es_slot_status_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_slot_status_req_CALLBACK NULL
#define es_slot_status_req_DEFAULT NULL
#define es_slot_status_req_hdr_MSGTYPE request_hdr
#define es_slot_status_req_pl_MSGTYPE slot_status_req_pl

#define slot_status_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   activated_count,   1) \
X(a, STATIC,   OPTIONAL, STRING,   activated_timestamp,   2) \
X(a, STATIC,   OPTIONAL, STRING,   boot_status,       3) \
X(a, STATIC,   OPTIONAL, STRING,   bootname,          4) \
X(a, STATIC,   OPTIONAL, STRING,   bundle_build,      5) \
X(a, STATIC,   OPTIONAL, STRING,   bundle_compatible,   6) \
X(a, STATIC,   OPTIONAL, STRING,   bundle_description,   7) \
X(a, STATIC,   OPTIONAL, STRING,   bundle_ver,        8) \
X(a, STATIC,   OPTIONAL, STRING,   slot_cl,           9) \
X(a, STATIC,   OPTIONAL, STRING,   device,           10) \
X(a, STATIC,   OPTIONAL, UINT64,   installed_count,  11) \
X(a, STATIC,   OPTIONAL, STRING,   installed_timestamp,  12) \
X(a, STATIC,   OPTIONAL, STRING,   sha256,           13) \
X(a, STATIC,   OPTIONAL, UINT64,   size,             14) \
X(a, STATIC,   OPTIONAL, STRING,   slot_state,       15) \
X(a, STATIC,   OPTIONAL, STRING,   status,           16) \
X(a, STATIC,   OPTIONAL, STRING,   type,             17)
#define slot_status_res_pl_CALLBACK NULL
#define slot_status_res_pl_DEFAULT NULL

#define es_slot_status_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pl,                2)
#define es_slot_status_res_CALLBACK NULL
#define es_slot_status_res_DEFAULT NULL
#define es_slot_status_res_hdr_MSGTYPE response_hdr
#define es_slot_status_res_pl_MSGTYPE slot_status_res_pl

#define slot_status_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define slot_status_rpc_CALLBACK NULL
#define slot_status_rpc_DEFAULT NULL
#define slot_status_rpc_payload_req_MSGTYPE es_slot_status_req
#define slot_status_rpc_payload_res_MSGTYPE es_slot_status_res

#define mark_slot_req_pl_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   slot,              1) \
X(a, STATIC,   REQUIRED, STRING,   slot_state,        2)
#define mark_slot_req_pl_CALLBACK NULL
#define mark_slot_req_pl_DEFAULT (const pb_byte_t*)"\x0a\x08\x72\x6f\x6f\x74\x66\x73\x2e\x30\x12\x04\x67\x6f\x6f\x64\x00"

#define es_mark_slot_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_mark_slot_req_CALLBACK NULL
#define es_mark_slot_req_DEFAULT NULL
#define es_mark_slot_req_hdr_MSGTYPE request_hdr
#define es_mark_slot_req_pl_MSGTYPE mark_slot_req_pl

#define es_mark_slot_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_mark_slot_res_CALLBACK NULL
#define es_mark_slot_res_DEFAULT NULL
#define es_mark_slot_res_hdr_MSGTYPE response_hdr

#define mark_slot_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define mark_slot_rpc_CALLBACK NULL
#define mark_slot_rpc_DEFAULT NULL
#define mark_slot_rpc_payload_req_MSGTYPE es_mark_slot_req
#define mark_slot_rpc_payload_res_MSGTYPE es_mark_slot_res

#define es_get_primary_slot_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_get_primary_slot_req_CALLBACK NULL
#define es_get_primary_slot_req_DEFAULT NULL
#define es_get_primary_slot_req_hdr_MSGTYPE request_hdr

#define get_primary_slot_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   slot,              1)
#define get_primary_slot_res_pl_CALLBACK NULL
#define get_primary_slot_res_pl_DEFAULT NULL

#define es_get_primary_slot_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pl,                2)
#define es_get_primary_slot_res_CALLBACK NULL
#define es_get_primary_slot_res_DEFAULT NULL
#define es_get_primary_slot_res_hdr_MSGTYPE response_hdr
#define es_get_primary_slot_res_pl_MSGTYPE get_primary_slot_res_pl

#define get_primary_slot_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define get_primary_slot_rpc_CALLBACK NULL
#define get_primary_slot_rpc_DEFAULT NULL
#define get_primary_slot_rpc_payload_req_MSGTYPE es_get_primary_slot_req
#define get_primary_slot_rpc_payload_res_MSGTYPE es_get_primary_slot_res

#define sys_time_set_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define sys_time_set_rpc_CALLBACK NULL
#define sys_time_set_rpc_DEFAULT NULL
#define sys_time_set_rpc_payload_req_MSGTYPE es_sys_time_set_req
#define sys_time_set_rpc_payload_res_MSGTYPE es_sys_time_set_res

#define es_sys_time_set_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_sys_time_set_req_CALLBACK NULL
#define es_sys_time_set_req_DEFAULT NULL
#define es_sys_time_set_req_hdr_MSGTYPE request_hdr
#define es_sys_time_set_req_pl_MSGTYPE sys_time_set_req_pl

#define sys_time_set_req_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   sys_time,          1)
#define sys_time_set_req_pl_CALLBACK NULL
#define sys_time_set_req_pl_DEFAULT (const pb_byte_t*)"\x0a\x03\x4e\x2f\x41\x00"

#define es_sys_time_set_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_sys_time_set_res_CALLBACK NULL
#define es_sys_time_set_res_DEFAULT NULL
#define es_sys_time_set_res_hdr_MSGTYPE response_hdr

#define sys_time_get_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define sys_time_get_rpc_CALLBACK NULL
#define sys_time_get_rpc_DEFAULT NULL
#define sys_time_get_rpc_payload_req_MSGTYPE es_sys_time_get_req
#define sys_time_get_rpc_payload_res_MSGTYPE es_sys_time_get_res

#define es_sys_time_get_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_sys_time_get_req_CALLBACK NULL
#define es_sys_time_get_req_DEFAULT NULL
#define es_sys_time_get_req_hdr_MSGTYPE request_hdr

#define es_sys_time_get_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_sys_time_get_res_CALLBACK NULL
#define es_sys_time_get_res_DEFAULT NULL
#define es_sys_time_get_res_hdr_MSGTYPE response_hdr
#define es_sys_time_get_res_pl_MSGTYPE sys_time_get_res_pl

#define sys_time_get_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   sys_time,          1)
#define sys_time_get_res_pl_CALLBACK NULL
#define sys_time_get_res_pl_DEFAULT NULL

#define sys_time_pps_lock_stat_get_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define sys_time_pps_lock_stat_get_rpc_CALLBACK NULL
#define sys_time_pps_lock_stat_get_rpc_DEFAULT NULL
#define sys_time_pps_lock_stat_get_rpc_payload_req_MSGTYPE es_sys_time_pps_lock_stat_get_req
#define sys_time_pps_lock_stat_get_rpc_payload_res_MSGTYPE es_sys_time_pps_lock_stat_get_res

#define es_sys_time_pps_lock_stat_get_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_sys_time_pps_lock_stat_get_req_CALLBACK NULL
#define es_sys_time_pps_lock_stat_get_req_DEFAULT NULL
#define es_sys_time_pps_lock_stat_get_req_hdr_MSGTYPE request_hdr

#define es_sys_time_pps_lock_stat_get_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_sys_time_pps_lock_stat_get_res_CALLBACK NULL
#define es_sys_time_pps_lock_stat_get_res_DEFAULT NULL
#define es_sys_time_pps_lock_stat_get_res_hdr_MSGTYPE response_hdr
#define es_sys_time_pps_lock_stat_get_res_pl_MSGTYPE sys_time_pps_lock_stat_get_res_pl

#define sys_time_pps_lock_stat_get_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     locked,            1)
#define sys_time_pps_lock_stat_get_res_pl_CALLBACK NULL
#define sys_time_pps_lock_stat_get_res_pl_DEFAULT NULL

#define sys_time_pps_offset_get_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define sys_time_pps_offset_get_rpc_CALLBACK NULL
#define sys_time_pps_offset_get_rpc_DEFAULT NULL
#define sys_time_pps_offset_get_rpc_payload_req_MSGTYPE es_sys_time_pps_offset_get_req
#define sys_time_pps_offset_get_rpc_payload_res_MSGTYPE es_sys_time_pps_offset_get_res

#define es_sys_time_pps_offset_get_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_sys_time_pps_offset_get_req_CALLBACK NULL
#define es_sys_time_pps_offset_get_req_DEFAULT NULL
#define es_sys_time_pps_offset_get_req_hdr_MSGTYPE request_hdr

#define es_sys_time_pps_offset_get_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_sys_time_pps_offset_get_res_CALLBACK NULL
#define es_sys_time_pps_offset_get_res_DEFAULT NULL
#define es_sys_time_pps_offset_get_res_hdr_MSGTYPE response_hdr
#define es_sys_time_pps_offset_get_res_pl_MSGTYPE sys_time_pps_offset_get_res_pl

#define sys_time_pps_offset_get_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, SFIXED32, pps_offset,        1)
#define sys_time_pps_offset_get_res_pl_CALLBACK NULL
#define sys_time_pps_offset_get_res_pl_DEFAULT NULL

#define rtc_time_get_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define rtc_time_get_rpc_CALLBACK NULL
#define rtc_time_get_rpc_DEFAULT NULL
#define rtc_time_get_rpc_payload_req_MSGTYPE es_rtc_time_get_req
#define rtc_time_get_rpc_payload_res_MSGTYPE es_rtc_time_get_res

#define es_rtc_time_get_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_rtc_time_get_req_CALLBACK NULL
#define es_rtc_time_get_req_DEFAULT NULL
#define es_rtc_time_get_req_hdr_MSGTYPE request_hdr

#define es_rtc_time_get_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_rtc_time_get_res_CALLBACK NULL
#define es_rtc_time_get_res_DEFAULT NULL
#define es_rtc_time_get_res_hdr_MSGTYPE response_hdr
#define es_rtc_time_get_res_pl_MSGTYPE rtc_time_get_res_pl

#define rtc_time_get_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   rtc_time,          1)
#define rtc_time_get_res_pl_CALLBACK NULL
#define rtc_time_get_res_pl_DEFAULT NULL

#define rtc_time_force_sync_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define rtc_time_force_sync_rpc_CALLBACK NULL
#define rtc_time_force_sync_rpc_DEFAULT NULL
#define rtc_time_force_sync_rpc_payload_req_MSGTYPE es_rtc_time_force_sync_req
#define rtc_time_force_sync_rpc_payload_res_MSGTYPE es_rtc_time_force_sync_res

#define es_rtc_time_force_sync_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_rtc_time_force_sync_req_CALLBACK NULL
#define es_rtc_time_force_sync_req_DEFAULT NULL
#define es_rtc_time_force_sync_req_hdr_MSGTYPE request_hdr

#define es_rtc_time_force_sync_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_rtc_time_force_sync_res_CALLBACK NULL
#define es_rtc_time_force_sync_res_DEFAULT NULL
#define es_rtc_time_force_sync_res_hdr_MSGTYPE response_hdr

#define rf_board_stat_set_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define rf_board_stat_set_rpc_CALLBACK NULL
#define rf_board_stat_set_rpc_DEFAULT NULL
#define rf_board_stat_set_rpc_payload_req_MSGTYPE es_rf_board_stat_set_req
#define rf_board_stat_set_rpc_payload_res_MSGTYPE es_rf_board_stat_set_res

#define es_rf_board_stat_set_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_rf_board_stat_set_req_CALLBACK NULL
#define es_rf_board_stat_set_req_DEFAULT NULL
#define es_rf_board_stat_set_req_hdr_MSGTYPE request_hdr
#define es_rf_board_stat_set_req_pl_MSGTYPE rf_board_stat_set_req_pl

#define rf_board_stat_set_req_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     enabled,           1)
#define rf_board_stat_set_req_pl_CALLBACK NULL
#define rf_board_stat_set_req_pl_DEFAULT (const pb_byte_t*)"\x08\x00\x00"

#define es_rf_board_stat_set_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_rf_board_stat_set_res_CALLBACK NULL
#define es_rf_board_stat_set_res_DEFAULT NULL
#define es_rf_board_stat_set_res_hdr_MSGTYPE response_hdr

#define rf_board_stat_get_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define rf_board_stat_get_rpc_CALLBACK NULL
#define rf_board_stat_get_rpc_DEFAULT NULL
#define rf_board_stat_get_rpc_payload_req_MSGTYPE es_rf_board_stat_get_req
#define rf_board_stat_get_rpc_payload_res_MSGTYPE es_rf_board_stat_get_res

#define es_rf_board_stat_get_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_rf_board_stat_get_req_CALLBACK NULL
#define es_rf_board_stat_get_req_DEFAULT NULL
#define es_rf_board_stat_get_req_hdr_MSGTYPE request_hdr

#define es_rf_board_stat_get_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_rf_board_stat_get_res_CALLBACK NULL
#define es_rf_board_stat_get_res_DEFAULT NULL
#define es_rf_board_stat_get_res_hdr_MSGTYPE response_hdr
#define es_rf_board_stat_get_res_pl_MSGTYPE rf_board_stat_get_res_pl

#define system_halt_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define system_halt_rpc_CALLBACK NULL
#define system_halt_rpc_DEFAULT NULL
#define system_halt_rpc_payload_req_MSGTYPE es_system_halt_req
#define system_halt_rpc_payload_res_MSGTYPE es_system_halt_res

#define es_system_halt_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_system_halt_req_CALLBACK NULL
#define es_system_halt_req_DEFAULT NULL
#define es_system_halt_req_hdr_MSGTYPE request_hdr

#define es_system_halt_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_system_halt_res_CALLBACK NULL
#define es_system_halt_res_DEFAULT NULL
#define es_system_halt_res_hdr_MSGTYPE response_hdr

#define rf_board_stat_get_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     enabled,           1) \
X(a, STATIC,   OPTIONAL, STRING,   jesd204_fsm_state,   2) \
X(a, STATIC,   OPTIONAL, INT32,    jesd204_fsm_error,   3) \
X(a, STATIC,   OPTIONAL, BOOL,     jesd204_fsm_paused,   4)
#define rf_board_stat_get_res_pl_CALLBACK NULL
#define rf_board_stat_get_res_pl_DEFAULT NULL

#define es_board_mgr_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,eth_cfg_set,rpc.eth_cfg_set),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,eth_cfg_get,rpc.eth_cfg_get),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,csp_cfg_set,rpc.csp_cfg_set),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,csp_cfg_get,rpc.csp_cfg_get),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,esps_cfg_set,rpc.esps_cfg_set),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,esps_cfg_get,rpc.esps_cfg_get),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,bundle_info,rpc.bundle_info),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,bundle_install,rpc.bundle_install),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,update_progress,rpc.update_progress),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,slot_status,rpc.slot_status),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,mark_slot,rpc.mark_slot),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,get_primary_slot,rpc.get_primary_slot),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,sys_time_set,rpc.sys_time_set),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,sys_time_get,rpc.sys_time_get),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,sys_time_pps_lock_stat_get,rpc.sys_time_pps_lock_stat_get),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,sys_time_pps_offset_get,rpc.sys_time_pps_offset_get),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,rtc_time_get,rpc.rtc_time_get),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,rtc_time_force_sync,rpc.rtc_time_force_sync),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,rf_board_stat_set,rpc.rf_board_stat_set),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,rf_board_stat_get,rpc.rf_board_stat_get),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,system_halt,rpc.system_halt),  21)
#define es_board_mgr_rpc_CALLBACK NULL
#define es_board_mgr_rpc_DEFAULT NULL
#define es_board_mgr_rpc_rpc_eth_cfg_set_MSGTYPE eth_cfg_set_rpc
#define es_board_mgr_rpc_rpc_eth_cfg_get_MSGTYPE eth_cfg_get_rpc
#define es_board_mgr_rpc_rpc_csp_cfg_set_MSGTYPE csp_cfg_set_rpc
#define es_board_mgr_rpc_rpc_csp_cfg_get_MSGTYPE csp_cfg_get_rpc
#define es_board_mgr_rpc_rpc_esps_cfg_set_MSGTYPE esps_cfg_set_rpc
#define es_board_mgr_rpc_rpc_esps_cfg_get_MSGTYPE esps_cfg_get_rpc
#define es_board_mgr_rpc_rpc_bundle_info_MSGTYPE bundle_info_rpc
#define es_board_mgr_rpc_rpc_bundle_install_MSGTYPE bundle_install_rpc
#define es_board_mgr_rpc_rpc_update_progress_MSGTYPE update_progress_rpc
#define es_board_mgr_rpc_rpc_slot_status_MSGTYPE slot_status_rpc
#define es_board_mgr_rpc_rpc_mark_slot_MSGTYPE mark_slot_rpc
#define es_board_mgr_rpc_rpc_get_primary_slot_MSGTYPE get_primary_slot_rpc
#define es_board_mgr_rpc_rpc_sys_time_set_MSGTYPE sys_time_set_rpc
#define es_board_mgr_rpc_rpc_sys_time_get_MSGTYPE sys_time_get_rpc
#define es_board_mgr_rpc_rpc_sys_time_pps_lock_stat_get_MSGTYPE sys_time_pps_lock_stat_get_rpc
#define es_board_mgr_rpc_rpc_sys_time_pps_offset_get_MSGTYPE sys_time_pps_offset_get_rpc
#define es_board_mgr_rpc_rpc_rtc_time_get_MSGTYPE rtc_time_get_rpc
#define es_board_mgr_rpc_rpc_rtc_time_force_sync_MSGTYPE rtc_time_force_sync_rpc
#define es_board_mgr_rpc_rpc_rf_board_stat_set_MSGTYPE rf_board_stat_set_rpc
#define es_board_mgr_rpc_rpc_rf_board_stat_get_MSGTYPE rf_board_stat_get_rpc
#define es_board_mgr_rpc_rpc_system_halt_MSGTYPE system_halt_rpc

extern const pb_msgdesc_t eth_cfg_get_req_pl_msg;
extern const pb_msgdesc_t es_eth_cfg_get_req_msg;
extern const pb_msgdesc_t eth_cfg_get_res_pl_msg;
extern const pb_msgdesc_t es_eth_cfg_get_res_msg;
extern const pb_msgdesc_t eth_cfg_get_rpc_msg;
extern const pb_msgdesc_t eth_cfg_set_req_pl_msg;
extern const pb_msgdesc_t es_eth_cfg_set_req_msg;
extern const pb_msgdesc_t es_eth_cfg_set_res_msg;
extern const pb_msgdesc_t eth_cfg_set_rpc_msg;
extern const pb_msgdesc_t csp_cfg_get_req_pl_msg;
extern const pb_msgdesc_t es_csp_cfg_get_req_msg;
extern const pb_msgdesc_t csp_cfg_get_res_pl_msg;
extern const pb_msgdesc_t es_csp_cfg_get_res_msg;
extern const pb_msgdesc_t csp_cfg_get_rpc_msg;
extern const pb_msgdesc_t csp_cfg_set_req_pl_msg;
extern const pb_msgdesc_t es_csp_cfg_set_req_msg;
extern const pb_msgdesc_t es_csp_cfg_set_res_msg;
extern const pb_msgdesc_t csp_cfg_set_rpc_msg;
extern const pb_msgdesc_t esps_cfg_get_req_pl_msg;
extern const pb_msgdesc_t es_esps_cfg_get_req_msg;
extern const pb_msgdesc_t esps_cfg_get_res_pl_msg;
extern const pb_msgdesc_t es_esps_cfg_get_res_msg;
extern const pb_msgdesc_t esps_cfg_get_rpc_msg;
extern const pb_msgdesc_t esps_cfg_set_req_pl_msg;
extern const pb_msgdesc_t es_esps_cfg_set_req_msg;
extern const pb_msgdesc_t es_esps_cfg_set_res_msg;
extern const pb_msgdesc_t esps_cfg_set_rpc_msg;
extern const pb_msgdesc_t bundle_info_req_pl_msg;
extern const pb_msgdesc_t es_bundle_info_req_msg;
extern const pb_msgdesc_t bundle_info_res_pl_msg;
extern const pb_msgdesc_t es_bundle_info_res_msg;
extern const pb_msgdesc_t bundle_info_rpc_msg;
extern const pb_msgdesc_t bundle_install_req_pl_msg;
extern const pb_msgdesc_t es_bundle_install_req_msg;
extern const pb_msgdesc_t es_bundle_install_res_msg;
extern const pb_msgdesc_t bundle_install_rpc_msg;
extern const pb_msgdesc_t es_update_progress_req_msg;
extern const pb_msgdesc_t update_progress_res_pl_msg;
extern const pb_msgdesc_t es_update_progress_res_msg;
extern const pb_msgdesc_t update_progress_rpc_msg;
extern const pb_msgdesc_t slot_status_req_pl_msg;
extern const pb_msgdesc_t es_slot_status_req_msg;
extern const pb_msgdesc_t slot_status_res_pl_msg;
extern const pb_msgdesc_t es_slot_status_res_msg;
extern const pb_msgdesc_t slot_status_rpc_msg;
extern const pb_msgdesc_t mark_slot_req_pl_msg;
extern const pb_msgdesc_t es_mark_slot_req_msg;
extern const pb_msgdesc_t es_mark_slot_res_msg;
extern const pb_msgdesc_t mark_slot_rpc_msg;
extern const pb_msgdesc_t es_get_primary_slot_req_msg;
extern const pb_msgdesc_t get_primary_slot_res_pl_msg;
extern const pb_msgdesc_t es_get_primary_slot_res_msg;
extern const pb_msgdesc_t get_primary_slot_rpc_msg;
extern const pb_msgdesc_t sys_time_set_rpc_msg;
extern const pb_msgdesc_t es_sys_time_set_req_msg;
extern const pb_msgdesc_t sys_time_set_req_pl_msg;
extern const pb_msgdesc_t es_sys_time_set_res_msg;
extern const pb_msgdesc_t sys_time_get_rpc_msg;
extern const pb_msgdesc_t es_sys_time_get_req_msg;
extern const pb_msgdesc_t es_sys_time_get_res_msg;
extern const pb_msgdesc_t sys_time_get_res_pl_msg;
extern const pb_msgdesc_t sys_time_pps_lock_stat_get_rpc_msg;
extern const pb_msgdesc_t es_sys_time_pps_lock_stat_get_req_msg;
extern const pb_msgdesc_t es_sys_time_pps_lock_stat_get_res_msg;
extern const pb_msgdesc_t sys_time_pps_lock_stat_get_res_pl_msg;
extern const pb_msgdesc_t sys_time_pps_offset_get_rpc_msg;
extern const pb_msgdesc_t es_sys_time_pps_offset_get_req_msg;
extern const pb_msgdesc_t es_sys_time_pps_offset_get_res_msg;
extern const pb_msgdesc_t sys_time_pps_offset_get_res_pl_msg;
extern const pb_msgdesc_t rtc_time_get_rpc_msg;
extern const pb_msgdesc_t es_rtc_time_get_req_msg;
extern const pb_msgdesc_t es_rtc_time_get_res_msg;
extern const pb_msgdesc_t rtc_time_get_res_pl_msg;
extern const pb_msgdesc_t rtc_time_force_sync_rpc_msg;
extern const pb_msgdesc_t es_rtc_time_force_sync_req_msg;
extern const pb_msgdesc_t es_rtc_time_force_sync_res_msg;
extern const pb_msgdesc_t rf_board_stat_set_rpc_msg;
extern const pb_msgdesc_t es_rf_board_stat_set_req_msg;
extern const pb_msgdesc_t rf_board_stat_set_req_pl_msg;
extern const pb_msgdesc_t es_rf_board_stat_set_res_msg;
extern const pb_msgdesc_t rf_board_stat_get_rpc_msg;
extern const pb_msgdesc_t es_rf_board_stat_get_req_msg;
extern const pb_msgdesc_t es_rf_board_stat_get_res_msg;
extern const pb_msgdesc_t system_halt_rpc_msg;
extern const pb_msgdesc_t es_system_halt_req_msg;
extern const pb_msgdesc_t es_system_halt_res_msg;
extern const pb_msgdesc_t rf_board_stat_get_res_pl_msg;
extern const pb_msgdesc_t es_board_mgr_rpc_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define eth_cfg_get_req_pl_fields &eth_cfg_get_req_pl_msg
#define es_eth_cfg_get_req_fields &es_eth_cfg_get_req_msg
#define eth_cfg_get_res_pl_fields &eth_cfg_get_res_pl_msg
#define es_eth_cfg_get_res_fields &es_eth_cfg_get_res_msg
#define eth_cfg_get_rpc_fields &eth_cfg_get_rpc_msg
#define eth_cfg_set_req_pl_fields &eth_cfg_set_req_pl_msg
#define es_eth_cfg_set_req_fields &es_eth_cfg_set_req_msg
#define es_eth_cfg_set_res_fields &es_eth_cfg_set_res_msg
#define eth_cfg_set_rpc_fields &eth_cfg_set_rpc_msg
#define csp_cfg_get_req_pl_fields &csp_cfg_get_req_pl_msg
#define es_csp_cfg_get_req_fields &es_csp_cfg_get_req_msg
#define csp_cfg_get_res_pl_fields &csp_cfg_get_res_pl_msg
#define es_csp_cfg_get_res_fields &es_csp_cfg_get_res_msg
#define csp_cfg_get_rpc_fields &csp_cfg_get_rpc_msg
#define csp_cfg_set_req_pl_fields &csp_cfg_set_req_pl_msg
#define es_csp_cfg_set_req_fields &es_csp_cfg_set_req_msg
#define es_csp_cfg_set_res_fields &es_csp_cfg_set_res_msg
#define csp_cfg_set_rpc_fields &csp_cfg_set_rpc_msg
#define esps_cfg_get_req_pl_fields &esps_cfg_get_req_pl_msg
#define es_esps_cfg_get_req_fields &es_esps_cfg_get_req_msg
#define esps_cfg_get_res_pl_fields &esps_cfg_get_res_pl_msg
#define es_esps_cfg_get_res_fields &es_esps_cfg_get_res_msg
#define esps_cfg_get_rpc_fields &esps_cfg_get_rpc_msg
#define esps_cfg_set_req_pl_fields &esps_cfg_set_req_pl_msg
#define es_esps_cfg_set_req_fields &es_esps_cfg_set_req_msg
#define es_esps_cfg_set_res_fields &es_esps_cfg_set_res_msg
#define esps_cfg_set_rpc_fields &esps_cfg_set_rpc_msg
#define bundle_info_req_pl_fields &bundle_info_req_pl_msg
#define es_bundle_info_req_fields &es_bundle_info_req_msg
#define bundle_info_res_pl_fields &bundle_info_res_pl_msg
#define es_bundle_info_res_fields &es_bundle_info_res_msg
#define bundle_info_rpc_fields &bundle_info_rpc_msg
#define bundle_install_req_pl_fields &bundle_install_req_pl_msg
#define es_bundle_install_req_fields &es_bundle_install_req_msg
#define es_bundle_install_res_fields &es_bundle_install_res_msg
#define bundle_install_rpc_fields &bundle_install_rpc_msg
#define es_update_progress_req_fields &es_update_progress_req_msg
#define update_progress_res_pl_fields &update_progress_res_pl_msg
#define es_update_progress_res_fields &es_update_progress_res_msg
#define update_progress_rpc_fields &update_progress_rpc_msg
#define slot_status_req_pl_fields &slot_status_req_pl_msg
#define es_slot_status_req_fields &es_slot_status_req_msg
#define slot_status_res_pl_fields &slot_status_res_pl_msg
#define es_slot_status_res_fields &es_slot_status_res_msg
#define slot_status_rpc_fields &slot_status_rpc_msg
#define mark_slot_req_pl_fields &mark_slot_req_pl_msg
#define es_mark_slot_req_fields &es_mark_slot_req_msg
#define es_mark_slot_res_fields &es_mark_slot_res_msg
#define mark_slot_rpc_fields &mark_slot_rpc_msg
#define es_get_primary_slot_req_fields &es_get_primary_slot_req_msg
#define get_primary_slot_res_pl_fields &get_primary_slot_res_pl_msg
#define es_get_primary_slot_res_fields &es_get_primary_slot_res_msg
#define get_primary_slot_rpc_fields &get_primary_slot_rpc_msg
#define sys_time_set_rpc_fields &sys_time_set_rpc_msg
#define es_sys_time_set_req_fields &es_sys_time_set_req_msg
#define sys_time_set_req_pl_fields &sys_time_set_req_pl_msg
#define es_sys_time_set_res_fields &es_sys_time_set_res_msg
#define sys_time_get_rpc_fields &sys_time_get_rpc_msg
#define es_sys_time_get_req_fields &es_sys_time_get_req_msg
#define es_sys_time_get_res_fields &es_sys_time_get_res_msg
#define sys_time_get_res_pl_fields &sys_time_get_res_pl_msg
#define sys_time_pps_lock_stat_get_rpc_fields &sys_time_pps_lock_stat_get_rpc_msg
#define es_sys_time_pps_lock_stat_get_req_fields &es_sys_time_pps_lock_stat_get_req_msg
#define es_sys_time_pps_lock_stat_get_res_fields &es_sys_time_pps_lock_stat_get_res_msg
#define sys_time_pps_lock_stat_get_res_pl_fields &sys_time_pps_lock_stat_get_res_pl_msg
#define sys_time_pps_offset_get_rpc_fields &sys_time_pps_offset_get_rpc_msg
#define es_sys_time_pps_offset_get_req_fields &es_sys_time_pps_offset_get_req_msg
#define es_sys_time_pps_offset_get_res_fields &es_sys_time_pps_offset_get_res_msg
#define sys_time_pps_offset_get_res_pl_fields &sys_time_pps_offset_get_res_pl_msg
#define rtc_time_get_rpc_fields &rtc_time_get_rpc_msg
#define es_rtc_time_get_req_fields &es_rtc_time_get_req_msg
#define es_rtc_time_get_res_fields &es_rtc_time_get_res_msg
#define rtc_time_get_res_pl_fields &rtc_time_get_res_pl_msg
#define rtc_time_force_sync_rpc_fields &rtc_time_force_sync_rpc_msg
#define es_rtc_time_force_sync_req_fields &es_rtc_time_force_sync_req_msg
#define es_rtc_time_force_sync_res_fields &es_rtc_time_force_sync_res_msg
#define rf_board_stat_set_rpc_fields &rf_board_stat_set_rpc_msg
#define es_rf_board_stat_set_req_fields &es_rf_board_stat_set_req_msg
#define rf_board_stat_set_req_pl_fields &rf_board_stat_set_req_pl_msg
#define es_rf_board_stat_set_res_fields &es_rf_board_stat_set_res_msg
#define rf_board_stat_get_rpc_fields &rf_board_stat_get_rpc_msg
#define es_rf_board_stat_get_req_fields &es_rf_board_stat_get_req_msg
#define es_rf_board_stat_get_res_fields &es_rf_board_stat_get_res_msg
#define system_halt_rpc_fields &system_halt_rpc_msg
#define es_system_halt_req_fields &es_system_halt_req_msg
#define es_system_halt_res_fields &es_system_halt_res_msg
#define rf_board_stat_get_res_pl_fields &rf_board_stat_get_res_pl_msg
#define es_board_mgr_rpc_fields &es_board_mgr_rpc_msg

/* Maximum encoded size of messages (where known) */
#define bundle_info_req_pl_size                  130
#define bundle_info_res_pl_size                  122
#define bundle_info_rpc_size                     1180
#define bundle_install_req_pl_size               130
#define bundle_install_rpc_size                  1056
#define csp_cfg_get_req_pl_size                  17
#define csp_cfg_get_res_pl_size                  23
#define csp_cfg_get_rpc_size                     1081
#define csp_cfg_set_req_pl_size                  23
#define csp_cfg_set_rpc_size                     1056
#define es_board_mgr_rpc_size                    1294
#define es_bundle_info_req_size                  157
#define es_bundle_info_res_size                  1177
#define es_bundle_install_req_size               157
#define es_bundle_install_res_size               1053
#define es_csp_cfg_get_req_size                  43
#define es_csp_cfg_get_res_size                  1078
#define es_csp_cfg_set_req_size                  49
#define es_csp_cfg_set_res_size                  1053
#define es_esps_cfg_get_req_size                 43
#define es_esps_cfg_get_res_size                 1078
#define es_esps_cfg_set_req_size                 49
#define es_esps_cfg_set_res_size                 1053
#define es_eth_cfg_get_req_size                  43
#define es_eth_cfg_get_res_size                  1097
#define es_eth_cfg_set_req_size                  68
#define es_eth_cfg_set_res_size                  1053
#define es_get_primary_slot_req_size             24
#define es_get_primary_slot_res_size             1076
#define es_mark_slot_req_size                    58
#define es_mark_slot_res_size                    1053
#define es_rf_board_stat_get_req_size            24
#define es_rf_board_stat_get_res_size            1151
#define es_rf_board_stat_set_req_size            28
#define es_rf_board_stat_set_res_size            1053
#define es_rtc_time_force_sync_req_size          24
#define es_rtc_time_force_sync_res_size          1053
#define es_rtc_time_get_req_size                 24
#define es_rtc_time_get_res_size                 1081
#define es_slot_status_req_size                  47
#define es_slot_status_res_size                  1288
#define es_sys_time_get_req_size                 24
#define es_sys_time_get_res_size                 1081
#define es_sys_time_pps_lock_stat_get_req_size   24
#define es_sys_time_pps_lock_stat_get_res_size   1057
#define es_sys_time_pps_offset_get_req_size      24
#define es_sys_time_pps_offset_get_res_size      1060
#define es_sys_time_set_req_size                 52
#define es_sys_time_set_res_size                 1053
#define es_system_halt_req_size                  24
#define es_system_halt_res_size                  1053
#define es_update_progress_req_size              24
#define es_update_progress_res_size              1235
#define esps_cfg_get_req_pl_size                 17
#define esps_cfg_get_res_pl_size                 23
#define esps_cfg_get_rpc_size                    1081
#define esps_cfg_set_req_pl_size                 23
#define esps_cfg_set_rpc_size                    1056
#define eth_cfg_get_req_pl_size                  17
#define eth_cfg_get_res_pl_size                  42
#define eth_cfg_get_rpc_size                     1100
#define eth_cfg_set_req_pl_size                  42
#define eth_cfg_set_rpc_size                     1056
#define get_primary_slot_res_pl_size             21
#define get_primary_slot_rpc_size                1079
#define mark_slot_req_pl_size                    32
#define mark_slot_rpc_size                       1056
#define rf_board_stat_get_res_pl_size            96
#define rf_board_stat_get_rpc_size               1154
#define rf_board_stat_set_req_pl_size            2
#define rf_board_stat_set_rpc_size               1056
#define rtc_time_force_sync_rpc_size             1056
#define rtc_time_get_res_pl_size                 26
#define rtc_time_get_rpc_size                    1084
#define slot_status_req_pl_size                  21
#define slot_status_res_pl_size                  232
#define slot_status_rpc_size                     1291
#define sys_time_get_res_pl_size                 26
#define sys_time_get_rpc_size                    1084
#define sys_time_pps_lock_stat_get_res_pl_size   2
#define sys_time_pps_lock_stat_get_rpc_size      1060
#define sys_time_pps_offset_get_res_pl_size      5
#define sys_time_pps_offset_get_rpc_size         1063
#define sys_time_set_req_pl_size                 26
#define sys_time_set_rpc_size                    1056
#define system_halt_rpc_size                     1056
#define update_progress_res_pl_size              179
#define update_progress_rpc_size                 1238

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
