/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_ES_BOARD_INFO_PB_H_INCLUDED
#define PB_ES_BOARD_INFO_PB_H_INCLUDED
#include <pb.h>
#include "es_common_types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/**ADM1177 power monitor telemetry get response payload*/
typedef struct _adm1177_tel_get_res_pl { 
    bool has_current0;
    double current0; /**< Vin, current in mA*/
    bool has_voltage0;
    double voltage0; /**< Vin, voltage in V*/
} adm1177_tel_get_res_pl;

/**Xilinx AMS get response payload*/
typedef struct _ams_tel_get_res_pl { 
    bool has_pl_temp;
    double pl_temp; /**< FPGA temperature in C*/
    bool has_ps_temp;
    double ps_temp; /**< CPU temperature in C*/
    bool has_remote_temp;
    double remote_temp; /**< SOC Full power domain (FPD) temperature measurement (REMOTE) in deg C*/
    bool has_psmgtravcc;
    double psmgtravcc; /**< VCC_PS_GTR voltage measurement (Vcc_PS_MGTRAVCC).*/
    bool has_psmgtravtt;
    double psmgtravtt; /**< VTT_PS_GTR voltage measurement (Vcc_PS_MGTRAVTT).*/
    bool has_vccams;
    double vccams; /**< PL VCCADC voltage measurement (Vcc_AMS).*/
    bool has_vccaux;
    double vccaux; /**< PS Aux voltage measurement, (Vcc_AUX).*/
    bool has_vccbram;
    double vccbram; /**< Block RAM voltage measurement, (Vcc_BRAM).*/
    bool has_vccint;
    double vccint; /**< PL Internal voltage measurement, (Vcc_PLINT).*/
    bool has_vccplaux;
    double vccplaux; /**< PL Aux voltage measurement, (Vcc_PLAUX).*/
    bool has_vccplintfp;
    double vccplintfp; /**< PL full power supply (Vcc_PLINTFP)*/
    bool has_vccpsaux;
    double vccpsaux; /**< PS Aux voltage reference (Vcc_PSAUX).*/
    bool has_vcc_psbatt;
    double vcc_psbatt; /**< Battery voltage measurement (Vcc_PSBATT.*/
    bool has_vccpsddr;
    double vccpsddr; /**< DDR I/O VCC voltage measurement.*/
    bool has_vcc_psddrpll;
    double vcc_psddrpll; /**< Voltage measurement for six DDR I/O PLLs, VCC_PSDDR_PLL.*/
    bool has_vccpsintfp;
    double vccpsintfp; /**< FPD Internal voltage measurement, VCC_PSINTFP (supply5)*/
    bool has_vccpsintfpddr;
    double vccpsintfpddr; /**< VCC_PSINTFP_DDR voltage measurement.*/
    bool has_vccpsintlp;
    double vccpsintlp; /**< LPD Internal voltage measurement, VCC_PSINTLP (supply4).*/
    bool has_vccpsio0;
    double vccpsio0; /**< PS IO Bank 500 voltage measurement (supply6).*/
    bool has_vccpsio1;
    double vccpsio1; /**< VCCO_PSIO1 voltage measurement.*/
    bool has_vccpsio2;
    double vccpsio2; /**< VCCO_PSIO2 voltage measurement.*/
    bool has_vccpsio3;
    double vccpsio3; /**< PS IO Bank 503 voltage measurement (supply5).*/
    bool has_vcc_pspll0;
    double vcc_pspll0; /**< System PLLs voltage measurement, VCC_PSPLL*/
    bool has_vccvrefn;
    double vccvrefn; /**< ADC Reference P+ voltage measurement.*/
    bool has_vccvrefp;
    double vccvrefp; /**< ADC Reference N- voltage measurement.*/
} ams_tel_get_res_pl;

/**ADM1177 power monitor telemetry get request*/
typedef struct _es_adm1177_tel_get_req { 
    request_hdr hdr; /**< Request header*/
} es_adm1177_tel_get_req;

/**Xilinx AMS get request*/
typedef struct _es_ams_tel_get_req { 
    request_hdr hdr; /**< Request header*/
} es_ams_tel_get_req;

/**Reset reason get request*/
typedef struct _es_reset_reason_get_req { 
    request_hdr hdr; /**< Request header*/
} es_reset_reason_get_req;

/**Board id/serial number get request*/
typedef struct _es_serial_get_req { 
    request_hdr hdr; /**< Request header*/
} es_serial_get_req;

/**System information get request*/
typedef struct _es_system_info_get_req { 
    request_hdr hdr; /**< Request header*/
} es_system_info_get_req;

/**Reset reason get response payload*/
typedef struct _reset_reason_get_res_pl { 
    bool has_reset_reason;
    char reset_reason[80]; /**< Reset reason*/
    bool has_uptime;
    float uptime; /**< Uptime in seconds after the last boot*/
} reset_reason_get_res_pl;

/**Board id/serial number get response payload*/
typedef struct _serial_get_res_pl { 
    bool has_machine;
    char machine[60]; /**< ID of the machine*/
    bool has_serial_number;
    char serial_number[60]; /**< Serial number*/
} serial_get_res_pl;

/**Get software version of a module request payload*/
typedef struct _software_version_get_req_pl { 
    char module[60]; /**< Name of the module to retrieve version for*/
} software_version_get_req_pl;

/**Get software version of a module response payload*/
typedef struct _software_version_get_res_pl { 
    bool has_branch;
    char branch[60]; /**< Git branch*/
    bool has_sha;
    char sha[41]; /**< Git sha*/
    bool has_clean_state;
    char clean_state[6]; /**< State (clean / dirty)*/
    bool has_date;
    char date[31]; /**< Date*/
} software_version_get_res_pl;

/**System information get response payload*/
typedef struct _system_info_get_res_pl { 
    bool has_disk_total;
    int64_t disk_total; /**< Disk total*/
    bool has_disk_used;
    int64_t disk_used; /**< Disk used*/
    bool has_disk_free;
    int64_t disk_free; /**< Disk free*/
    bool has_load_avg_1;
    float load_avg_1; /**< Average load for the last 1 minute*/
    bool has_load_avg_5;
    float load_avg_5; /**< Average load for the last 5 minutes*/
    bool has_load_avg_15;
    float load_avg_15; /**< Average load for the last 15 minutes*/
    bool has_cpu_freq;
    float cpu_freq; /**< CPU frequency*/
    bool has_cpu_ctx_sw;
    int64_t cpu_ctx_sw; /**< CPU ctx switching*/
    bool has_cpu_irqs;
    int64_t cpu_irqs; /**< CPU isr*/
    bool has_boot_time;
    char boot_time[120]; /**<  Time at witch the system has started*/
} system_info_get_res_pl;

/**ADM1177 power monitor telemetry get response*/
typedef struct _es_adm1177_tel_get_res { 
    response_hdr hdr; /**< Response header*/
    bool has_pl;
    adm1177_tel_get_res_pl pl; /**< Response payload*/
} es_adm1177_tel_get_res;

/**Xilinx AMS get response*/
typedef struct _es_ams_tel_get_res { 
    response_hdr hdr; /**< Response header*/
    bool has_pl;
    ams_tel_get_res_pl pl; /**< Response payload*/
} es_ams_tel_get_res;

/**Reset reason get response*/
typedef struct _es_reset_reason_get_res { 
    response_hdr hdr; /**< Response header*/
    bool has_pl;
    reset_reason_get_res_pl pl; /**< Response payload*/
} es_reset_reason_get_res;

/**Board id/serial number get response*/
typedef struct _es_serial_get_res { 
    response_hdr hdr; /**< Response header*/
    bool has_pl;
    serial_get_res_pl pl; /**< Request header*/
} es_serial_get_res;

/**Get software version of a module request*/
typedef struct _es_software_version_get_req { 
    request_hdr hdr; /**< Request header*/
    bool has_pl;
    software_version_get_req_pl pl; /**< Request payload*/
} es_software_version_get_req;

/**Get software version of a module response*/
typedef struct _es_software_version_get_res { 
    response_hdr hdr; /**< Response header*/
    bool has_pl;
    software_version_get_res_pl pl; /**< You can add comments here*/
} es_software_version_get_res;

/**System information get response*/
typedef struct _es_system_info_get_res { 
    response_hdr hdr; /**< Response header*/
    bool has_pl;
    system_info_get_res_pl pl; /**< Response payload*/
} es_system_info_get_res;

/**ADM1177 power monitor telemetry get RPC*/
typedef struct _adm1177_tel_get_rpc { 
    pb_size_t which_payload;
    union {
        es_adm1177_tel_get_req req;
        es_adm1177_tel_get_res res;
    } payload; 
} adm1177_tel_get_rpc;

/**Xilinx AMS get RPC*/
typedef struct _ams_tel_get_rpc { 
    pb_size_t which_payload;
    union {
        es_ams_tel_get_req req;
        es_ams_tel_get_res res;
    } payload; 
} ams_tel_get_rpc;

/**Retrieve the reset reason*/
typedef struct _reset_reason_get_rpc { 
    pb_size_t which_payload;
    union {
        es_reset_reason_get_req req;
        es_reset_reason_get_res res;
    } payload; 
} reset_reason_get_rpc;

/**Retrieve the id of the machine and its serial number*/
typedef struct _serial_get_rpc { 
    pb_size_t which_payload;
    union {
        es_serial_get_req req;
        es_serial_get_res res;
    } payload; 
} serial_get_rpc;

/**Get software version of a module RPC*/
typedef struct _software_version_get_rpc { 
    pb_size_t which_payload;
    union {
        es_software_version_get_req req;
        es_software_version_get_res res;
    } payload; 
} software_version_get_rpc;

/**System information get RPC*/
typedef struct _system_info_get_rpc { 
    pb_size_t which_payload;
    union {
        es_system_info_get_req req;
        es_system_info_get_res res;
    } payload; 
} system_info_get_rpc;

/**ES BoardInfo RPCs*/
typedef struct _es_board_info_rpc { 
    pb_size_t which_rpc;
    union {
        software_version_get_rpc software_version_get;
        system_info_get_rpc system_info_get;
        adm1177_tel_get_rpc adm1177_tel_get;
        ams_tel_get_rpc ams_tel_get;
        serial_get_rpc serial_get;
        reset_reason_get_rpc reset_reason_get;
    } rpc; 
} es_board_info_rpc;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define software_version_get_req_pl_init_default {"es-middleware"}
#define es_software_version_get_req_init_default {request_hdr_init_default, false, software_version_get_req_pl_init_default}
#define software_version_get_res_pl_init_default {false, "", false, "", false, "", false, ""}
#define es_software_version_get_res_init_default {response_hdr_init_default, false, software_version_get_res_pl_init_default}
#define software_version_get_rpc_init_default    {0, {es_software_version_get_req_init_default}}
#define es_system_info_get_req_init_default      {request_hdr_init_default}
#define system_info_get_res_pl_init_default      {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, ""}
#define es_system_info_get_res_init_default      {response_hdr_init_default, false, system_info_get_res_pl_init_default}
#define system_info_get_rpc_init_default         {0, {es_system_info_get_req_init_default}}
#define es_adm1177_tel_get_req_init_default      {request_hdr_init_default}
#define adm1177_tel_get_res_pl_init_default      {false, 0, false, 0}
#define es_adm1177_tel_get_res_init_default      {response_hdr_init_default, false, adm1177_tel_get_res_pl_init_default}
#define adm1177_tel_get_rpc_init_default         {0, {es_adm1177_tel_get_req_init_default}}
#define es_ams_tel_get_req_init_default          {request_hdr_init_default}
#define ams_tel_get_res_pl_init_default          {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define es_ams_tel_get_res_init_default          {response_hdr_init_default, false, ams_tel_get_res_pl_init_default}
#define ams_tel_get_rpc_init_default             {0, {es_ams_tel_get_req_init_default}}
#define es_serial_get_req_init_default           {request_hdr_init_default}
#define serial_get_res_pl_init_default           {false, "", false, ""}
#define es_serial_get_res_init_default           {response_hdr_init_default, false, serial_get_res_pl_init_default}
#define serial_get_rpc_init_default              {0, {es_serial_get_req_init_default}}
#define es_reset_reason_get_req_init_default     {request_hdr_init_default}
#define reset_reason_get_res_pl_init_default     {false, "", false, 0}
#define es_reset_reason_get_res_init_default     {response_hdr_init_default, false, reset_reason_get_res_pl_init_default}
#define reset_reason_get_rpc_init_default        {0, {es_reset_reason_get_req_init_default}}
#define es_board_info_rpc_init_default           {0, {software_version_get_rpc_init_default}}
#define software_version_get_req_pl_init_zero    {""}
#define es_software_version_get_req_init_zero    {request_hdr_init_zero, false, software_version_get_req_pl_init_zero}
#define software_version_get_res_pl_init_zero    {false, "", false, "", false, "", false, ""}
#define es_software_version_get_res_init_zero    {response_hdr_init_zero, false, software_version_get_res_pl_init_zero}
#define software_version_get_rpc_init_zero       {0, {es_software_version_get_req_init_zero}}
#define es_system_info_get_req_init_zero         {request_hdr_init_zero}
#define system_info_get_res_pl_init_zero         {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, ""}
#define es_system_info_get_res_init_zero         {response_hdr_init_zero, false, system_info_get_res_pl_init_zero}
#define system_info_get_rpc_init_zero            {0, {es_system_info_get_req_init_zero}}
#define es_adm1177_tel_get_req_init_zero         {request_hdr_init_zero}
#define adm1177_tel_get_res_pl_init_zero         {false, 0, false, 0}
#define es_adm1177_tel_get_res_init_zero         {response_hdr_init_zero, false, adm1177_tel_get_res_pl_init_zero}
#define adm1177_tel_get_rpc_init_zero            {0, {es_adm1177_tel_get_req_init_zero}}
#define es_ams_tel_get_req_init_zero             {request_hdr_init_zero}
#define ams_tel_get_res_pl_init_zero             {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define es_ams_tel_get_res_init_zero             {response_hdr_init_zero, false, ams_tel_get_res_pl_init_zero}
#define ams_tel_get_rpc_init_zero                {0, {es_ams_tel_get_req_init_zero}}
#define es_serial_get_req_init_zero              {request_hdr_init_zero}
#define serial_get_res_pl_init_zero              {false, "", false, ""}
#define es_serial_get_res_init_zero              {response_hdr_init_zero, false, serial_get_res_pl_init_zero}
#define serial_get_rpc_init_zero                 {0, {es_serial_get_req_init_zero}}
#define es_reset_reason_get_req_init_zero        {request_hdr_init_zero}
#define reset_reason_get_res_pl_init_zero        {false, "", false, 0}
#define es_reset_reason_get_res_init_zero        {response_hdr_init_zero, false, reset_reason_get_res_pl_init_zero}
#define reset_reason_get_rpc_init_zero           {0, {es_reset_reason_get_req_init_zero}}
#define es_board_info_rpc_init_zero              {0, {software_version_get_rpc_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define adm1177_tel_get_res_pl_current0_tag      1
#define adm1177_tel_get_res_pl_voltage0_tag      2
#define ams_tel_get_res_pl_pl_temp_tag           1
#define ams_tel_get_res_pl_ps_temp_tag           2
#define ams_tel_get_res_pl_remote_temp_tag       3
#define ams_tel_get_res_pl_psmgtravcc_tag        4
#define ams_tel_get_res_pl_psmgtravtt_tag        5
#define ams_tel_get_res_pl_vccams_tag            6
#define ams_tel_get_res_pl_vccaux_tag            7
#define ams_tel_get_res_pl_vccbram_tag           8
#define ams_tel_get_res_pl_vccint_tag            9
#define ams_tel_get_res_pl_vccplaux_tag          10
#define ams_tel_get_res_pl_vccplintfp_tag        11
#define ams_tel_get_res_pl_vccpsaux_tag          12
#define ams_tel_get_res_pl_vcc_psbatt_tag        13
#define ams_tel_get_res_pl_vccpsddr_tag          14
#define ams_tel_get_res_pl_vcc_psddrpll_tag      15
#define ams_tel_get_res_pl_vccpsintfp_tag        16
#define ams_tel_get_res_pl_vccpsintfpddr_tag     17
#define ams_tel_get_res_pl_vccpsintlp_tag        18
#define ams_tel_get_res_pl_vccpsio0_tag          19
#define ams_tel_get_res_pl_vccpsio1_tag          20
#define ams_tel_get_res_pl_vccpsio2_tag          21
#define ams_tel_get_res_pl_vccpsio3_tag          22
#define ams_tel_get_res_pl_vcc_pspll0_tag        23
#define ams_tel_get_res_pl_vccvrefn_tag          24
#define ams_tel_get_res_pl_vccvrefp_tag          25
#define es_adm1177_tel_get_req_hdr_tag           1
#define es_ams_tel_get_req_hdr_tag               1
#define es_reset_reason_get_req_hdr_tag          1
#define es_serial_get_req_hdr_tag                1
#define es_system_info_get_req_hdr_tag           1
#define reset_reason_get_res_pl_reset_reason_tag 1
#define reset_reason_get_res_pl_uptime_tag       2
#define serial_get_res_pl_machine_tag            1
#define serial_get_res_pl_serial_number_tag      2
#define software_version_get_req_pl_module_tag   1
#define software_version_get_res_pl_branch_tag   1
#define software_version_get_res_pl_sha_tag      2
#define software_version_get_res_pl_clean_state_tag 3
#define software_version_get_res_pl_date_tag     4
#define system_info_get_res_pl_disk_total_tag    1
#define system_info_get_res_pl_disk_used_tag     2
#define system_info_get_res_pl_disk_free_tag     3
#define system_info_get_res_pl_load_avg_1_tag    4
#define system_info_get_res_pl_load_avg_5_tag    5
#define system_info_get_res_pl_load_avg_15_tag   6
#define system_info_get_res_pl_cpu_freq_tag      7
#define system_info_get_res_pl_cpu_ctx_sw_tag    8
#define system_info_get_res_pl_cpu_irqs_tag      9
#define system_info_get_res_pl_boot_time_tag     10
#define es_adm1177_tel_get_res_hdr_tag           1
#define es_adm1177_tel_get_res_pl_tag            2
#define es_ams_tel_get_res_hdr_tag               1
#define es_ams_tel_get_res_pl_tag                2
#define es_reset_reason_get_res_hdr_tag          1
#define es_reset_reason_get_res_pl_tag           2
#define es_serial_get_res_hdr_tag                1
#define es_serial_get_res_pl_tag                 2
#define es_software_version_get_req_hdr_tag      1
#define es_software_version_get_req_pl_tag       2
#define es_software_version_get_res_hdr_tag      1
#define es_software_version_get_res_pl_tag       2
#define es_system_info_get_res_hdr_tag           1
#define es_system_info_get_res_pl_tag            2
#define adm1177_tel_get_rpc_req_tag              1
#define adm1177_tel_get_rpc_res_tag              2
#define ams_tel_get_rpc_req_tag                  1
#define ams_tel_get_rpc_res_tag                  2
#define reset_reason_get_rpc_req_tag             1
#define reset_reason_get_rpc_res_tag             2
#define serial_get_rpc_req_tag                   1
#define serial_get_rpc_res_tag                   2
#define software_version_get_rpc_req_tag         1
#define software_version_get_rpc_res_tag         2
#define system_info_get_rpc_req_tag              1
#define system_info_get_rpc_res_tag              2
#define es_board_info_rpc_software_version_get_tag 1
#define es_board_info_rpc_system_info_get_tag    2
#define es_board_info_rpc_adm1177_tel_get_tag    3
#define es_board_info_rpc_ams_tel_get_tag        4
#define es_board_info_rpc_serial_get_tag         5
#define es_board_info_rpc_reset_reason_get_tag   6

/* Struct field encoding specification for nanopb */
#define software_version_get_req_pl_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   module,            1)
#define software_version_get_req_pl_CALLBACK NULL
#define software_version_get_req_pl_DEFAULT (const pb_byte_t*)"\x0a\x0d\x65\x73\x2d\x6d\x69\x64\x64\x6c\x65\x77\x61\x72\x65\x00"

#define es_software_version_get_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pl,                2)
#define es_software_version_get_req_CALLBACK NULL
#define es_software_version_get_req_DEFAULT NULL
#define es_software_version_get_req_hdr_MSGTYPE request_hdr
#define es_software_version_get_req_pl_MSGTYPE software_version_get_req_pl

#define software_version_get_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   branch,            1) \
X(a, STATIC,   OPTIONAL, STRING,   sha,               2) \
X(a, STATIC,   OPTIONAL, STRING,   clean_state,       3) \
X(a, STATIC,   OPTIONAL, STRING,   date,              4)
#define software_version_get_res_pl_CALLBACK NULL
#define software_version_get_res_pl_DEFAULT NULL

#define es_software_version_get_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pl,                2)
#define es_software_version_get_res_CALLBACK NULL
#define es_software_version_get_res_DEFAULT NULL
#define es_software_version_get_res_hdr_MSGTYPE response_hdr
#define es_software_version_get_res_pl_MSGTYPE software_version_get_res_pl

#define software_version_get_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define software_version_get_rpc_CALLBACK NULL
#define software_version_get_rpc_DEFAULT NULL
#define software_version_get_rpc_payload_req_MSGTYPE es_software_version_get_req
#define software_version_get_rpc_payload_res_MSGTYPE es_software_version_get_res

#define es_system_info_get_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_system_info_get_req_CALLBACK NULL
#define es_system_info_get_req_DEFAULT NULL
#define es_system_info_get_req_hdr_MSGTYPE request_hdr

#define system_info_get_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT64,    disk_total,        1) \
X(a, STATIC,   OPTIONAL, INT64,    disk_used,         2) \
X(a, STATIC,   OPTIONAL, INT64,    disk_free,         3) \
X(a, STATIC,   OPTIONAL, FLOAT,    load_avg_1,        4) \
X(a, STATIC,   OPTIONAL, FLOAT,    load_avg_5,        5) \
X(a, STATIC,   OPTIONAL, FLOAT,    load_avg_15,       6) \
X(a, STATIC,   OPTIONAL, FLOAT,    cpu_freq,          7) \
X(a, STATIC,   OPTIONAL, INT64,    cpu_ctx_sw,        8) \
X(a, STATIC,   OPTIONAL, INT64,    cpu_irqs,          9) \
X(a, STATIC,   OPTIONAL, STRING,   boot_time,        10)
#define system_info_get_res_pl_CALLBACK NULL
#define system_info_get_res_pl_DEFAULT NULL

#define es_system_info_get_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pl,                2)
#define es_system_info_get_res_CALLBACK NULL
#define es_system_info_get_res_DEFAULT NULL
#define es_system_info_get_res_hdr_MSGTYPE response_hdr
#define es_system_info_get_res_pl_MSGTYPE system_info_get_res_pl

#define system_info_get_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define system_info_get_rpc_CALLBACK NULL
#define system_info_get_rpc_DEFAULT NULL
#define system_info_get_rpc_payload_req_MSGTYPE es_system_info_get_req
#define system_info_get_rpc_payload_res_MSGTYPE es_system_info_get_res

#define es_adm1177_tel_get_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_adm1177_tel_get_req_CALLBACK NULL
#define es_adm1177_tel_get_req_DEFAULT NULL
#define es_adm1177_tel_get_req_hdr_MSGTYPE request_hdr

#define adm1177_tel_get_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, DOUBLE,   current0,          1) \
X(a, STATIC,   OPTIONAL, DOUBLE,   voltage0,          2)
#define adm1177_tel_get_res_pl_CALLBACK NULL
#define adm1177_tel_get_res_pl_DEFAULT NULL

#define es_adm1177_tel_get_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pl,                2)
#define es_adm1177_tel_get_res_CALLBACK NULL
#define es_adm1177_tel_get_res_DEFAULT NULL
#define es_adm1177_tel_get_res_hdr_MSGTYPE response_hdr
#define es_adm1177_tel_get_res_pl_MSGTYPE adm1177_tel_get_res_pl

#define adm1177_tel_get_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define adm1177_tel_get_rpc_CALLBACK NULL
#define adm1177_tel_get_rpc_DEFAULT NULL
#define adm1177_tel_get_rpc_payload_req_MSGTYPE es_adm1177_tel_get_req
#define adm1177_tel_get_rpc_payload_res_MSGTYPE es_adm1177_tel_get_res

#define es_ams_tel_get_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_ams_tel_get_req_CALLBACK NULL
#define es_ams_tel_get_req_DEFAULT NULL
#define es_ams_tel_get_req_hdr_MSGTYPE request_hdr

#define ams_tel_get_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, DOUBLE,   pl_temp,           1) \
X(a, STATIC,   OPTIONAL, DOUBLE,   ps_temp,           2) \
X(a, STATIC,   OPTIONAL, DOUBLE,   remote_temp,       3) \
X(a, STATIC,   OPTIONAL, DOUBLE,   psmgtravcc,        4) \
X(a, STATIC,   OPTIONAL, DOUBLE,   psmgtravtt,        5) \
X(a, STATIC,   OPTIONAL, DOUBLE,   vccams,            6) \
X(a, STATIC,   OPTIONAL, DOUBLE,   vccaux,            7) \
X(a, STATIC,   OPTIONAL, DOUBLE,   vccbram,           8) \
X(a, STATIC,   OPTIONAL, DOUBLE,   vccint,            9) \
X(a, STATIC,   OPTIONAL, DOUBLE,   vccplaux,         10) \
X(a, STATIC,   OPTIONAL, DOUBLE,   vccplintfp,       11) \
X(a, STATIC,   OPTIONAL, DOUBLE,   vccpsaux,         12) \
X(a, STATIC,   OPTIONAL, DOUBLE,   vcc_psbatt,       13) \
X(a, STATIC,   OPTIONAL, DOUBLE,   vccpsddr,         14) \
X(a, STATIC,   OPTIONAL, DOUBLE,   vcc_psddrpll,     15) \
X(a, STATIC,   OPTIONAL, DOUBLE,   vccpsintfp,       16) \
X(a, STATIC,   OPTIONAL, DOUBLE,   vccpsintfpddr,    17) \
X(a, STATIC,   OPTIONAL, DOUBLE,   vccpsintlp,       18) \
X(a, STATIC,   OPTIONAL, DOUBLE,   vccpsio0,         19) \
X(a, STATIC,   OPTIONAL, DOUBLE,   vccpsio1,         20) \
X(a, STATIC,   OPTIONAL, DOUBLE,   vccpsio2,         21) \
X(a, STATIC,   OPTIONAL, DOUBLE,   vccpsio3,         22) \
X(a, STATIC,   OPTIONAL, DOUBLE,   vcc_pspll0,       23) \
X(a, STATIC,   OPTIONAL, DOUBLE,   vccvrefn,         24) \
X(a, STATIC,   OPTIONAL, DOUBLE,   vccvrefp,         25)
#define ams_tel_get_res_pl_CALLBACK NULL
#define ams_tel_get_res_pl_DEFAULT NULL

#define es_ams_tel_get_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pl,                2)
#define es_ams_tel_get_res_CALLBACK NULL
#define es_ams_tel_get_res_DEFAULT NULL
#define es_ams_tel_get_res_hdr_MSGTYPE response_hdr
#define es_ams_tel_get_res_pl_MSGTYPE ams_tel_get_res_pl

#define ams_tel_get_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define ams_tel_get_rpc_CALLBACK NULL
#define ams_tel_get_rpc_DEFAULT NULL
#define ams_tel_get_rpc_payload_req_MSGTYPE es_ams_tel_get_req
#define ams_tel_get_rpc_payload_res_MSGTYPE es_ams_tel_get_res

#define es_serial_get_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_serial_get_req_CALLBACK NULL
#define es_serial_get_req_DEFAULT NULL
#define es_serial_get_req_hdr_MSGTYPE request_hdr

#define serial_get_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   machine,           1) \
X(a, STATIC,   OPTIONAL, STRING,   serial_number,     2)
#define serial_get_res_pl_CALLBACK NULL
#define serial_get_res_pl_DEFAULT NULL

#define es_serial_get_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pl,                2)
#define es_serial_get_res_CALLBACK NULL
#define es_serial_get_res_DEFAULT NULL
#define es_serial_get_res_hdr_MSGTYPE response_hdr
#define es_serial_get_res_pl_MSGTYPE serial_get_res_pl

#define serial_get_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define serial_get_rpc_CALLBACK NULL
#define serial_get_rpc_DEFAULT NULL
#define serial_get_rpc_payload_req_MSGTYPE es_serial_get_req
#define serial_get_rpc_payload_res_MSGTYPE es_serial_get_res

#define es_reset_reason_get_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_reset_reason_get_req_CALLBACK NULL
#define es_reset_reason_get_req_DEFAULT NULL
#define es_reset_reason_get_req_hdr_MSGTYPE request_hdr

#define reset_reason_get_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   reset_reason,      1) \
X(a, STATIC,   OPTIONAL, FLOAT,    uptime,            2)
#define reset_reason_get_res_pl_CALLBACK NULL
#define reset_reason_get_res_pl_DEFAULT NULL

#define es_reset_reason_get_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pl,                2)
#define es_reset_reason_get_res_CALLBACK NULL
#define es_reset_reason_get_res_DEFAULT NULL
#define es_reset_reason_get_res_hdr_MSGTYPE response_hdr
#define es_reset_reason_get_res_pl_MSGTYPE reset_reason_get_res_pl

#define reset_reason_get_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define reset_reason_get_rpc_CALLBACK NULL
#define reset_reason_get_rpc_DEFAULT NULL
#define reset_reason_get_rpc_payload_req_MSGTYPE es_reset_reason_get_req
#define reset_reason_get_rpc_payload_res_MSGTYPE es_reset_reason_get_res

#define es_board_info_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,software_version_get,rpc.software_version_get),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,system_info_get,rpc.system_info_get),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,adm1177_tel_get,rpc.adm1177_tel_get),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,ams_tel_get,rpc.ams_tel_get),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,serial_get,rpc.serial_get),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,reset_reason_get,rpc.reset_reason_get),   6)
#define es_board_info_rpc_CALLBACK NULL
#define es_board_info_rpc_DEFAULT NULL
#define es_board_info_rpc_rpc_software_version_get_MSGTYPE software_version_get_rpc
#define es_board_info_rpc_rpc_system_info_get_MSGTYPE system_info_get_rpc
#define es_board_info_rpc_rpc_adm1177_tel_get_MSGTYPE adm1177_tel_get_rpc
#define es_board_info_rpc_rpc_ams_tel_get_MSGTYPE ams_tel_get_rpc
#define es_board_info_rpc_rpc_serial_get_MSGTYPE serial_get_rpc
#define es_board_info_rpc_rpc_reset_reason_get_MSGTYPE reset_reason_get_rpc

extern const pb_msgdesc_t software_version_get_req_pl_msg;
extern const pb_msgdesc_t es_software_version_get_req_msg;
extern const pb_msgdesc_t software_version_get_res_pl_msg;
extern const pb_msgdesc_t es_software_version_get_res_msg;
extern const pb_msgdesc_t software_version_get_rpc_msg;
extern const pb_msgdesc_t es_system_info_get_req_msg;
extern const pb_msgdesc_t system_info_get_res_pl_msg;
extern const pb_msgdesc_t es_system_info_get_res_msg;
extern const pb_msgdesc_t system_info_get_rpc_msg;
extern const pb_msgdesc_t es_adm1177_tel_get_req_msg;
extern const pb_msgdesc_t adm1177_tel_get_res_pl_msg;
extern const pb_msgdesc_t es_adm1177_tel_get_res_msg;
extern const pb_msgdesc_t adm1177_tel_get_rpc_msg;
extern const pb_msgdesc_t es_ams_tel_get_req_msg;
extern const pb_msgdesc_t ams_tel_get_res_pl_msg;
extern const pb_msgdesc_t es_ams_tel_get_res_msg;
extern const pb_msgdesc_t ams_tel_get_rpc_msg;
extern const pb_msgdesc_t es_serial_get_req_msg;
extern const pb_msgdesc_t serial_get_res_pl_msg;
extern const pb_msgdesc_t es_serial_get_res_msg;
extern const pb_msgdesc_t serial_get_rpc_msg;
extern const pb_msgdesc_t es_reset_reason_get_req_msg;
extern const pb_msgdesc_t reset_reason_get_res_pl_msg;
extern const pb_msgdesc_t es_reset_reason_get_res_msg;
extern const pb_msgdesc_t reset_reason_get_rpc_msg;
extern const pb_msgdesc_t es_board_info_rpc_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define software_version_get_req_pl_fields &software_version_get_req_pl_msg
#define es_software_version_get_req_fields &es_software_version_get_req_msg
#define software_version_get_res_pl_fields &software_version_get_res_pl_msg
#define es_software_version_get_res_fields &es_software_version_get_res_msg
#define software_version_get_rpc_fields &software_version_get_rpc_msg
#define es_system_info_get_req_fields &es_system_info_get_req_msg
#define system_info_get_res_pl_fields &system_info_get_res_pl_msg
#define es_system_info_get_res_fields &es_system_info_get_res_msg
#define system_info_get_rpc_fields &system_info_get_rpc_msg
#define es_adm1177_tel_get_req_fields &es_adm1177_tel_get_req_msg
#define adm1177_tel_get_res_pl_fields &adm1177_tel_get_res_pl_msg
#define es_adm1177_tel_get_res_fields &es_adm1177_tel_get_res_msg
#define adm1177_tel_get_rpc_fields &adm1177_tel_get_rpc_msg
#define es_ams_tel_get_req_fields &es_ams_tel_get_req_msg
#define ams_tel_get_res_pl_fields &ams_tel_get_res_pl_msg
#define es_ams_tel_get_res_fields &es_ams_tel_get_res_msg
#define ams_tel_get_rpc_fields &ams_tel_get_rpc_msg
#define es_serial_get_req_fields &es_serial_get_req_msg
#define serial_get_res_pl_fields &serial_get_res_pl_msg
#define es_serial_get_res_fields &es_serial_get_res_msg
#define serial_get_rpc_fields &serial_get_rpc_msg
#define es_reset_reason_get_req_fields &es_reset_reason_get_req_msg
#define reset_reason_get_res_pl_fields &reset_reason_get_res_pl_msg
#define es_reset_reason_get_res_fields &es_reset_reason_get_res_msg
#define reset_reason_get_rpc_fields &reset_reason_get_rpc_msg
#define es_board_info_rpc_fields &es_board_info_rpc_msg

/* Maximum encoded size of messages (where known) */
#define adm1177_tel_get_res_pl_size              18
#define adm1177_tel_get_rpc_size                 1076
#define ams_tel_get_res_pl_size                  235
#define ams_tel_get_rpc_size                     1294
#define es_adm1177_tel_get_req_size              24
#define es_adm1177_tel_get_res_size              1073
#define es_ams_tel_get_req_size                  24
#define es_ams_tel_get_res_size                  1291
#define es_board_info_rpc_size                   1297
#define es_reset_reason_get_req_size             24
#define es_reset_reason_get_res_size             1141
#define es_serial_get_req_size                   24
#define es_serial_get_res_size                   1177
#define es_software_version_get_req_size         87
#define es_software_version_get_res_size         1198
#define es_system_info_get_req_size              24
#define es_system_info_get_res_size              1252
#define reset_reason_get_res_pl_size             86
#define reset_reason_get_rpc_size                1144
#define serial_get_res_pl_size                   122
#define serial_get_rpc_size                      1180
#define software_version_get_req_pl_size         61
#define software_version_get_res_pl_size         142
#define software_version_get_rpc_size            1201
#define system_info_get_res_pl_size              196
#define system_info_get_rpc_size                 1255

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
