/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_ES_COMMON_TYPES_PB_H_INCLUDED
#define PB_ES_COMMON_TYPES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/***< Status of operation enum*/
typedef enum _ES_STATUS { 
    ES_STATUS_OK = 0, /**< Operation was successful*/
    ES_STATUS_ERR = 1 /**< Operation failed*/
} ES_STATUS;

/***< Parameter flag*/
typedef enum _ES_HAS_PARAM { 
    ES_HAS_PARAM_NO = 0, /**< Do not send parameter*/
    ES_HAS_PARAM_YES = 1 /**< Send parameter*/
} ES_HAS_PARAM;

/* Struct definitions */
/**ES service request header*/
typedef struct _request_hdr { 
    uint64_t id; /**< Request ID*/
    uint64_t timestamp; /**< Packet Timestamp*/
} request_hdr;

/**ES service response header*/
typedef struct _response_hdr { 
    uint64_t id; /**< Response ID*/
    uint64_t timestamp; /**< Packet Timestamp*/
    ES_STATUS stat; /**< Response status*/
    bool has_err_msg;
    char err_msg[1024]; /**< Error message*/
} response_hdr;


/* Helper constants for enums */
#define _ES_STATUS_MIN ES_STATUS_OK
#define _ES_STATUS_MAX ES_STATUS_ERR
#define _ES_STATUS_ARRAYSIZE ((ES_STATUS)(ES_STATUS_ERR+1))

#define _ES_HAS_PARAM_MIN ES_HAS_PARAM_NO
#define _ES_HAS_PARAM_MAX ES_HAS_PARAM_YES
#define _ES_HAS_PARAM_ARRAYSIZE ((ES_HAS_PARAM)(ES_HAS_PARAM_YES+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define request_hdr_init_default                 {0, 0}
#define response_hdr_init_default                {0, 0, _ES_STATUS_MIN, false, ""}
#define request_hdr_init_zero                    {0, 0}
#define response_hdr_init_zero                   {0, 0, _ES_STATUS_MIN, false, ""}

/* Field tags (for use in manual encoding/decoding) */
#define request_hdr_id_tag                       1
#define request_hdr_timestamp_tag                2
#define response_hdr_id_tag                      1
#define response_hdr_timestamp_tag               2
#define response_hdr_stat_tag                    3
#define response_hdr_err_msg_tag                 4

/* Struct field encoding specification for nanopb */
#define request_hdr_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   id,                1) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         2)
#define request_hdr_CALLBACK NULL
#define request_hdr_DEFAULT NULL

#define response_hdr_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   id,                1) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         2) \
X(a, STATIC,   REQUIRED, UENUM,    stat,              3) \
X(a, STATIC,   OPTIONAL, STRING,   err_msg,           4)
#define response_hdr_CALLBACK NULL
#define response_hdr_DEFAULT NULL

extern const pb_msgdesc_t request_hdr_msg;
extern const pb_msgdesc_t response_hdr_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define request_hdr_fields &request_hdr_msg
#define response_hdr_fields &response_hdr_msg

/* Maximum encoded size of messages (where known) */
#define request_hdr_size                         22
#define response_hdr_size                        1050

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
