/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_ES_FILE_TRANSFER_PB_H_INCLUDED
#define PB_ES_FILE_TRANSFER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/***<  ES FTP Packet operation code*/
typedef enum _ES_FTP_OPCODE { 
    ES_FTP_OPCODE_RRQ = 1, /**< Read request*/
    ES_FTP_OPCODE_WRQ = 2, /**< Write request*/
    ES_FTP_OPCODE_DATA = 3, /**< Data packet*/
    ES_FTP_OPCODE_ACK = 4, /**< Acknowledgment*/
    ES_FTP_OPCODE_ERROR = 5, /**< Error*/
    ES_FTP_OPCODE_OACK = 6 /**< Options acknowledgment*/
} ES_FTP_OPCODE;

/***<  ES FTP Packet errror code*/
typedef enum _ES_FTP_ERRCODE { 
    ES_FTP_ERRCODE_UNDEF = 0, /**< Not defined, see error message (if any).*/
    ES_FTP_ERRCODE_NOT_FOUND = 1, /**< File not found*/
    ES_FTP_ERRCODE_ACCESS = 2, /**< Access violation*/
    ES_FTP_ERRCODE_IO = 3, /**< Disk full or allocation exceeded*/
    ES_FTP_ERRCODE_ILLEGAL_OP = 4, /**< Illegal TFTP operation*/
    ES_FTP_ERRCODE_UNKNOWN_ID = 5, /**< Unknow transfer ID*/
    ES_FTP_ERRCODE_FILE_EXISTS = 6, /**< File already exists*/
    ES_FTP_ERRCODE_NO_USER = 7, /**< No such user*/
    ES_FTP_ERRCODE_OPTIONS_NOT_SUPPORTED = 8 /**< Options not supported*/
} ES_FTP_ERRCODE;

/* Struct definitions */
/**ES FTP Acknowledgment packet*/
typedef struct _es_ftp_ack_pkt { 
    uint32_t block; /**< Block ID*/
    uint64_t data_size; /**< Size of the transfered data*/
} es_ftp_ack_pkt;

typedef PB_BYTES_ARRAY_T(9000) es_ftp_data_pkt_data_t;
/**ES FTP Data packet*/
typedef struct _es_ftp_data_pkt { 
    uint32_t block; /**< Block ID*/
    es_ftp_data_pkt_data_t data; /**< Data*/
} es_ftp_data_pkt;

/**ES FTP Error packet*/
typedef struct _es_ftp_err_pkt { 
    ES_FTP_ERRCODE errcode; /**< Error code*/
    bool has_err_msg;
    char err_msg[120]; /**< Error message*/
} es_ftp_err_pkt;

/**ES FTP RRQ/WRQ packet*/
typedef struct _es_ftp_rrq_wrq_pkt { 
    char filename[120]; /**< File name*/
    char mode[120]; /**< Mode*/
    uint32_t blksize; /**< Block size*/
    uint64_t data_size; /**< data size*/
} es_ftp_rrq_wrq_pkt;

/**ES FTP packet*/
typedef struct _es_ftp_pkt { 
    uint32_t stream_id; /**< Stream ID*/
    ES_FTP_OPCODE opcode; /**< Packet operation field*/
    pb_size_t which_pkt;
    union {
        es_ftp_rrq_wrq_pkt rrq_wrq_pkt;
        es_ftp_data_pkt data_pkt;
        es_ftp_ack_pkt ack_pkt;
        es_ftp_err_pkt err_pkt;
    } pkt; 
} es_ftp_pkt;


/* Helper constants for enums */
#define _ES_FTP_OPCODE_MIN ES_FTP_OPCODE_RRQ
#define _ES_FTP_OPCODE_MAX ES_FTP_OPCODE_OACK
#define _ES_FTP_OPCODE_ARRAYSIZE ((ES_FTP_OPCODE)(ES_FTP_OPCODE_OACK+1))

#define _ES_FTP_ERRCODE_MIN ES_FTP_ERRCODE_UNDEF
#define _ES_FTP_ERRCODE_MAX ES_FTP_ERRCODE_OPTIONS_NOT_SUPPORTED
#define _ES_FTP_ERRCODE_ARRAYSIZE ((ES_FTP_ERRCODE)(ES_FTP_ERRCODE_OPTIONS_NOT_SUPPORTED+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define es_ftp_rrq_wrq_pkt_init_default          {"", "", 0, 0}
#define es_ftp_data_pkt_init_default             {0, {0, {0}}}
#define es_ftp_ack_pkt_init_default              {0, 0}
#define es_ftp_err_pkt_init_default              {_ES_FTP_ERRCODE_MIN, false, ""}
#define es_ftp_pkt_init_default                  {0, _ES_FTP_OPCODE_MIN, 0, {es_ftp_rrq_wrq_pkt_init_default}}
#define es_ftp_rrq_wrq_pkt_init_zero             {"", "", 0, 0}
#define es_ftp_data_pkt_init_zero                {0, {0, {0}}}
#define es_ftp_ack_pkt_init_zero                 {0, 0}
#define es_ftp_err_pkt_init_zero                 {_ES_FTP_ERRCODE_MIN, false, ""}
#define es_ftp_pkt_init_zero                     {0, _ES_FTP_OPCODE_MIN, 0, {es_ftp_rrq_wrq_pkt_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define es_ftp_ack_pkt_block_tag                 1
#define es_ftp_ack_pkt_data_size_tag             2
#define es_ftp_data_pkt_block_tag                1
#define es_ftp_data_pkt_data_tag                 2
#define es_ftp_err_pkt_errcode_tag               1
#define es_ftp_err_pkt_err_msg_tag               2
#define es_ftp_rrq_wrq_pkt_filename_tag          1
#define es_ftp_rrq_wrq_pkt_mode_tag              3
#define es_ftp_rrq_wrq_pkt_blksize_tag           4
#define es_ftp_rrq_wrq_pkt_data_size_tag         5
#define es_ftp_pkt_stream_id_tag                 1
#define es_ftp_pkt_opcode_tag                    2
#define es_ftp_pkt_rrq_wrq_pkt_tag               3
#define es_ftp_pkt_data_pkt_tag                  4
#define es_ftp_pkt_ack_pkt_tag                   5
#define es_ftp_pkt_err_pkt_tag                   6

/* Struct field encoding specification for nanopb */
#define es_ftp_rrq_wrq_pkt_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   filename,          1) \
X(a, STATIC,   REQUIRED, STRING,   mode,              3) \
X(a, STATIC,   REQUIRED, UINT32,   blksize,           4) \
X(a, STATIC,   REQUIRED, UINT64,   data_size,         5)
#define es_ftp_rrq_wrq_pkt_CALLBACK NULL
#define es_ftp_rrq_wrq_pkt_DEFAULT NULL

#define es_ftp_data_pkt_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   block,             1) \
X(a, STATIC,   REQUIRED, BYTES,    data,              2)
#define es_ftp_data_pkt_CALLBACK NULL
#define es_ftp_data_pkt_DEFAULT NULL

#define es_ftp_ack_pkt_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   block,             1) \
X(a, STATIC,   REQUIRED, UINT64,   data_size,         2)
#define es_ftp_ack_pkt_CALLBACK NULL
#define es_ftp_ack_pkt_DEFAULT NULL

#define es_ftp_err_pkt_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    errcode,           1) \
X(a, STATIC,   OPTIONAL, STRING,   err_msg,           2)
#define es_ftp_err_pkt_CALLBACK NULL
#define es_ftp_err_pkt_DEFAULT NULL

#define es_ftp_pkt_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   stream_id,         1) \
X(a, STATIC,   REQUIRED, UENUM,    opcode,            2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (pkt,rrq_wrq_pkt,pkt.rrq_wrq_pkt),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (pkt,data_pkt,pkt.data_pkt),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (pkt,ack_pkt,pkt.ack_pkt),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (pkt,err_pkt,pkt.err_pkt),   6)
#define es_ftp_pkt_CALLBACK NULL
#define es_ftp_pkt_DEFAULT (const pb_byte_t*)"\x10\x01\x00"
#define es_ftp_pkt_pkt_rrq_wrq_pkt_MSGTYPE es_ftp_rrq_wrq_pkt
#define es_ftp_pkt_pkt_data_pkt_MSGTYPE es_ftp_data_pkt
#define es_ftp_pkt_pkt_ack_pkt_MSGTYPE es_ftp_ack_pkt
#define es_ftp_pkt_pkt_err_pkt_MSGTYPE es_ftp_err_pkt

extern const pb_msgdesc_t es_ftp_rrq_wrq_pkt_msg;
extern const pb_msgdesc_t es_ftp_data_pkt_msg;
extern const pb_msgdesc_t es_ftp_ack_pkt_msg;
extern const pb_msgdesc_t es_ftp_err_pkt_msg;
extern const pb_msgdesc_t es_ftp_pkt_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define es_ftp_rrq_wrq_pkt_fields &es_ftp_rrq_wrq_pkt_msg
#define es_ftp_data_pkt_fields &es_ftp_data_pkt_msg
#define es_ftp_ack_pkt_fields &es_ftp_ack_pkt_msg
#define es_ftp_err_pkt_fields &es_ftp_err_pkt_msg
#define es_ftp_pkt_fields &es_ftp_pkt_msg

/* Maximum encoded size of messages (where known) */
#define es_ftp_ack_pkt_size                      17
#define es_ftp_data_pkt_size                     9009
#define es_ftp_err_pkt_size                      123
#define es_ftp_pkt_size                          9020
#define es_ftp_rrq_wrq_pkt_size                  259

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
