/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_ES_IPRIUM_DVB_S2_PB_H_INCLUDED
#define PB_ES_IPRIUM_DVB_S2_PB_H_INCLUDED
#include <pb.h>
#include "es_common_types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/**TS GEN block configuration*/
typedef struct _clk_wiz_get_res_pl { 
    bool has_base_scaler_divclk_divide;
    uint32_t base_scaler_divclk_divide; /**< Eight bit divide value applied to all output clocks.*/
    bool has_base_scaler_clkfbout_mult;
    uint32_t base_scaler_clkfbout_mult; /**< Integer part of multiplie*/
    bool has_clk0_divider;
    uint32_t clk0_divider; /**< Clock0 Divider*/
    bool has_clk1_divider;
    uint32_t clk1_divider; /**< Clock1 Divider*/
    bool has_clk2_divider;
    uint32_t clk2_divider; /**< Clock2 Divider*/
    bool has_clk3_divider;
    uint32_t clk3_divider; /**< Clock3 Divider*/
} clk_wiz_get_res_pl;

/**Request payload*/
typedef struct _clk_wiz_set_req_pl { 
    bool has_base_scaler_divclk_divide;
    uint32_t base_scaler_divclk_divide; /**< Eight bit divide value applied to all output clocks.*/
    bool has_base_scaler_clkfbout_mult;
    uint32_t base_scaler_clkfbout_mult; /**< Integer part of multiplie*/
    bool has_clk0_divider;
    uint32_t clk0_divider; /**< Clock0 Divider*/
    bool has_clk1_divider;
    uint32_t clk1_divider; /**< Clock1 Divider*/
    bool has_clk2_divider;
    uint32_t clk2_divider; /**< Clock2 Divider*/
    bool has_clk3_divider;
    uint32_t clk3_divider; /**< Clock3 Divider*/
} clk_wiz_set_req_pl;

/**DVB S2 modulator get response payload*/
typedef struct _dvb_s2_core0_get_res_pl { 
    bool has_modcod;
    char modcod[16]; /**< Modulation code*/
    bool has_pilot;
    char pilot[16]; /**< Pilots*/
    bool has_roll_off;
    char roll_off[16]; /**< Roll-off factor*/
    bool has_fec_frame;
    char fec_frame[16]; /**< FEC frame size*/
    bool has_vlsnr_mode;
    char vlsnr_mode[16]; /**< DVB S2X VLSNR Modes VLSNR_[0-5]*/
    bool has_igain;
    uint32_t igain; /**< gain in dB*/
    bool has_isample;
    uint32_t isample; /**< Symbol rate [bauds]*/
    bool has_ifreq;
    uint64_t ifreq; /**< Nominal frequency [Hz] (in RF DAC case)*/
    bool has_input_stream;
    char input_stream[10]; /**< Input stream type*/
    bool has_frame_encap_enable;
    bool frame_encap_enable; /**< Enable/Disable internal input stream encapsulation*/
    bool has_frame_aes256_gcm_enable;
    bool frame_aes256_gcm_enable; /**< Enable/Disable AES256 GCM encryption. (Not implemented TBD)*/
} dvb_s2_core0_get_res_pl;

/**DVB S2 modulator set request payload*/
typedef struct _dvb_s2_core0_set_req_pl { 
    bool has_modcod;
    char modcod[16]; /**< Modulation code*/
    bool has_pilot;
    char pilot[16]; /**< Pilots*/
    bool has_roll_off;
    char roll_off[16]; /**< Roll-off factor*/
    bool has_fec_frame;
    char fec_frame[16]; /**< FEC frame size*/
    bool has_vlsnr_mode;
    char vlsnr_mode[16]; /**< DVB S2X VLSNR Modes VLSNR_[0-5]*/
    bool has_igain;
    uint32_t igain; /**< gain in dB*/
    bool has_isample;
    uint32_t isample; /**< Symbol rate [bauds]*/
    bool has_ifreq;
    uint64_t ifreq; /**< Nominal frequency [Hz] (in RF DAC case)*/
    bool has_input_stream;
    char input_stream[10]; /**< Input stream type*/
    bool has_frame_encap_enable;
    bool frame_encap_enable; /**< Enable/Disable internal input stream encapsulation*/
    bool has_frame_aes256_gcm_enable;
    bool frame_aes256_gcm_enable; /**< Enable/Disable AES256 GCM encryption. (Not implemented TBD)*/
} dvb_s2_core0_set_req_pl;

/**Retrieve the configuration of the TS GEN block request*/
typedef struct _es_clk_wiz_get_req { 
    request_hdr hdr; /**< Request header*/
} es_clk_wiz_get_req;

/**Configure Xilinx's Clock Wizard core response*/
typedef struct _es_clk_wiz_set_res { 
    response_hdr hdr; /**< Response header*/
} es_clk_wiz_set_res;

/**DVB S2 modulator get request*/
typedef struct _es_dvb_s2_core0_get_req { 
    request_hdr hdr; /**< Request header*/
} es_dvb_s2_core0_get_req;

/**DVB S2 modulator set response*/
typedef struct _es_dvb_s2_core0_set_res { 
    response_hdr hdr; /**< Response header*/
} es_dvb_s2_core0_set_res;

/**Retrieve the configuration of the TS GEN block request*/
typedef struct _es_tsgen_get_req { 
    request_hdr hdr; /**< Request header*/
} es_tsgen_get_req;

/**Configure TS GEN PRBS core response*/
typedef struct _es_tsgen_set_res { 
    response_hdr hdr; /**< Response header*/
} es_tsgen_set_res;

/**XBAR get request*/
typedef struct _es_xbar_get_req { 
    request_hdr hdr; /**< Request header*/
} es_xbar_get_req;

/**XBAR IP Core set response*/
typedef struct _es_xbar_set_res { 
    response_hdr hdr; /**< Response header*/
} es_xbar_set_res;

/**TS GEN block configuration*/
typedef struct _tsgen_get_res_pl { 
    bool has_overwrite_mode;
    char overwrite_mode[12]; /**< Overwrite output data with contanst pattern or ramp sequence*/
    bool has_tsgen_imode;
    bool tsgen_imode; /**< Enable/Disable imode*/
    bool has_transport_stream_mode;
    char transport_stream_mode[6]; /**< Transport stream type*/
    bool has_overwrite_data;
    uint32_t overwrite_data; /**< Constant pattern used with overwrite_mode=Pattern*/
    bool has_overwrite_ts_pid;
    uint32_t overwrite_ts_pid; /**< MPEG TS stream PID*/
    bool has_tm_gse_size;
    bool tm_gse_size; /**< Enable GSE frame length modifications*/
    bool has_tm_gse_frame_size_overwrite;
    uint32_t tm_gse_frame_size_overwrite; /**< GSE frame size (applicable when tm_gse_size=true)*/
    bool has_tm_data_rate_div;
    uint32_t tm_data_rate_div; /**< Data rate divider*/
    bool has_gse_protocol_type;
    uint32_t gse_protocol_type; /**< Next protocol encapsulation*/
} tsgen_get_res_pl;

/**TS generator request payload*/
typedef struct _tsgen_set_req_pl { 
    bool has_overwrite_mode;
    char overwrite_mode[12]; /**< Overwrite output data with contanst pattern or ramp sequence*/
    bool has_tsgen_imode;
    bool tsgen_imode; /**< Enable/Disable imode*/
    bool has_transport_stream_mode;
    char transport_stream_mode[6]; /**< Transport stream type*/
    bool has_overwrite_data;
    uint32_t overwrite_data; /**< Constant pattern used with overwrite_mode=Pattern*/
    bool has_overwrite_ts_pid;
    uint32_t overwrite_ts_pid; /**< MPEG TS stream PID*/
    bool has_tm_gse_size;
    bool tm_gse_size; /**< Enable GSE frame length modifications*/
    bool has_tm_gse_frame_size_overwrite;
    uint32_t tm_gse_frame_size_overwrite; /**< GSE frame size (applicable when tm_gse_size=true)*/
    bool has_tm_data_rate_div;
    uint32_t tm_data_rate_div; /**< Data rate divider*/
    bool has_gse_protocol_type;
    uint32_t gse_protocol_type; /**< Next protocol encapsulation*/
} tsgen_set_req_pl;

/**XBAR get response payload*/
typedef struct _xbar_get_res_pl { 
    bool has_dvbs2x_modulator_input;
    char dvbs2x_modulator_input[20]; /**< DVBS2X Modulator Input*/
} xbar_get_res_pl;

/**XBAR IP Core set request payload*/
typedef struct _xbar_set_req_pl { 
    bool has_dvbs2x_modulator_input;
    char dvbs2x_modulator_input[30]; /**< Select input data source for the DVBS2X Modulator*/
} xbar_set_req_pl;

/**Retrieve the configuration of the TS GEN block response*/
typedef struct _es_clk_wiz_get_res { 
    response_hdr hdr; /**< Response header*/
    bool has_pl;
    clk_wiz_get_res_pl pl; /**< Response payload*/
} es_clk_wiz_get_res;

/**Configure Xilinx's Clock Wizard core request*/
typedef struct _es_clk_wiz_set_req { 
    request_hdr hdr; /**< Request header*/
    clk_wiz_set_req_pl pl; /**< Request payload*/
} es_clk_wiz_set_req;

/**DVB S2 modulator get response*/
typedef struct _es_dvb_s2_core0_get_res { 
    response_hdr hdr; /**< Response header*/
    bool has_pl;
    dvb_s2_core0_get_res_pl pl; /**< Response payload*/
} es_dvb_s2_core0_get_res;

/**DVB S2 modulator set request*/
typedef struct _es_dvb_s2_core0_set_req { 
    request_hdr hdr; /**< Request header*/
    dvb_s2_core0_set_req_pl pl; /**< Request payload*/
} es_dvb_s2_core0_set_req;

/**Retrieve the configuration of the TS GEN block response*/
typedef struct _es_tsgen_get_res { 
    response_hdr hdr; /**< Response header*/
    bool has_pl;
    tsgen_get_res_pl pl; /**< Response payload*/
} es_tsgen_get_res;

/**Configure TS GEN PRBS core request*/
typedef struct _es_tsgen_set_req { 
    request_hdr hdr; /**< Request header*/
    tsgen_set_req_pl pl; /**< Request payload*/
} es_tsgen_set_req;

/**XBAR get response*/
typedef struct _es_xbar_get_res { 
    response_hdr hdr; /**< Response header*/
    bool has_pl;
    xbar_get_res_pl pl; /**< Response payload*/
} es_xbar_get_res;

/**XBAR IP Core set request*/
typedef struct _es_xbar_set_req { 
    request_hdr hdr; /**< Request header*/
    xbar_set_req_pl pl; /**< Request payload*/
} es_xbar_set_req;

/**Retrieve the configuration of the TS GEN block*/
typedef struct _clk_wiz_get_rpc { 
    pb_size_t which_payload;
    union {
        es_clk_wiz_get_req req;
        es_clk_wiz_get_res res;
    } payload; 
} clk_wiz_get_rpc;

/**Configure Xilinx's Clock Wizard core*/
typedef struct _clk_wiz_set_rpc { 
    pb_size_t which_payload;
    union {
        es_clk_wiz_set_req req;
        es_clk_wiz_set_res res;
    } payload; 
} clk_wiz_set_rpc;

/**Retrieve the configuration of the DVB S2 IP core0*/
typedef struct _dvb_s2_core0_get_rpc { 
    pb_size_t which_payload;
    union {
        es_dvb_s2_core0_get_req req;
        es_dvb_s2_core0_get_res res;
    } payload; 
} dvb_s2_core0_get_rpc;

/**DVB S2 modulator set RPC*/
typedef struct _dvb_s2_core0_set_rpc { 
    pb_size_t which_payload;
    union {
        es_dvb_s2_core0_set_req req;
        es_dvb_s2_core0_set_res res;
    } payload; 
} dvb_s2_core0_set_rpc;

/**Retrieve the configuration of the TS GEN block*/
typedef struct _tsgen_get_rpc { 
    pb_size_t which_payload;
    union {
        es_tsgen_get_req req;
        es_tsgen_get_res res;
    } payload; 
} tsgen_get_rpc;

/**Configure TS GEN PRBS core*/
typedef struct _tsgen_set_rpc { 
    pb_size_t which_payload;
    union {
        es_tsgen_set_req req;
        es_tsgen_set_res res;
    } payload; 
} tsgen_set_rpc;

/**Retrieve the configuration of the XBAR IP core*/
typedef struct _xbar_get_rpc { 
    pb_size_t which_payload;
    union {
        es_xbar_get_req req;
        es_xbar_get_res res;
    } payload; 
} xbar_get_rpc;

/**Configure XBAR IP core*/
typedef struct _xbar_set_rpc { 
    pb_size_t which_payload;
    union {
        es_xbar_set_req req;
        es_xbar_set_res res;
    } payload; 
} xbar_set_rpc;

/**ES Iprium DVBS2 RPCs*/
typedef struct _es_iprium_dvb_s2_rpc { 
    pb_size_t which_rpc;
    union {
        dvb_s2_core0_set_rpc dvb_s2_core0_set;
        dvb_s2_core0_get_rpc dvb_s2_core0_get;
        tsgen_set_rpc tsgen_set;
        tsgen_get_rpc tsgen_get;
        clk_wiz_set_rpc clk_wiz_set;
        clk_wiz_get_rpc clk_wiz_get;
        xbar_set_rpc xbar_set;
        xbar_get_rpc xbar_get;
    } rpc; 
} es_iprium_dvb_s2_rpc;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define dvb_s2_core0_set_req_pl_init_default     {false, "32APSK3/4", false, "off", false, "0,20", false, "normal", false, "VLSNR_0", false, 0u, false, 0u, false, 0ull, false, "TS", false, true, false, false}
#define es_dvb_s2_core0_set_req_init_default     {request_hdr_init_default, dvb_s2_core0_set_req_pl_init_default}
#define es_dvb_s2_core0_set_res_init_default     {response_hdr_init_default}
#define dvb_s2_core0_set_rpc_init_default        {0, {es_dvb_s2_core0_set_req_init_default}}
#define es_dvb_s2_core0_get_req_init_default     {request_hdr_init_default}
#define dvb_s2_core0_get_res_pl_init_default     {false, "", false, "", false, "", false, "", false, "", false, 0, false, 0, false, 0, false, "", false, 0, false, 0}
#define es_dvb_s2_core0_get_res_init_default     {response_hdr_init_default, false, dvb_s2_core0_get_res_pl_init_default}
#define dvb_s2_core0_get_rpc_init_default        {0, {es_dvb_s2_core0_get_req_init_default}}
#define tsgen_set_req_pl_init_default            {false, "Disabled", false, false, false, "TS", false, 0u, false, 7951u, false, false, false, 1430u, false, 0u, false, 2048u}
#define es_tsgen_set_req_init_default            {request_hdr_init_default, tsgen_set_req_pl_init_default}
#define es_tsgen_set_res_init_default            {response_hdr_init_default}
#define tsgen_set_rpc_init_default               {0, {es_tsgen_set_req_init_default}}
#define es_tsgen_get_req_init_default            {request_hdr_init_default}
#define tsgen_get_res_pl_init_default            {false, "", false, 0, false, "", false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define es_tsgen_get_res_init_default            {response_hdr_init_default, false, tsgen_get_res_pl_init_default}
#define tsgen_get_rpc_init_default               {0, {es_tsgen_get_req_init_default}}
#define clk_wiz_set_req_pl_init_default          {false, 1u, false, 10u, false, 20u, false, 2u, false, 10u, false, 5u}
#define es_clk_wiz_set_req_init_default          {request_hdr_init_default, clk_wiz_set_req_pl_init_default}
#define es_clk_wiz_set_res_init_default          {response_hdr_init_default}
#define clk_wiz_set_rpc_init_default             {0, {es_clk_wiz_set_req_init_default}}
#define es_clk_wiz_get_req_init_default          {request_hdr_init_default}
#define clk_wiz_get_res_pl_init_default          {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define es_clk_wiz_get_res_init_default          {response_hdr_init_default, false, clk_wiz_get_res_pl_init_default}
#define clk_wiz_get_rpc_init_default             {0, {es_clk_wiz_get_req_init_default}}
#define xbar_set_req_pl_init_default             {false, "INTERNAL_DATA"}
#define es_xbar_set_req_init_default             {request_hdr_init_default, xbar_set_req_pl_init_default}
#define es_xbar_set_res_init_default             {response_hdr_init_default}
#define xbar_set_rpc_init_default                {0, {es_xbar_set_req_init_default}}
#define es_xbar_get_req_init_default             {request_hdr_init_default}
#define xbar_get_res_pl_init_default             {false, ""}
#define es_xbar_get_res_init_default             {response_hdr_init_default, false, xbar_get_res_pl_init_default}
#define xbar_get_rpc_init_default                {0, {es_xbar_get_req_init_default}}
#define es_iprium_dvb_s2_rpc_init_default        {0, {dvb_s2_core0_set_rpc_init_default}}
#define dvb_s2_core0_set_req_pl_init_zero        {false, "", false, "", false, "", false, "", false, "", false, 0, false, 0, false, 0, false, "", false, 0, false, 0}
#define es_dvb_s2_core0_set_req_init_zero        {request_hdr_init_zero, dvb_s2_core0_set_req_pl_init_zero}
#define es_dvb_s2_core0_set_res_init_zero        {response_hdr_init_zero}
#define dvb_s2_core0_set_rpc_init_zero           {0, {es_dvb_s2_core0_set_req_init_zero}}
#define es_dvb_s2_core0_get_req_init_zero        {request_hdr_init_zero}
#define dvb_s2_core0_get_res_pl_init_zero        {false, "", false, "", false, "", false, "", false, "", false, 0, false, 0, false, 0, false, "", false, 0, false, 0}
#define es_dvb_s2_core0_get_res_init_zero        {response_hdr_init_zero, false, dvb_s2_core0_get_res_pl_init_zero}
#define dvb_s2_core0_get_rpc_init_zero           {0, {es_dvb_s2_core0_get_req_init_zero}}
#define tsgen_set_req_pl_init_zero               {false, "", false, 0, false, "", false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define es_tsgen_set_req_init_zero               {request_hdr_init_zero, tsgen_set_req_pl_init_zero}
#define es_tsgen_set_res_init_zero               {response_hdr_init_zero}
#define tsgen_set_rpc_init_zero                  {0, {es_tsgen_set_req_init_zero}}
#define es_tsgen_get_req_init_zero               {request_hdr_init_zero}
#define tsgen_get_res_pl_init_zero               {false, "", false, 0, false, "", false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define es_tsgen_get_res_init_zero               {response_hdr_init_zero, false, tsgen_get_res_pl_init_zero}
#define tsgen_get_rpc_init_zero                  {0, {es_tsgen_get_req_init_zero}}
#define clk_wiz_set_req_pl_init_zero             {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define es_clk_wiz_set_req_init_zero             {request_hdr_init_zero, clk_wiz_set_req_pl_init_zero}
#define es_clk_wiz_set_res_init_zero             {response_hdr_init_zero}
#define clk_wiz_set_rpc_init_zero                {0, {es_clk_wiz_set_req_init_zero}}
#define es_clk_wiz_get_req_init_zero             {request_hdr_init_zero}
#define clk_wiz_get_res_pl_init_zero             {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define es_clk_wiz_get_res_init_zero             {response_hdr_init_zero, false, clk_wiz_get_res_pl_init_zero}
#define clk_wiz_get_rpc_init_zero                {0, {es_clk_wiz_get_req_init_zero}}
#define xbar_set_req_pl_init_zero                {false, ""}
#define es_xbar_set_req_init_zero                {request_hdr_init_zero, xbar_set_req_pl_init_zero}
#define es_xbar_set_res_init_zero                {response_hdr_init_zero}
#define xbar_set_rpc_init_zero                   {0, {es_xbar_set_req_init_zero}}
#define es_xbar_get_req_init_zero                {request_hdr_init_zero}
#define xbar_get_res_pl_init_zero                {false, ""}
#define es_xbar_get_res_init_zero                {response_hdr_init_zero, false, xbar_get_res_pl_init_zero}
#define xbar_get_rpc_init_zero                   {0, {es_xbar_get_req_init_zero}}
#define es_iprium_dvb_s2_rpc_init_zero           {0, {dvb_s2_core0_set_rpc_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define clk_wiz_get_res_pl_base_scaler_divclk_divide_tag 1
#define clk_wiz_get_res_pl_base_scaler_clkfbout_mult_tag 2
#define clk_wiz_get_res_pl_clk0_divider_tag      3
#define clk_wiz_get_res_pl_clk1_divider_tag      4
#define clk_wiz_get_res_pl_clk2_divider_tag      5
#define clk_wiz_get_res_pl_clk3_divider_tag      6
#define clk_wiz_set_req_pl_base_scaler_divclk_divide_tag 1
#define clk_wiz_set_req_pl_base_scaler_clkfbout_mult_tag 2
#define clk_wiz_set_req_pl_clk0_divider_tag      3
#define clk_wiz_set_req_pl_clk1_divider_tag      4
#define clk_wiz_set_req_pl_clk2_divider_tag      5
#define clk_wiz_set_req_pl_clk3_divider_tag      6
#define dvb_s2_core0_get_res_pl_modcod_tag       1
#define dvb_s2_core0_get_res_pl_pilot_tag        2
#define dvb_s2_core0_get_res_pl_roll_off_tag     3
#define dvb_s2_core0_get_res_pl_fec_frame_tag    4
#define dvb_s2_core0_get_res_pl_vlsnr_mode_tag   5
#define dvb_s2_core0_get_res_pl_igain_tag        6
#define dvb_s2_core0_get_res_pl_isample_tag      7
#define dvb_s2_core0_get_res_pl_ifreq_tag        8
#define dvb_s2_core0_get_res_pl_input_stream_tag 9
#define dvb_s2_core0_get_res_pl_frame_encap_enable_tag 10
#define dvb_s2_core0_get_res_pl_frame_aes256_gcm_enable_tag 11
#define dvb_s2_core0_set_req_pl_modcod_tag       1
#define dvb_s2_core0_set_req_pl_pilot_tag        2
#define dvb_s2_core0_set_req_pl_roll_off_tag     3
#define dvb_s2_core0_set_req_pl_fec_frame_tag    4
#define dvb_s2_core0_set_req_pl_vlsnr_mode_tag   5
#define dvb_s2_core0_set_req_pl_igain_tag        6
#define dvb_s2_core0_set_req_pl_isample_tag      7
#define dvb_s2_core0_set_req_pl_ifreq_tag        8
#define dvb_s2_core0_set_req_pl_input_stream_tag 9
#define dvb_s2_core0_set_req_pl_frame_encap_enable_tag 10
#define dvb_s2_core0_set_req_pl_frame_aes256_gcm_enable_tag 11
#define es_clk_wiz_get_req_hdr_tag               1
#define es_clk_wiz_set_res_hdr_tag               1
#define es_dvb_s2_core0_get_req_hdr_tag          1
#define es_dvb_s2_core0_set_res_hdr_tag          1
#define es_tsgen_get_req_hdr_tag                 1
#define es_tsgen_set_res_hdr_tag                 1
#define es_xbar_get_req_hdr_tag                  1
#define es_xbar_set_res_hdr_tag                  1
#define tsgen_get_res_pl_overwrite_mode_tag      1
#define tsgen_get_res_pl_tsgen_imode_tag         2
#define tsgen_get_res_pl_transport_stream_mode_tag 3
#define tsgen_get_res_pl_overwrite_data_tag      4
#define tsgen_get_res_pl_overwrite_ts_pid_tag    5
#define tsgen_get_res_pl_tm_gse_size_tag         7
#define tsgen_get_res_pl_tm_gse_frame_size_overwrite_tag 8
#define tsgen_get_res_pl_tm_data_rate_div_tag    9
#define tsgen_get_res_pl_gse_protocol_type_tag   10
#define tsgen_set_req_pl_overwrite_mode_tag      1
#define tsgen_set_req_pl_tsgen_imode_tag         2
#define tsgen_set_req_pl_transport_stream_mode_tag 3
#define tsgen_set_req_pl_overwrite_data_tag      4
#define tsgen_set_req_pl_overwrite_ts_pid_tag    5
#define tsgen_set_req_pl_tm_gse_size_tag         8
#define tsgen_set_req_pl_tm_gse_frame_size_overwrite_tag 9
#define tsgen_set_req_pl_tm_data_rate_div_tag    10
#define tsgen_set_req_pl_gse_protocol_type_tag   11
#define xbar_get_res_pl_dvbs2x_modulator_input_tag 1
#define xbar_set_req_pl_dvbs2x_modulator_input_tag 1
#define es_clk_wiz_get_res_hdr_tag               1
#define es_clk_wiz_get_res_pl_tag                2
#define es_clk_wiz_set_req_hdr_tag               1
#define es_clk_wiz_set_req_pl_tag                2
#define es_dvb_s2_core0_get_res_hdr_tag          1
#define es_dvb_s2_core0_get_res_pl_tag           2
#define es_dvb_s2_core0_set_req_hdr_tag          1
#define es_dvb_s2_core0_set_req_pl_tag           2
#define es_tsgen_get_res_hdr_tag                 1
#define es_tsgen_get_res_pl_tag                  2
#define es_tsgen_set_req_hdr_tag                 1
#define es_tsgen_set_req_pl_tag                  2
#define es_xbar_get_res_hdr_tag                  1
#define es_xbar_get_res_pl_tag                   2
#define es_xbar_set_req_hdr_tag                  1
#define es_xbar_set_req_pl_tag                   2
#define clk_wiz_get_rpc_req_tag                  1
#define clk_wiz_get_rpc_res_tag                  2
#define clk_wiz_set_rpc_req_tag                  1
#define clk_wiz_set_rpc_res_tag                  2
#define dvb_s2_core0_get_rpc_req_tag             1
#define dvb_s2_core0_get_rpc_res_tag             2
#define dvb_s2_core0_set_rpc_req_tag             1
#define dvb_s2_core0_set_rpc_res_tag             2
#define tsgen_get_rpc_req_tag                    1
#define tsgen_get_rpc_res_tag                    2
#define tsgen_set_rpc_req_tag                    1
#define tsgen_set_rpc_res_tag                    2
#define xbar_get_rpc_req_tag                     1
#define xbar_get_rpc_res_tag                     2
#define xbar_set_rpc_req_tag                     1
#define xbar_set_rpc_res_tag                     2
#define es_iprium_dvb_s2_rpc_dvb_s2_core0_set_tag 1
#define es_iprium_dvb_s2_rpc_dvb_s2_core0_get_tag 2
#define es_iprium_dvb_s2_rpc_tsgen_set_tag       3
#define es_iprium_dvb_s2_rpc_tsgen_get_tag       4
#define es_iprium_dvb_s2_rpc_clk_wiz_set_tag     5
#define es_iprium_dvb_s2_rpc_clk_wiz_get_tag     6
#define es_iprium_dvb_s2_rpc_xbar_set_tag        7
#define es_iprium_dvb_s2_rpc_xbar_get_tag        8

/* Struct field encoding specification for nanopb */
#define dvb_s2_core0_set_req_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   modcod,            1) \
X(a, STATIC,   OPTIONAL, STRING,   pilot,             2) \
X(a, STATIC,   OPTIONAL, STRING,   roll_off,          3) \
X(a, STATIC,   OPTIONAL, STRING,   fec_frame,         4) \
X(a, STATIC,   OPTIONAL, STRING,   vlsnr_mode,        5) \
X(a, STATIC,   OPTIONAL, UINT32,   igain,             6) \
X(a, STATIC,   OPTIONAL, UINT32,   isample,           7) \
X(a, STATIC,   OPTIONAL, UINT64,   ifreq,             8) \
X(a, STATIC,   OPTIONAL, STRING,   input_stream,      9) \
X(a, STATIC,   OPTIONAL, BOOL,     frame_encap_enable,  10) \
X(a, STATIC,   OPTIONAL, BOOL,     frame_aes256_gcm_enable,  11)
#define dvb_s2_core0_set_req_pl_CALLBACK NULL
#define dvb_s2_core0_set_req_pl_DEFAULT (const pb_byte_t*)"\x0a\x09\x33\x32\x41\x50\x53\x4b\x33\x2f\x34\x12\x03\x6f\x66\x66\x1a\x04\x30\x2c\x32\x30\x22\x06\x6e\x6f\x72\x6d\x61\x6c\x2a\x07\x56\x4c\x53\x4e\x52\x5f\x30\x30\x00\x38\x00\x40\x00\x4a\x02\x54\x53\x50\x01\x58\x00\x00"

#define es_dvb_s2_core0_set_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_dvb_s2_core0_set_req_CALLBACK NULL
#define es_dvb_s2_core0_set_req_DEFAULT NULL
#define es_dvb_s2_core0_set_req_hdr_MSGTYPE request_hdr
#define es_dvb_s2_core0_set_req_pl_MSGTYPE dvb_s2_core0_set_req_pl

#define es_dvb_s2_core0_set_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_dvb_s2_core0_set_res_CALLBACK NULL
#define es_dvb_s2_core0_set_res_DEFAULT NULL
#define es_dvb_s2_core0_set_res_hdr_MSGTYPE response_hdr

#define dvb_s2_core0_set_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define dvb_s2_core0_set_rpc_CALLBACK NULL
#define dvb_s2_core0_set_rpc_DEFAULT NULL
#define dvb_s2_core0_set_rpc_payload_req_MSGTYPE es_dvb_s2_core0_set_req
#define dvb_s2_core0_set_rpc_payload_res_MSGTYPE es_dvb_s2_core0_set_res

#define es_dvb_s2_core0_get_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_dvb_s2_core0_get_req_CALLBACK NULL
#define es_dvb_s2_core0_get_req_DEFAULT NULL
#define es_dvb_s2_core0_get_req_hdr_MSGTYPE request_hdr

#define dvb_s2_core0_get_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   modcod,            1) \
X(a, STATIC,   OPTIONAL, STRING,   pilot,             2) \
X(a, STATIC,   OPTIONAL, STRING,   roll_off,          3) \
X(a, STATIC,   OPTIONAL, STRING,   fec_frame,         4) \
X(a, STATIC,   OPTIONAL, STRING,   vlsnr_mode,        5) \
X(a, STATIC,   OPTIONAL, UINT32,   igain,             6) \
X(a, STATIC,   OPTIONAL, UINT32,   isample,           7) \
X(a, STATIC,   OPTIONAL, UINT64,   ifreq,             8) \
X(a, STATIC,   OPTIONAL, STRING,   input_stream,      9) \
X(a, STATIC,   OPTIONAL, BOOL,     frame_encap_enable,  10) \
X(a, STATIC,   OPTIONAL, BOOL,     frame_aes256_gcm_enable,  11)
#define dvb_s2_core0_get_res_pl_CALLBACK NULL
#define dvb_s2_core0_get_res_pl_DEFAULT NULL

#define es_dvb_s2_core0_get_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pl,                2)
#define es_dvb_s2_core0_get_res_CALLBACK NULL
#define es_dvb_s2_core0_get_res_DEFAULT NULL
#define es_dvb_s2_core0_get_res_hdr_MSGTYPE response_hdr
#define es_dvb_s2_core0_get_res_pl_MSGTYPE dvb_s2_core0_get_res_pl

#define dvb_s2_core0_get_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define dvb_s2_core0_get_rpc_CALLBACK NULL
#define dvb_s2_core0_get_rpc_DEFAULT NULL
#define dvb_s2_core0_get_rpc_payload_req_MSGTYPE es_dvb_s2_core0_get_req
#define dvb_s2_core0_get_rpc_payload_res_MSGTYPE es_dvb_s2_core0_get_res

#define tsgen_set_req_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   overwrite_mode,    1) \
X(a, STATIC,   OPTIONAL, BOOL,     tsgen_imode,       2) \
X(a, STATIC,   OPTIONAL, STRING,   transport_stream_mode,   3) \
X(a, STATIC,   OPTIONAL, FIXED32,  overwrite_data,    4) \
X(a, STATIC,   OPTIONAL, FIXED32,  overwrite_ts_pid,   5) \
X(a, STATIC,   OPTIONAL, BOOL,     tm_gse_size,       8) \
X(a, STATIC,   OPTIONAL, FIXED32,  tm_gse_frame_size_overwrite,   9) \
X(a, STATIC,   OPTIONAL, FIXED32,  tm_data_rate_div,  10) \
X(a, STATIC,   OPTIONAL, FIXED32,  gse_protocol_type,  11)
#define tsgen_set_req_pl_CALLBACK NULL
#define tsgen_set_req_pl_DEFAULT (const pb_byte_t*)"\x0a\x08\x44\x69\x73\x61\x62\x6c\x65\x64\x10\x00\x1a\x02\x54\x53\x25\x00\x00\x00\x00\x2d\x0f\x1f\x00\x00\x40\x00\x4d\x96\x05\x00\x00\x55\x00\x00\x00\x00\x5d\x00\x08\x00\x00\x00"

#define es_tsgen_set_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_tsgen_set_req_CALLBACK NULL
#define es_tsgen_set_req_DEFAULT NULL
#define es_tsgen_set_req_hdr_MSGTYPE request_hdr
#define es_tsgen_set_req_pl_MSGTYPE tsgen_set_req_pl

#define es_tsgen_set_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_tsgen_set_res_CALLBACK NULL
#define es_tsgen_set_res_DEFAULT NULL
#define es_tsgen_set_res_hdr_MSGTYPE response_hdr

#define tsgen_set_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define tsgen_set_rpc_CALLBACK NULL
#define tsgen_set_rpc_DEFAULT NULL
#define tsgen_set_rpc_payload_req_MSGTYPE es_tsgen_set_req
#define tsgen_set_rpc_payload_res_MSGTYPE es_tsgen_set_res

#define es_tsgen_get_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_tsgen_get_req_CALLBACK NULL
#define es_tsgen_get_req_DEFAULT NULL
#define es_tsgen_get_req_hdr_MSGTYPE request_hdr

#define tsgen_get_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   overwrite_mode,    1) \
X(a, STATIC,   OPTIONAL, BOOL,     tsgen_imode,       2) \
X(a, STATIC,   OPTIONAL, STRING,   transport_stream_mode,   3) \
X(a, STATIC,   OPTIONAL, FIXED32,  overwrite_data,    4) \
X(a, STATIC,   OPTIONAL, FIXED32,  overwrite_ts_pid,   5) \
X(a, STATIC,   OPTIONAL, BOOL,     tm_gse_size,       7) \
X(a, STATIC,   OPTIONAL, FIXED32,  tm_gse_frame_size_overwrite,   8) \
X(a, STATIC,   OPTIONAL, FIXED32,  tm_data_rate_div,   9) \
X(a, STATIC,   OPTIONAL, FIXED32,  gse_protocol_type,  10)
#define tsgen_get_res_pl_CALLBACK NULL
#define tsgen_get_res_pl_DEFAULT NULL

#define es_tsgen_get_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pl,                2)
#define es_tsgen_get_res_CALLBACK NULL
#define es_tsgen_get_res_DEFAULT NULL
#define es_tsgen_get_res_hdr_MSGTYPE response_hdr
#define es_tsgen_get_res_pl_MSGTYPE tsgen_get_res_pl

#define tsgen_get_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define tsgen_get_rpc_CALLBACK NULL
#define tsgen_get_rpc_DEFAULT NULL
#define tsgen_get_rpc_payload_req_MSGTYPE es_tsgen_get_req
#define tsgen_get_rpc_payload_res_MSGTYPE es_tsgen_get_res

#define clk_wiz_set_req_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FIXED32,  base_scaler_divclk_divide,   1) \
X(a, STATIC,   OPTIONAL, FIXED32,  base_scaler_clkfbout_mult,   2) \
X(a, STATIC,   OPTIONAL, FIXED32,  clk0_divider,      3) \
X(a, STATIC,   OPTIONAL, FIXED32,  clk1_divider,      4) \
X(a, STATIC,   OPTIONAL, FIXED32,  clk2_divider,      5) \
X(a, STATIC,   OPTIONAL, FIXED32,  clk3_divider,      6)
#define clk_wiz_set_req_pl_CALLBACK NULL
#define clk_wiz_set_req_pl_DEFAULT (const pb_byte_t*)"\x0d\x01\x00\x00\x00\x15\x0a\x00\x00\x00\x1d\x14\x00\x00\x00\x25\x02\x00\x00\x00\x2d\x0a\x00\x00\x00\x35\x05\x00\x00\x00\x00"

#define es_clk_wiz_set_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_clk_wiz_set_req_CALLBACK NULL
#define es_clk_wiz_set_req_DEFAULT NULL
#define es_clk_wiz_set_req_hdr_MSGTYPE request_hdr
#define es_clk_wiz_set_req_pl_MSGTYPE clk_wiz_set_req_pl

#define es_clk_wiz_set_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_clk_wiz_set_res_CALLBACK NULL
#define es_clk_wiz_set_res_DEFAULT NULL
#define es_clk_wiz_set_res_hdr_MSGTYPE response_hdr

#define clk_wiz_set_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define clk_wiz_set_rpc_CALLBACK NULL
#define clk_wiz_set_rpc_DEFAULT NULL
#define clk_wiz_set_rpc_payload_req_MSGTYPE es_clk_wiz_set_req
#define clk_wiz_set_rpc_payload_res_MSGTYPE es_clk_wiz_set_res

#define es_clk_wiz_get_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_clk_wiz_get_req_CALLBACK NULL
#define es_clk_wiz_get_req_DEFAULT NULL
#define es_clk_wiz_get_req_hdr_MSGTYPE request_hdr

#define clk_wiz_get_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FIXED32,  base_scaler_divclk_divide,   1) \
X(a, STATIC,   OPTIONAL, FIXED32,  base_scaler_clkfbout_mult,   2) \
X(a, STATIC,   OPTIONAL, FIXED32,  clk0_divider,      3) \
X(a, STATIC,   OPTIONAL, FIXED32,  clk1_divider,      4) \
X(a, STATIC,   OPTIONAL, FIXED32,  clk2_divider,      5) \
X(a, STATIC,   OPTIONAL, FIXED32,  clk3_divider,      6)
#define clk_wiz_get_res_pl_CALLBACK NULL
#define clk_wiz_get_res_pl_DEFAULT NULL

#define es_clk_wiz_get_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pl,                2)
#define es_clk_wiz_get_res_CALLBACK NULL
#define es_clk_wiz_get_res_DEFAULT NULL
#define es_clk_wiz_get_res_hdr_MSGTYPE response_hdr
#define es_clk_wiz_get_res_pl_MSGTYPE clk_wiz_get_res_pl

#define clk_wiz_get_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define clk_wiz_get_rpc_CALLBACK NULL
#define clk_wiz_get_rpc_DEFAULT NULL
#define clk_wiz_get_rpc_payload_req_MSGTYPE es_clk_wiz_get_req
#define clk_wiz_get_rpc_payload_res_MSGTYPE es_clk_wiz_get_res

#define xbar_set_req_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   dvbs2x_modulator_input,   1)
#define xbar_set_req_pl_CALLBACK NULL
#define xbar_set_req_pl_DEFAULT (const pb_byte_t*)"\x0a\x0d\x49\x4e\x54\x45\x52\x4e\x41\x4c\x5f\x44\x41\x54\x41\x00"

#define es_xbar_set_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_xbar_set_req_CALLBACK NULL
#define es_xbar_set_req_DEFAULT NULL
#define es_xbar_set_req_hdr_MSGTYPE request_hdr
#define es_xbar_set_req_pl_MSGTYPE xbar_set_req_pl

#define es_xbar_set_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_xbar_set_res_CALLBACK NULL
#define es_xbar_set_res_DEFAULT NULL
#define es_xbar_set_res_hdr_MSGTYPE response_hdr

#define xbar_set_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define xbar_set_rpc_CALLBACK NULL
#define xbar_set_rpc_DEFAULT NULL
#define xbar_set_rpc_payload_req_MSGTYPE es_xbar_set_req
#define xbar_set_rpc_payload_res_MSGTYPE es_xbar_set_res

#define es_xbar_get_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_xbar_get_req_CALLBACK NULL
#define es_xbar_get_req_DEFAULT NULL
#define es_xbar_get_req_hdr_MSGTYPE request_hdr

#define xbar_get_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   dvbs2x_modulator_input,   1)
#define xbar_get_res_pl_CALLBACK NULL
#define xbar_get_res_pl_DEFAULT NULL

#define es_xbar_get_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pl,                2)
#define es_xbar_get_res_CALLBACK NULL
#define es_xbar_get_res_DEFAULT NULL
#define es_xbar_get_res_hdr_MSGTYPE response_hdr
#define es_xbar_get_res_pl_MSGTYPE xbar_get_res_pl

#define xbar_get_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define xbar_get_rpc_CALLBACK NULL
#define xbar_get_rpc_DEFAULT NULL
#define xbar_get_rpc_payload_req_MSGTYPE es_xbar_get_req
#define xbar_get_rpc_payload_res_MSGTYPE es_xbar_get_res

#define es_iprium_dvb_s2_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,dvb_s2_core0_set,rpc.dvb_s2_core0_set),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,dvb_s2_core0_get,rpc.dvb_s2_core0_get),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,tsgen_set,rpc.tsgen_set),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,tsgen_get,rpc.tsgen_get),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,clk_wiz_set,rpc.clk_wiz_set),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,clk_wiz_get,rpc.clk_wiz_get),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,xbar_set,rpc.xbar_set),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,xbar_get,rpc.xbar_get),   8)
#define es_iprium_dvb_s2_rpc_CALLBACK NULL
#define es_iprium_dvb_s2_rpc_DEFAULT NULL
#define es_iprium_dvb_s2_rpc_rpc_dvb_s2_core0_set_MSGTYPE dvb_s2_core0_set_rpc
#define es_iprium_dvb_s2_rpc_rpc_dvb_s2_core0_get_MSGTYPE dvb_s2_core0_get_rpc
#define es_iprium_dvb_s2_rpc_rpc_tsgen_set_MSGTYPE tsgen_set_rpc
#define es_iprium_dvb_s2_rpc_rpc_tsgen_get_MSGTYPE tsgen_get_rpc
#define es_iprium_dvb_s2_rpc_rpc_clk_wiz_set_MSGTYPE clk_wiz_set_rpc
#define es_iprium_dvb_s2_rpc_rpc_clk_wiz_get_MSGTYPE clk_wiz_get_rpc
#define es_iprium_dvb_s2_rpc_rpc_xbar_set_MSGTYPE xbar_set_rpc
#define es_iprium_dvb_s2_rpc_rpc_xbar_get_MSGTYPE xbar_get_rpc

extern const pb_msgdesc_t dvb_s2_core0_set_req_pl_msg;
extern const pb_msgdesc_t es_dvb_s2_core0_set_req_msg;
extern const pb_msgdesc_t es_dvb_s2_core0_set_res_msg;
extern const pb_msgdesc_t dvb_s2_core0_set_rpc_msg;
extern const pb_msgdesc_t es_dvb_s2_core0_get_req_msg;
extern const pb_msgdesc_t dvb_s2_core0_get_res_pl_msg;
extern const pb_msgdesc_t es_dvb_s2_core0_get_res_msg;
extern const pb_msgdesc_t dvb_s2_core0_get_rpc_msg;
extern const pb_msgdesc_t tsgen_set_req_pl_msg;
extern const pb_msgdesc_t es_tsgen_set_req_msg;
extern const pb_msgdesc_t es_tsgen_set_res_msg;
extern const pb_msgdesc_t tsgen_set_rpc_msg;
extern const pb_msgdesc_t es_tsgen_get_req_msg;
extern const pb_msgdesc_t tsgen_get_res_pl_msg;
extern const pb_msgdesc_t es_tsgen_get_res_msg;
extern const pb_msgdesc_t tsgen_get_rpc_msg;
extern const pb_msgdesc_t clk_wiz_set_req_pl_msg;
extern const pb_msgdesc_t es_clk_wiz_set_req_msg;
extern const pb_msgdesc_t es_clk_wiz_set_res_msg;
extern const pb_msgdesc_t clk_wiz_set_rpc_msg;
extern const pb_msgdesc_t es_clk_wiz_get_req_msg;
extern const pb_msgdesc_t clk_wiz_get_res_pl_msg;
extern const pb_msgdesc_t es_clk_wiz_get_res_msg;
extern const pb_msgdesc_t clk_wiz_get_rpc_msg;
extern const pb_msgdesc_t xbar_set_req_pl_msg;
extern const pb_msgdesc_t es_xbar_set_req_msg;
extern const pb_msgdesc_t es_xbar_set_res_msg;
extern const pb_msgdesc_t xbar_set_rpc_msg;
extern const pb_msgdesc_t es_xbar_get_req_msg;
extern const pb_msgdesc_t xbar_get_res_pl_msg;
extern const pb_msgdesc_t es_xbar_get_res_msg;
extern const pb_msgdesc_t xbar_get_rpc_msg;
extern const pb_msgdesc_t es_iprium_dvb_s2_rpc_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define dvb_s2_core0_set_req_pl_fields &dvb_s2_core0_set_req_pl_msg
#define es_dvb_s2_core0_set_req_fields &es_dvb_s2_core0_set_req_msg
#define es_dvb_s2_core0_set_res_fields &es_dvb_s2_core0_set_res_msg
#define dvb_s2_core0_set_rpc_fields &dvb_s2_core0_set_rpc_msg
#define es_dvb_s2_core0_get_req_fields &es_dvb_s2_core0_get_req_msg
#define dvb_s2_core0_get_res_pl_fields &dvb_s2_core0_get_res_pl_msg
#define es_dvb_s2_core0_get_res_fields &es_dvb_s2_core0_get_res_msg
#define dvb_s2_core0_get_rpc_fields &dvb_s2_core0_get_rpc_msg
#define tsgen_set_req_pl_fields &tsgen_set_req_pl_msg
#define es_tsgen_set_req_fields &es_tsgen_set_req_msg
#define es_tsgen_set_res_fields &es_tsgen_set_res_msg
#define tsgen_set_rpc_fields &tsgen_set_rpc_msg
#define es_tsgen_get_req_fields &es_tsgen_get_req_msg
#define tsgen_get_res_pl_fields &tsgen_get_res_pl_msg
#define es_tsgen_get_res_fields &es_tsgen_get_res_msg
#define tsgen_get_rpc_fields &tsgen_get_rpc_msg
#define clk_wiz_set_req_pl_fields &clk_wiz_set_req_pl_msg
#define es_clk_wiz_set_req_fields &es_clk_wiz_set_req_msg
#define es_clk_wiz_set_res_fields &es_clk_wiz_set_res_msg
#define clk_wiz_set_rpc_fields &clk_wiz_set_rpc_msg
#define es_clk_wiz_get_req_fields &es_clk_wiz_get_req_msg
#define clk_wiz_get_res_pl_fields &clk_wiz_get_res_pl_msg
#define es_clk_wiz_get_res_fields &es_clk_wiz_get_res_msg
#define clk_wiz_get_rpc_fields &clk_wiz_get_rpc_msg
#define xbar_set_req_pl_fields &xbar_set_req_pl_msg
#define es_xbar_set_req_fields &es_xbar_set_req_msg
#define es_xbar_set_res_fields &es_xbar_set_res_msg
#define xbar_set_rpc_fields &xbar_set_rpc_msg
#define es_xbar_get_req_fields &es_xbar_get_req_msg
#define xbar_get_res_pl_fields &xbar_get_res_pl_msg
#define es_xbar_get_res_fields &es_xbar_get_res_msg
#define xbar_get_rpc_fields &xbar_get_rpc_msg
#define es_iprium_dvb_s2_rpc_fields &es_iprium_dvb_s2_rpc_msg

/* Maximum encoded size of messages (where known) */
#define clk_wiz_get_res_pl_size                  30
#define clk_wiz_get_rpc_size                     1088
#define clk_wiz_set_req_pl_size                  30
#define clk_wiz_set_rpc_size                     1056
#define dvb_s2_core0_get_res_pl_size             123
#define dvb_s2_core0_get_rpc_size                1181
#define dvb_s2_core0_set_req_pl_size             123
#define dvb_s2_core0_set_rpc_size                1056
#define es_clk_wiz_get_req_size                  24
#define es_clk_wiz_get_res_size                  1085
#define es_clk_wiz_set_req_size                  56
#define es_clk_wiz_set_res_size                  1053
#define es_dvb_s2_core0_get_req_size             24
#define es_dvb_s2_core0_get_res_size             1178
#define es_dvb_s2_core0_set_req_size             149
#define es_dvb_s2_core0_set_res_size             1053
#define es_iprium_dvb_s2_rpc_size                1184
#define es_tsgen_get_req_size                    24
#define es_tsgen_get_res_size                    1104
#define es_tsgen_set_req_size                    75
#define es_tsgen_set_res_size                    1053
#define es_xbar_get_req_size                     24
#define es_xbar_get_res_size                     1076
#define es_xbar_set_req_size                     57
#define es_xbar_set_res_size                     1053
#define tsgen_get_res_pl_size                    49
#define tsgen_get_rpc_size                       1107
#define tsgen_set_req_pl_size                    49
#define tsgen_set_rpc_size                       1056
#define xbar_get_res_pl_size                     21
#define xbar_get_rpc_size                        1079
#define xbar_set_req_pl_size                     31
#define xbar_set_rpc_size                        1056

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
