/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_ES_RCE_PB_H_INCLUDED
#define PB_ES_RCE_PB_H_INCLUDED
#include <pb.h>
#include "es_common_types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Indication whether the command has finished or it is still processing */
typedef enum _ES_CMD_STATE { 
    ES_CMD_STATE_PROCESSING = 1, /**< The command is being processed*/
    ES_CMD_STATE_COMPLETED = 2, /**< The command execution has been completed*/
    ES_CMD_STATE_INVAL = 3 /**< Invalid*/
} ES_CMD_STATE;

/* Struct definitions */
/**Command execute payload parameters*/
typedef struct _cmd_exec_req_pl { 
    char command[200]; /**< The command to be executed*/
    uint32_t command_id; /**< ID associated with the command*/
    uint32_t command_timeout; /**< Command timeout in seconds*/
    char command_type[15]; /**< Command type*/
    bool has_store_results;
    int32_t store_results; /**< Whether to store commands output in file*/
} cmd_exec_req_pl;

/**Command status request parameters*/
typedef struct _cmd_get_status_req_pl { 
    uint32_t command_id; /**< ID associated with the command*/
} cmd_get_status_req_pl;

/**Command get status response parameters*/
typedef struct _cmd_get_status_res_pl { 
    bool has_return_code;
    int64_t return_code; /**< Return code*/
    bool has_results_file;
    char results_file[200]; /**< ID associated with the command*/
    bool has_cmd_state;
    int32_t cmd_state; /**< Indication whether the command has finished or it is still processing*/
} cmd_get_status_res_pl;

/**Command execute response*/
typedef struct _es_cmd_exec_res { 
    response_hdr hdr; /**< Response header*/
} es_cmd_exec_res;

/**Command execute request*/
typedef struct _es_cmd_exec_req { 
    request_hdr hdr; /**< Request header*/
    cmd_exec_req_pl pl; /**< Payload*/
} es_cmd_exec_req;

/**Command get status request*/
typedef struct _es_cmd_get_status_req { 
    request_hdr hdr; /**< Request header*/
    cmd_get_status_req_pl pl; /**< Payload*/
} es_cmd_get_status_req;

/**Command get status response*/
typedef struct _es_cmd_get_status_res { 
    response_hdr hdr; /**< Response header*/
    bool has_pl;
    cmd_get_status_res_pl pl; /**< Payload*/
} es_cmd_get_status_res;

/**Execute a command on the target*/
typedef struct _cmd_exec_rpc { 
    pb_size_t which_payload;
    union {
        es_cmd_exec_req req;
        es_cmd_exec_res res;
    } payload; 
} cmd_exec_rpc;

/**Get the status of an executed command*/
typedef struct _cmd_get_status_rpc { 
    pb_size_t which_payload;
    union {
        es_cmd_get_status_req req;
        es_cmd_get_status_res res;
    } payload; 
} cmd_get_status_rpc;

/**ES RCE RPCs*/
typedef struct _es_rce_rpc { 
    pb_size_t which_rpc;
    union {
        cmd_exec_rpc cmd_exec;
        cmd_get_status_rpc cmd_get_status;
    } rpc; 
} es_rce_rpc;


/* Helper constants for enums */
#define _ES_CMD_STATE_MIN ES_CMD_STATE_PROCESSING
#define _ES_CMD_STATE_MAX ES_CMD_STATE_INVAL
#define _ES_CMD_STATE_ARRAYSIZE ((ES_CMD_STATE)(ES_CMD_STATE_INVAL+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define cmd_exec_req_pl_init_default             {"ls -l", 0u, 10u, "bin", false, 0}
#define es_cmd_exec_req_init_default             {request_hdr_init_default, cmd_exec_req_pl_init_default}
#define es_cmd_exec_res_init_default             {response_hdr_init_default}
#define cmd_exec_rpc_init_default                {0, {es_cmd_exec_req_init_default}}
#define cmd_get_status_req_pl_init_default       {0u}
#define es_cmd_get_status_req_init_default       {request_hdr_init_default, cmd_get_status_req_pl_init_default}
#define cmd_get_status_res_pl_init_default       {false, 0, false, "", false, 0}
#define es_cmd_get_status_res_init_default       {response_hdr_init_default, false, cmd_get_status_res_pl_init_default}
#define cmd_get_status_rpc_init_default          {0, {es_cmd_get_status_req_init_default}}
#define es_rce_rpc_init_default                  {0, {cmd_exec_rpc_init_default}}
#define cmd_exec_req_pl_init_zero                {"", 0, 0, "", false, 0}
#define es_cmd_exec_req_init_zero                {request_hdr_init_zero, cmd_exec_req_pl_init_zero}
#define es_cmd_exec_res_init_zero                {response_hdr_init_zero}
#define cmd_exec_rpc_init_zero                   {0, {es_cmd_exec_req_init_zero}}
#define cmd_get_status_req_pl_init_zero          {0}
#define es_cmd_get_status_req_init_zero          {request_hdr_init_zero, cmd_get_status_req_pl_init_zero}
#define cmd_get_status_res_pl_init_zero          {false, 0, false, "", false, 0}
#define es_cmd_get_status_res_init_zero          {response_hdr_init_zero, false, cmd_get_status_res_pl_init_zero}
#define cmd_get_status_rpc_init_zero             {0, {es_cmd_get_status_req_init_zero}}
#define es_rce_rpc_init_zero                     {0, {cmd_exec_rpc_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define cmd_exec_req_pl_command_tag              1
#define cmd_exec_req_pl_command_id_tag           2
#define cmd_exec_req_pl_command_timeout_tag      3
#define cmd_exec_req_pl_command_type_tag         4
#define cmd_exec_req_pl_store_results_tag        5
#define cmd_get_status_req_pl_command_id_tag     1
#define cmd_get_status_res_pl_return_code_tag    1
#define cmd_get_status_res_pl_results_file_tag   2
#define cmd_get_status_res_pl_cmd_state_tag      3
#define es_cmd_exec_res_hdr_tag                  1
#define es_cmd_exec_req_hdr_tag                  1
#define es_cmd_exec_req_pl_tag                   2
#define es_cmd_get_status_req_hdr_tag            1
#define es_cmd_get_status_req_pl_tag             2
#define es_cmd_get_status_res_hdr_tag            1
#define es_cmd_get_status_res_pl_tag             2
#define cmd_exec_rpc_req_tag                     1
#define cmd_exec_rpc_res_tag                     2
#define cmd_get_status_rpc_req_tag               1
#define cmd_get_status_rpc_res_tag               2
#define es_rce_rpc_cmd_exec_tag                  1
#define es_rce_rpc_cmd_get_status_tag            2

/* Struct field encoding specification for nanopb */
#define cmd_exec_req_pl_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   command,           1) \
X(a, STATIC,   REQUIRED, UINT32,   command_id,        2) \
X(a, STATIC,   REQUIRED, UINT32,   command_timeout,   3) \
X(a, STATIC,   REQUIRED, STRING,   command_type,      4) \
X(a, STATIC,   OPTIONAL, INT32,    store_results,     5)
#define cmd_exec_req_pl_CALLBACK NULL
#define cmd_exec_req_pl_DEFAULT (const pb_byte_t*)"\x0a\x05\x6c\x73\x20\x2d\x6c\x10\x00\x18\x0a\x22\x03\x62\x69\x6e\x28\x00\x00"

#define es_cmd_exec_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_cmd_exec_req_CALLBACK NULL
#define es_cmd_exec_req_DEFAULT NULL
#define es_cmd_exec_req_hdr_MSGTYPE request_hdr
#define es_cmd_exec_req_pl_MSGTYPE cmd_exec_req_pl

#define es_cmd_exec_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_cmd_exec_res_CALLBACK NULL
#define es_cmd_exec_res_DEFAULT NULL
#define es_cmd_exec_res_hdr_MSGTYPE response_hdr

#define cmd_exec_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define cmd_exec_rpc_CALLBACK NULL
#define cmd_exec_rpc_DEFAULT NULL
#define cmd_exec_rpc_payload_req_MSGTYPE es_cmd_exec_req
#define cmd_exec_rpc_payload_res_MSGTYPE es_cmd_exec_res

#define cmd_get_status_req_pl_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   command_id,        1)
#define cmd_get_status_req_pl_CALLBACK NULL
#define cmd_get_status_req_pl_DEFAULT (const pb_byte_t*)"\x08\x00\x00"

#define es_cmd_get_status_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_cmd_get_status_req_CALLBACK NULL
#define es_cmd_get_status_req_DEFAULT NULL
#define es_cmd_get_status_req_hdr_MSGTYPE request_hdr
#define es_cmd_get_status_req_pl_MSGTYPE cmd_get_status_req_pl

#define cmd_get_status_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT64,    return_code,       1) \
X(a, STATIC,   OPTIONAL, STRING,   results_file,      2) \
X(a, STATIC,   OPTIONAL, INT32,    cmd_state,         3)
#define cmd_get_status_res_pl_CALLBACK NULL
#define cmd_get_status_res_pl_DEFAULT NULL

#define es_cmd_get_status_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pl,                2)
#define es_cmd_get_status_res_CALLBACK NULL
#define es_cmd_get_status_res_DEFAULT NULL
#define es_cmd_get_status_res_hdr_MSGTYPE response_hdr
#define es_cmd_get_status_res_pl_MSGTYPE cmd_get_status_res_pl

#define cmd_get_status_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define cmd_get_status_rpc_CALLBACK NULL
#define cmd_get_status_rpc_DEFAULT NULL
#define cmd_get_status_rpc_payload_req_MSGTYPE es_cmd_get_status_req
#define cmd_get_status_rpc_payload_res_MSGTYPE es_cmd_get_status_res

#define es_rce_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,cmd_exec,rpc.cmd_exec),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,cmd_get_status,rpc.cmd_get_status),   2)
#define es_rce_rpc_CALLBACK NULL
#define es_rce_rpc_DEFAULT NULL
#define es_rce_rpc_rpc_cmd_exec_MSGTYPE cmd_exec_rpc
#define es_rce_rpc_rpc_cmd_get_status_MSGTYPE cmd_get_status_rpc

extern const pb_msgdesc_t cmd_exec_req_pl_msg;
extern const pb_msgdesc_t es_cmd_exec_req_msg;
extern const pb_msgdesc_t es_cmd_exec_res_msg;
extern const pb_msgdesc_t cmd_exec_rpc_msg;
extern const pb_msgdesc_t cmd_get_status_req_pl_msg;
extern const pb_msgdesc_t es_cmd_get_status_req_msg;
extern const pb_msgdesc_t cmd_get_status_res_pl_msg;
extern const pb_msgdesc_t es_cmd_get_status_res_msg;
extern const pb_msgdesc_t cmd_get_status_rpc_msg;
extern const pb_msgdesc_t es_rce_rpc_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cmd_exec_req_pl_fields &cmd_exec_req_pl_msg
#define es_cmd_exec_req_fields &es_cmd_exec_req_msg
#define es_cmd_exec_res_fields &es_cmd_exec_res_msg
#define cmd_exec_rpc_fields &cmd_exec_rpc_msg
#define cmd_get_status_req_pl_fields &cmd_get_status_req_pl_msg
#define es_cmd_get_status_req_fields &es_cmd_get_status_req_msg
#define cmd_get_status_res_pl_fields &cmd_get_status_res_pl_msg
#define es_cmd_get_status_res_fields &es_cmd_get_status_res_msg
#define cmd_get_status_rpc_fields &cmd_get_status_rpc_msg
#define es_rce_rpc_fields &es_rce_rpc_msg

/* Maximum encoded size of messages (where known) */
#define cmd_exec_req_pl_size                     241
#define cmd_exec_rpc_size                        1056
#define cmd_get_status_req_pl_size               6
#define cmd_get_status_res_pl_size               224
#define cmd_get_status_rpc_size                  1283
#define es_cmd_exec_req_size                     268
#define es_cmd_exec_res_size                     1053
#define es_cmd_get_status_req_size               32
#define es_cmd_get_status_res_size               1280
#define es_rce_rpc_size                          1286

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
