/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_ES_TEST_PB_H_INCLUDED
#define PB_ES_TEST_PB_H_INCLUDED
#include <pb.h>
#include "es_common_types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/**Hello test response*/
typedef struct _es_hello_test_res { 
    response_hdr hdr; /**< Response header*/
} es_hello_test_res;

/**Test Message configuration get request*/
typedef struct _es_test_cfg_get_req { 
    request_hdr hdr; /**< Request header*/
} es_test_cfg_get_req;

/**Test message response*/
typedef struct _es_test_cfg_set_res { 
    response_hdr hdr; /**< Response header*/
} es_test_cfg_set_res;

/**This is the payload of my hello test request*/
typedef struct _hello_test_req_pl { 
    bool has_param_str;
    char param_str[120]; /**< This is just a string parameter, which we used to print strings*/
    bool has_param_int64;
    int64_t param_int64; /**< This is just an int that we want to send*/
} hello_test_req_pl;

/**Test Message*/
typedef struct _loopback_req_pl { 
    char msg[1500]; /**< Test message to send*/
    double delay; /**< Response delay*/
} loopback_req_pl;

/**Test loopback response payload*/
typedef struct _loopback_res_pl { 
    bool has_msg;
    char msg[1500]; /**< Test message response*/
} loopback_res_pl;

/**Test Message configuration get response payload*/
typedef struct _test_cfg_get_res_pl { 
    bool has_param1;
    char param1[120]; /**< Test param1*/
    bool has_param2;
    double param2; /**< Test param2*/
    bool has_param3;
    int64_t param3; /**< Test param3*/
} test_cfg_get_res_pl;

/**Set Test Configuration Request Payload*/
typedef struct _test_cfg_set_req_pl { 
    bool has_param1;
    char param1[120]; /**< Test string parameter*/
    bool has_param2;
    double param2; /**< Test param2*/
    bool has_param3;
    int64_t param3; /**< Test param3*/
} test_cfg_set_req_pl;

/**Hello test request*/
typedef struct _es_hello_test_req { 
    request_hdr hdr; /**< Request header*/
    hello_test_req_pl pl; /**< Payload*/
} es_hello_test_req;

/**Test loopback request*/
typedef struct _es_loopback_req { 
    request_hdr hdr; /**< Request header*/
    loopback_req_pl pl; /**< Payload*/
} es_loopback_req;

/**Test loopback response*/
typedef struct _es_loopback_res { 
    response_hdr hdr; /**< Response header*/
    bool has_pl;
    loopback_res_pl pl; /**< Response Payload*/
} es_loopback_res;

/**Test Message configuration get response*/
typedef struct _es_test_cfg_get_res { 
    response_hdr hdr; /**< Response header*/
    bool has_pl;
    test_cfg_get_res_pl pl; /**< Payload*/
} es_test_cfg_get_res;

/**Test config set request*/
typedef struct _es_test_cfg_set_req { 
    request_hdr hdr; /**< Request header*/
    test_cfg_set_req_pl pl; /**< Payload*/
} es_test_cfg_set_req;

/**This is my Hello test RPC!*/
typedef struct _hello_test_rpc { 
    pb_size_t which_payload;
    union {
        es_hello_test_req req;
        es_hello_test_res res;
    } payload; 
} hello_test_rpc;

/**Sends a string and expects the same string as an answer.
The delay produces random 'processing' delay on the target*/
typedef struct _loopback_rpc { 
    pb_size_t which_payload;
    union {
        es_loopback_req req;
        es_loopback_res res;
    } payload; 
} loopback_rpc;

/**Retrieves the test configuration (counter part of test_cfg_set)*/
typedef struct _test_cfg_get_rpc { 
    pb_size_t which_payload;
    union {
        es_test_cfg_get_req req;
        es_test_cfg_get_res res;
    } payload; 
} test_cfg_get_rpc;

/**Send a test configuration which is persistent between reboots*/
typedef struct _test_cfg_set_rpc { 
    pb_size_t which_payload;
    union {
        es_test_cfg_set_req req;
        es_test_cfg_set_res res;
    } payload; 
} test_cfg_set_rpc;

/**ES Test RPCs*/
typedef struct _es_test_rpc { 
    pb_size_t which_rpc;
    union {
        loopback_rpc loopback;
        test_cfg_set_rpc test_cfg_set;
        test_cfg_get_rpc test_cfg_get;
        hello_test_rpc hello_test;
    } rpc; 
} es_test_rpc;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define loopback_req_pl_init_default             {"Test message", 0.0001}
#define es_loopback_req_init_default             {request_hdr_init_default, loopback_req_pl_init_default}
#define loopback_res_pl_init_default             {false, ""}
#define es_loopback_res_init_default             {response_hdr_init_default, false, loopback_res_pl_init_default}
#define loopback_rpc_init_default                {0, {es_loopback_req_init_default}}
#define test_cfg_set_req_pl_init_default         {false, "Test param1", false, 0, false, 0ll}
#define es_test_cfg_set_req_init_default         {request_hdr_init_default, test_cfg_set_req_pl_init_default}
#define es_test_cfg_set_res_init_default         {response_hdr_init_default}
#define test_cfg_set_rpc_init_default            {0, {es_test_cfg_set_req_init_default}}
#define es_test_cfg_get_req_init_default         {request_hdr_init_default}
#define test_cfg_get_res_pl_init_default         {false, "", false, 0, false, 0}
#define es_test_cfg_get_res_init_default         {response_hdr_init_default, false, test_cfg_get_res_pl_init_default}
#define test_cfg_get_rpc_init_default            {0, {es_test_cfg_get_req_init_default}}
#define es_hello_test_req_init_default           {request_hdr_init_default, hello_test_req_pl_init_default}
#define hello_test_req_pl_init_default           {false, "Hello from my test RPC!", false, 0ll}
#define es_hello_test_res_init_default           {response_hdr_init_default}
#define hello_test_rpc_init_default              {0, {es_hello_test_req_init_default}}
#define es_test_rpc_init_default                 {0, {loopback_rpc_init_default}}
#define loopback_req_pl_init_zero                {"", 0}
#define es_loopback_req_init_zero                {request_hdr_init_zero, loopback_req_pl_init_zero}
#define loopback_res_pl_init_zero                {false, ""}
#define es_loopback_res_init_zero                {response_hdr_init_zero, false, loopback_res_pl_init_zero}
#define loopback_rpc_init_zero                   {0, {es_loopback_req_init_zero}}
#define test_cfg_set_req_pl_init_zero            {false, "", false, 0, false, 0}
#define es_test_cfg_set_req_init_zero            {request_hdr_init_zero, test_cfg_set_req_pl_init_zero}
#define es_test_cfg_set_res_init_zero            {response_hdr_init_zero}
#define test_cfg_set_rpc_init_zero               {0, {es_test_cfg_set_req_init_zero}}
#define es_test_cfg_get_req_init_zero            {request_hdr_init_zero}
#define test_cfg_get_res_pl_init_zero            {false, "", false, 0, false, 0}
#define es_test_cfg_get_res_init_zero            {response_hdr_init_zero, false, test_cfg_get_res_pl_init_zero}
#define test_cfg_get_rpc_init_zero               {0, {es_test_cfg_get_req_init_zero}}
#define es_hello_test_req_init_zero              {request_hdr_init_zero, hello_test_req_pl_init_zero}
#define hello_test_req_pl_init_zero              {false, "", false, 0}
#define es_hello_test_res_init_zero              {response_hdr_init_zero}
#define hello_test_rpc_init_zero                 {0, {es_hello_test_req_init_zero}}
#define es_test_rpc_init_zero                    {0, {loopback_rpc_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define es_hello_test_res_hdr_tag                1
#define es_test_cfg_get_req_hdr_tag              1
#define es_test_cfg_set_res_hdr_tag              1
#define hello_test_req_pl_param_str_tag          1
#define hello_test_req_pl_param_int64_tag        2
#define loopback_req_pl_msg_tag                  1
#define loopback_req_pl_delay_tag                2
#define loopback_res_pl_msg_tag                  1
#define test_cfg_get_res_pl_param1_tag           1
#define test_cfg_get_res_pl_param2_tag           2
#define test_cfg_get_res_pl_param3_tag           3
#define test_cfg_set_req_pl_param1_tag           1
#define test_cfg_set_req_pl_param2_tag           2
#define test_cfg_set_req_pl_param3_tag           3
#define es_hello_test_req_hdr_tag                1
#define es_hello_test_req_pl_tag                 2
#define es_loopback_req_hdr_tag                  1
#define es_loopback_req_pl_tag                   2
#define es_loopback_res_hdr_tag                  1
#define es_loopback_res_pl_tag                   2
#define es_test_cfg_get_res_hdr_tag              1
#define es_test_cfg_get_res_pl_tag               2
#define es_test_cfg_set_req_hdr_tag              1
#define es_test_cfg_set_req_pl_tag               2
#define hello_test_rpc_req_tag                   1
#define hello_test_rpc_res_tag                   2
#define loopback_rpc_req_tag                     1
#define loopback_rpc_res_tag                     2
#define test_cfg_get_rpc_req_tag                 1
#define test_cfg_get_rpc_res_tag                 2
#define test_cfg_set_rpc_req_tag                 1
#define test_cfg_set_rpc_res_tag                 2
#define es_test_rpc_loopback_tag                 1
#define es_test_rpc_test_cfg_set_tag             2
#define es_test_rpc_test_cfg_get_tag             3
#define es_test_rpc_hello_test_tag               4

/* Struct field encoding specification for nanopb */
#define loopback_req_pl_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   msg,               1) \
X(a, STATIC,   REQUIRED, DOUBLE,   delay,             2)
#define loopback_req_pl_CALLBACK NULL
#define loopback_req_pl_DEFAULT (const pb_byte_t*)"\x0a\x0c\x54\x65\x73\x74\x20\x6d\x65\x73\x73\x61\x67\x65\x11\x2d\x43\x1c\xeb\xe2\x36\x1a\x3f\x00"

#define es_loopback_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_loopback_req_CALLBACK NULL
#define es_loopback_req_DEFAULT NULL
#define es_loopback_req_hdr_MSGTYPE request_hdr
#define es_loopback_req_pl_MSGTYPE loopback_req_pl

#define loopback_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   msg,               1)
#define loopback_res_pl_CALLBACK NULL
#define loopback_res_pl_DEFAULT NULL

#define es_loopback_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pl,                2)
#define es_loopback_res_CALLBACK NULL
#define es_loopback_res_DEFAULT NULL
#define es_loopback_res_hdr_MSGTYPE response_hdr
#define es_loopback_res_pl_MSGTYPE loopback_res_pl

#define loopback_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define loopback_rpc_CALLBACK NULL
#define loopback_rpc_DEFAULT NULL
#define loopback_rpc_payload_req_MSGTYPE es_loopback_req
#define loopback_rpc_payload_res_MSGTYPE es_loopback_res

#define test_cfg_set_req_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   param1,            1) \
X(a, STATIC,   OPTIONAL, DOUBLE,   param2,            2) \
X(a, STATIC,   OPTIONAL, INT64,    param3,            3)
#define test_cfg_set_req_pl_CALLBACK NULL
#define test_cfg_set_req_pl_DEFAULT (const pb_byte_t*)"\x0a\x0b\x54\x65\x73\x74\x20\x70\x61\x72\x61\x6d\x31\x11\x00\x00\x00\x00\x00\x00\x00\x00\x18\x00\x00"

#define es_test_cfg_set_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_test_cfg_set_req_CALLBACK NULL
#define es_test_cfg_set_req_DEFAULT NULL
#define es_test_cfg_set_req_hdr_MSGTYPE request_hdr
#define es_test_cfg_set_req_pl_MSGTYPE test_cfg_set_req_pl

#define es_test_cfg_set_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_test_cfg_set_res_CALLBACK NULL
#define es_test_cfg_set_res_DEFAULT NULL
#define es_test_cfg_set_res_hdr_MSGTYPE response_hdr

#define test_cfg_set_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define test_cfg_set_rpc_CALLBACK NULL
#define test_cfg_set_rpc_DEFAULT NULL
#define test_cfg_set_rpc_payload_req_MSGTYPE es_test_cfg_set_req
#define test_cfg_set_rpc_payload_res_MSGTYPE es_test_cfg_set_res

#define es_test_cfg_get_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_test_cfg_get_req_CALLBACK NULL
#define es_test_cfg_get_req_DEFAULT NULL
#define es_test_cfg_get_req_hdr_MSGTYPE request_hdr

#define test_cfg_get_res_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   param1,            1) \
X(a, STATIC,   OPTIONAL, DOUBLE,   param2,            2) \
X(a, STATIC,   OPTIONAL, INT64,    param3,            3)
#define test_cfg_get_res_pl_CALLBACK NULL
#define test_cfg_get_res_pl_DEFAULT NULL

#define es_test_cfg_get_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pl,                2)
#define es_test_cfg_get_res_CALLBACK NULL
#define es_test_cfg_get_res_DEFAULT NULL
#define es_test_cfg_get_res_hdr_MSGTYPE response_hdr
#define es_test_cfg_get_res_pl_MSGTYPE test_cfg_get_res_pl

#define test_cfg_get_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define test_cfg_get_rpc_CALLBACK NULL
#define test_cfg_get_rpc_DEFAULT NULL
#define test_cfg_get_rpc_payload_req_MSGTYPE es_test_cfg_get_req
#define test_cfg_get_rpc_payload_res_MSGTYPE es_test_cfg_get_res

#define es_hello_test_req_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1) \
X(a, STATIC,   REQUIRED, MESSAGE,  pl,                2)
#define es_hello_test_req_CALLBACK NULL
#define es_hello_test_req_DEFAULT NULL
#define es_hello_test_req_hdr_MSGTYPE request_hdr
#define es_hello_test_req_pl_MSGTYPE hello_test_req_pl

#define hello_test_req_pl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   param_str,         1) \
X(a, STATIC,   OPTIONAL, INT64,    param_int64,       2)
#define hello_test_req_pl_CALLBACK NULL
#define hello_test_req_pl_DEFAULT (const pb_byte_t*)"\x0a\x17\x48\x65\x6c\x6c\x6f\x20\x66\x72\x6f\x6d\x20\x6d\x79\x20\x74\x65\x73\x74\x20\x52\x50\x43\x21\x10\x00\x00"

#define es_hello_test_res_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  hdr,               1)
#define es_hello_test_res_CALLBACK NULL
#define es_hello_test_res_DEFAULT NULL
#define es_hello_test_res_hdr_MSGTYPE response_hdr

#define hello_test_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,req,payload.req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,res,payload.res),   2)
#define hello_test_rpc_CALLBACK NULL
#define hello_test_rpc_DEFAULT NULL
#define hello_test_rpc_payload_req_MSGTYPE es_hello_test_req
#define hello_test_rpc_payload_res_MSGTYPE es_hello_test_res

#define es_test_rpc_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,loopback,rpc.loopback),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,test_cfg_set,rpc.test_cfg_set),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,test_cfg_get,rpc.test_cfg_get),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rpc,hello_test,rpc.hello_test),   4)
#define es_test_rpc_CALLBACK NULL
#define es_test_rpc_DEFAULT NULL
#define es_test_rpc_rpc_loopback_MSGTYPE loopback_rpc
#define es_test_rpc_rpc_test_cfg_set_MSGTYPE test_cfg_set_rpc
#define es_test_rpc_rpc_test_cfg_get_MSGTYPE test_cfg_get_rpc
#define es_test_rpc_rpc_hello_test_MSGTYPE hello_test_rpc

extern const pb_msgdesc_t loopback_req_pl_msg;
extern const pb_msgdesc_t es_loopback_req_msg;
extern const pb_msgdesc_t loopback_res_pl_msg;
extern const pb_msgdesc_t es_loopback_res_msg;
extern const pb_msgdesc_t loopback_rpc_msg;
extern const pb_msgdesc_t test_cfg_set_req_pl_msg;
extern const pb_msgdesc_t es_test_cfg_set_req_msg;
extern const pb_msgdesc_t es_test_cfg_set_res_msg;
extern const pb_msgdesc_t test_cfg_set_rpc_msg;
extern const pb_msgdesc_t es_test_cfg_get_req_msg;
extern const pb_msgdesc_t test_cfg_get_res_pl_msg;
extern const pb_msgdesc_t es_test_cfg_get_res_msg;
extern const pb_msgdesc_t test_cfg_get_rpc_msg;
extern const pb_msgdesc_t es_hello_test_req_msg;
extern const pb_msgdesc_t hello_test_req_pl_msg;
extern const pb_msgdesc_t es_hello_test_res_msg;
extern const pb_msgdesc_t hello_test_rpc_msg;
extern const pb_msgdesc_t es_test_rpc_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define loopback_req_pl_fields &loopback_req_pl_msg
#define es_loopback_req_fields &es_loopback_req_msg
#define loopback_res_pl_fields &loopback_res_pl_msg
#define es_loopback_res_fields &es_loopback_res_msg
#define loopback_rpc_fields &loopback_rpc_msg
#define test_cfg_set_req_pl_fields &test_cfg_set_req_pl_msg
#define es_test_cfg_set_req_fields &es_test_cfg_set_req_msg
#define es_test_cfg_set_res_fields &es_test_cfg_set_res_msg
#define test_cfg_set_rpc_fields &test_cfg_set_rpc_msg
#define es_test_cfg_get_req_fields &es_test_cfg_get_req_msg
#define test_cfg_get_res_pl_fields &test_cfg_get_res_pl_msg
#define es_test_cfg_get_res_fields &es_test_cfg_get_res_msg
#define test_cfg_get_rpc_fields &test_cfg_get_rpc_msg
#define es_hello_test_req_fields &es_hello_test_req_msg
#define hello_test_req_pl_fields &hello_test_req_pl_msg
#define es_hello_test_res_fields &es_hello_test_res_msg
#define hello_test_rpc_fields &hello_test_rpc_msg
#define es_test_rpc_fields &es_test_rpc_msg

/* Maximum encoded size of messages (where known) */
#define es_hello_test_req_size                   159
#define es_hello_test_res_size                   1053
#define es_loopback_req_size                     1538
#define es_loopback_res_size                     2558
#define es_test_cfg_get_req_size                 24
#define es_test_cfg_get_res_size                 1197
#define es_test_cfg_set_req_size                 168
#define es_test_cfg_set_res_size                 1053
#define es_test_rpc_size                         2564
#define hello_test_req_pl_size                   132
#define hello_test_rpc_size                      1056
#define loopback_req_pl_size                     1511
#define loopback_res_pl_size                     1502
#define loopback_rpc_size                        2561
#define test_cfg_get_res_pl_size                 141
#define test_cfg_get_rpc_size                    1200
#define test_cfg_set_req_pl_size                 141
#define test_cfg_set_rpc_size                    1056

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
